### ISSUE TITLE
Run current version of model on data for each strain alone and compare to results when run with multiple strain data

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#10]
@Nwilli31 will do the following:
* run the parameter estimation with wild type data alone
* use those parameters to run a forward simulation with the data from each strain deleted from the network
* run the parameter estimation with each deletion strain data alone
* run the forward simulation with the corresponding deletion strain data

**Comment by Nwilli31** [comment]
We have decided to do estimations of the individual strains using the 2014b MATLAB version with the code from the BIOL398 course. 

We will also be running forward simulations of the deletion strains that contain the optimized parameters (threshold values, production rates, and network weights) from the estimation of the wt data - what was detailed above.

**Comment by GraceJohnson** [comment]
Here is the wiki page with our notes: http://openwetware.org/wiki/GRNmap_Testing_Report:_Strain_Run_Comparisons_2015-05-27#Results_and_Discussion

**Comment by kdahlquist** [comment]
We need to dive deeper into this to explain what is happening with all these results.  
* Look at your bar charts and discuss in English sentences the relationships you see.
* Look at the individual expression plots to see if you can explain what is going on.
* Figure out the fits of the individual genes by getting the sum of squares of error for the individual genes to see which have good fits and which have poor fits.
* Look up the individual within-strain ANOVA p values to see if the genes with good fits also have significant p values or not.  You could imagine that either good fit = small p value, good fit = large p value, or no relationship.  The relationship might also be with magnitude of the fold changes or the amount of variance alone.

**Comment by kdahlquist** [comment]
@GraceJohnson analyzed genes with no inputs at all and @Nwilli31 analyzed genes with auto-regulation and no additional inputs.  We will continue down this road by:
* grouping genes according to the number of inputs they have
* analyzing those groups of genes in the same way that @GraceJohnson and @Nwilli31 have been doing.

**Comment by kdahlquist** [comment]
I bumped this one down a notch because we are not working on this this week.  We will need to review the results from SURP 2015 to decide whether to close this issue or whether it needs new work.  Since the current priority 0 is to work on crunching the array data with the new normalization, we will get to this later.  It merits discussion at a future lab meeting.

**Comment by kdahlquist** [comment]
This issue was from Summer 2015 and hasn't been touched.  If this needs to be revisited, we will start another issue for it.
