### ISSUE TITLE
No output files for .xlsx or .mat created after changing all inital guesses for weights to 0 in running wt alone

### ISSUE THREAD

**Issue by Nwilli31** [kdahlquist/GRNmap#100]
This is the following error message that appears: 

<stopping criteria details>

Error using copyfile
No matching files were found.

Error in output (line 20)
copyfile([input_file '.xlsx'], output_file);

Error in GRNmodel (line 19)
GRNstruct = output(GRNstruct);
 
All the figures are created and saved, but not Excel or MATLAB files.

**Comment by kdahlquist** [comment]
@Nwilli31 should e-mail @trixr4kdz the input file you used so she can track the bug.  Also, when reporting a bug, state the MATLAB version and version of the code you are using.

**Comment by Nwilli31** [comment]
I figured out that when running MATLAB 2014b with the code used for the BIOL398 course, the input file must be .xlsx.

I reran the model and used the input file saved as .xlsx and I received the .mat and the .xlsx output files after MATLAB finished running.

The original file used was .xls.

**Comment by kdahlquist** [comment]
@Nwilli31, if this is no longer an issue, please close it.
