### ISSUE TITLE
Question about viewing the number of iterations

### ISSUE THREAD

**Issue by trixr4kdz** [kdahlquist/GRNmap#101]
After closing out the window that gives a figure every 100 iterations, is there a way to open the output .mat file and see how many iterations were taken for a given run (i.e. we want to see the information that tracks how many iterations were actually made)?

**Comment by bengfitzpatrick** [comment]
the global variable counter contains this information. I recommend creating a field in the GRNstruct.GRNOutput structure called counter and assigning it after line 67 of the lse routine, where the penalty term is saved out.

**Comment by kdahlquist** [comment]
done and closing
