### ISSUE TITLE
Computation for standard deviation

### ISSUE THREAD

**Issue by trixr4kdz** [kdahlquist/GRNmap#102]
For the "strain designation_sigmas" aka standard deviations, which function would contain the computations for it? I was thinking it would be either in lse.m or general_least_squares_error.m

**Comment by trixr4kdz** [comment]
Just an update on this. I think I found the code fragment that calculates the std deviation. Can you confirm?

```Matlab
GRNstruct.microData(i).avg(:,iT) = mean(data,2);
        GRNstruct.microData(i).stdev(:,iT) =  std(data,0,2);
        log2FC(i).avg(:,iT) = mean(data,2);
        log2FC(i).stdev(:,iT) = std(data,0,2);
end
```

**Comment by bengfitzpatrick** [comment]
current output is not correct.  Just a sheet with a column of zeros. It appears that the avg and stdev fields are not being computed correctly either.  This code snip has a big error... the avg and stdev arrays appear to be repeatedly zeroed out with a single column reassigned afterward.  The comment is ironically correct... the preallocation SHOULD be done elsewhere.

    for iT = 1:GRNstruct.GRNParams.num_times
        data = GRNstruct.microData(i).data(2:end,GRNstruct.microData(i).t(iT).indx);
        % Preallocate these arrays. Should probably be done somewhere else
        GRNstruct.microData(i).avg = zeros(size(data,1),1);
        GRNstruct.microData(i).stdev = zeros(size(data,1),1);
        log2FC(i).avg = zeros(size(data,1),1);
        log2FC(i).stdev = zeros(size(data,1),1);
        
        GRNstruct.microData(i).avg(:,iT) = mean(data,2);
        GRNstruct.microData(i).stdev(:,iT) =  std(data,0,2);
        log2FC(i).avg(:,iT) = mean(data,2);
        log2FC(i).stdev(:,iT) = std(data,0,2);
    end

**Comment by trixr4kdz** [comment]
By current output, did you mean that the values for all the worksheets in the output file are all just zeroes or just the ones for the sigmas?

Just to clarify though, we would want the standard deviation for each unique timepoints, yes? Like if we have replicates of timepoints 15, 30, and 60, we would have three different columns of standard deviations? Also, is GRNstruct.microData exactly the same as the global var log2FC?

**Comment by kdahlquist** [comment]
To answer the first part of the question, we would want standard deviations for each timepoint, so if you had 15, 30, and 60, you would have a standard deviation column for each one.

**Comment by kdahlquist** [comment]
This issue is redundant with #9.  I will close #9 and leave this one open.

**Comment by bengfitzpatrick** [comment]
@trixr4kdz when I run the current beta, I get a "strain designation_sigmas" sheet that has one column of zeros.  When I look at the GRNstruct data, the stdev array (which should be number of times by number of genes as @kdahlquist noted in an upstream comment) has zeros except for a final column of NaNs (and one too many columns).  load the .mat file into matlab and look at the entries.  Running the test current test cases would lead to 0 sigmas, as the data points are identical.  We (I) should create a couple more test cases by noising up those pristine test cases.

**Comment by trixr4kdz** [comment]
Ok I figured out why the last column is NaNs. In the optimization_parameter worksheet, the times are 0.4, 0.8, 1.2, and 1.4. However, the timepoints in the log2_expression worksheets are 0.4, 0.8, 1.2, and 1.6. The readInputSheet function tries to match the timepoints but since the last ones are different, it doesn't read the values corresponding to the last timepoint correctly.

**Comment by bengfitzpatrick** [comment]
good catch, @trixr4kdz -- who's working the test file prep? @tessaam ??

**Comment by trixr4kdz** [comment]
I've edited the code so the standard deviations should be correct now. I did notice when I ran the code with the 4-genes_6-edges sample that there were standard deviations that are 10^-17 (or something similarly small) instead of just 0.

**Comment by kdahlquist** [comment]
@tessaam should run the larger 22-gene_47-edge network to verify that the calculations are being done properly.  Just run one case and then compare the results of the sigmas sheet to calculations you compute in Excel to verify that MATLAB is computing it correctly.  run with all strains

**Comment by kdahlquist** [comment]
make a new folder under "test-files" called "validation-tests" to contain extra files used for validation that are not directly part of the estimation or forward tests.

**Comment by tessaam** [comment]
The "sigmas" output sheet for the 22-genes_47-edges_Dahlquist-data_Sigmoidal_estimation_fixb-1_fixP-1_no-graph was tested by comparing the standard deviation values calculated by MATLAB with ones calculated by excel. The standard deviations of the log2_expression data was calculated for  wt, dcin5, dgln3, dhap4, dhmo1, and dzap1. The maximum difference between the excel calculated sigmas and the MATLAB calculated sigmas was E-15. 

http://openwetware.org/wiki/GRNmap_Testing_Report_Sigmas_2015-06-03_TM

**Comment by kdahlquist** [comment]
verified by @tessaam so closing
