### ISSUE TITLE
Save diagnostic figure automatically

### ISSUE THREAD

**Issue by GraceJohnson** [kdahlquist/GRNmap#103]
We would like the progress (counter) diagnostic figure to be saved automatically with all the other output figures. We would like to be able to see how many iterations the model took, and potentially be capable of seeing the parameter counter figures. We would like this change to be independent of whether you select make graphs or do not make graphs (in other words, it should always happen).

**Comment by trixr4kdz** [comment]
@bengfitzpatrick fixed this and I've pushed the updated files to the beta branch

**Comment by kdahlquist** [comment]
verified by @tessaam
