### ISSUE TITLE
UH 2752 computer lab access

### ISSUE THREAD

**Issue by bengfitzpatrick** [kdahlquist/GRNmap#104]
@tessaam @trixr4kdz @NAnguiano need to visit the one card office for an update for access to the Math computer lab (2752) across from @bengfitzpatrick office. @GraceJohnson @Nwilli31 should have access now: tessa, trixie, and nicole will have access once their cards are updated.

**Comment by kdahlquist** [comment]
Did you want to give @anuvarsh access?  @NAnguiano is actually gone for the summer already, FYI.

**Comment by bengfitzpatrick** [comment]
I will ping Jill for @anuvarsh access.

**Comment by bengfitzpatrick** [comment]
@anuvarsh @tessaam  please go to 1 card office to gain access to UH2752 computer lab.
@GraceJohnson @Nwilli31 please check that your 1 cards open the UH2752 door.

**Comment by kdahlquist** [comment]
I am going to close this; if people discover they can't access the room and need to, then we will open another issue about it.
