### ISSUE TITLE
Michaelis-menten model with unregulated genes not being computed correctly; (no_inputs) variable

### ISSUE THREAD

**Issue by trixr4kdz** [kdahlquist/GRNmap#105]
I think there is a bug when using the michaelis-menten model when there is no gene being regulated. Should we make test cases for genes that are not regulated or is it guaranteed that the Excel file has been modified by the user to only have regulated genes?

**Comment by kdahlquist** [comment]
There is global variable called no_inputs that is in the Michaelis-Menten.m function and general_network_dynamics_mm.m.  There is a loop using it.

**Comment by kdahlquist** [comment]
@bengfitzpatrick needs to look at this.

**Comment by kdahlquist** [comment]
We have disabled the Michaelis-Menten function, so I'm backlogging this bug.
