### ISSUE TITLE
merge beta and master and create release v1.0.8

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#109]
merge beta and master and create release v1.0.8

**Comment by kdahlquist** [comment]
Remember that we need to update the release notes, the About page and News pages.

**Comment by trixr4kdz** [comment]
Beta has been merged with master, but the lab computers seem to not have the MATLAB Compiler so I couldn't make the executable

**Comment by kdahlquist** [comment]
The lab computers do not, only the ones in my research lab.  I know I got the key back from you, but if you come during the day, me or someone else in the department can let you in.  Or you could wait until Monday. 


Kam D. Dahlquist, Ph.D.
Associate Professor of Biology
Loyola Marymount University
http://myweb.lmu.edu/kdahlqui



-------- Original message --------

**Comment by trixr4kdz** [comment]
Ok I can come in around 11 tomorrow

**Comment by kdahlquist** [comment]
I won't be there at 11 but someone in the department should be able to let you in.  All the faculty and staff have a key.


Kam D. Dahlquist, Ph.D.
Associate Professor of Biology
Loyola Marymount University
http://myweb.lmu.edu/kdahlqui



-------- Original message --------

**Comment by trixr4kdz** [comment]
Updated the release to include the executable. Also updated the release notes on the About page and the News page

**Comment by kdahlquist** [comment]
done
