### ISSUE TITLE
Check b estimation for genes with no inputs

### ISSUE THREAD

**Issue by GraceJohnson** [kdahlquist/GRNmap#111]
@GraceJohnson will provide input and output sheets to @bengfitzpatrick. Problem genes (with no inputs) are SKO1, FHL1, SWI6. The code is giving a non-0 b for these genes.

**Comment by bengfitzpatrick** [comment]
estimation is working correctly, but the array used to write data to the spreadsheet is not being properly initialized, so extraneous non-zero data is being written to the "no input" components of the b vector. I will update the beta branch soon.

**Comment by bengfitzpatrick** [comment]
@trixr4kdz @kdahlquist the new beta code correcting this initialization problem is on lionshare, descriptively named GRNmap-beta-bgf-2.zip If you could push it, Trixie, that would be great. I have not had time to install and investigate the git package.

**Comment by kdahlquist** [comment]
junk data in a local variable, variable name being reused.  @bengfitzpatrick has fixed, but needs to be tested by @GraceJohnson

**Comment by GraceJohnson** [comment]
Beta tested. Update was successful - genes with no inputs had estimated b-values of 0 in the output sheet. Result files can be found here: http://openwetware.org/wiki/Katherine_Grace_Johnson_Electronic_Lab_Notebook#June_15.2C_2015

**Comment by bengfitzpatrick** [comment]
checked and closed
