### ISSUE TITLE
Output lines from all strains run seem to be averages of all data, rather than individual lines for each strain.

### ISSUE THREAD

**Issue by GraceJohnson** [kdahlquist/GRNmap#112]
Output lines from all strains run seem to be averages of all data, rather than individual lines for each strain. Is the plotting of this line somehow involved in the calculations/estimation of parameters?

**Comment by bengfitzpatrick** [comment]
@GraceJohnson I need a little more explanation?

**Comment by GraceJohnson** [comment]
When running two or more strains together, many times the output lines model the average of all data points, instead of having distinct lines for each strain. Examples are shown in the last slide of the powerpoint in the discussion section of http://openwetware.org/wiki/GRNmap_Testing_Report:_Strain_Run_Comparisons_2015-05-27.

**Comment by kdahlquist** [comment]
discussed at lab meeting on 6/10/15.  degradation rate rules for down-regulation
