### ISSUE TITLE
Dynamics of model do not fit t60 data points when those data points do not fit the production/degradation trend

### ISSUE THREAD

**Issue by GraceJohnson** [kdahlquist/GRNmap#113]
Dynamics of model do not fit t60 data points when those data points do not fit the production/degradation trend. Is it possible that the production/degradation trend is overpowering input dynamics?

**Comment by bengfitzpatrick** [comment]
@GraceJohnson I need you to post some results.  can you paste some plots into a ppt and put it on openwetware?

**Comment by GraceJohnson** [comment]
The powerpoint is in the discussion section of this page, http://openwetware.org/wiki/GRNmap_Testing_Report:_Strain_Run_Comparisons_2015-05-27, and is titled GRNmap testing analysis. Slides 13 and 15 contain the most relevant plot. @Nwilli31 will post another ppt containing plots of more genes that demonstrate this trend.

**Comment by Nwilli31** [comment]
On the same page @GraceJohnson mentioned, there is another powerpoint titled: Poor Fitting T60 Model to Data Points that can be downloaded. The genes seen in this powerpoint have the most noticeable shortcomings in the model's approach to fit the data points.

**Comment by kdahlquist** [comment]
if the gene is not regulated by any of the deleted genes, it won't affect by the deletion.
