### ISSUE TITLE
release v1.0.10 and executable

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#115]
package two test files
* 22-gene_47-edge, sigmoidal, graphs, estimate P and b
* 4-gene_6-edge, sigmoidal, graphs, estimate P and fix b
put them in a folder called "data_samples > input" and put the corresponding output .xlsx files in a folder "data_samples > output"

with the corresponding release notes, About page, download page, news.

**Comment by tessaam** [comment]
@kdahlquist 
*22-gene_47-edge, sigmoidal, graphs, estimate P and b took an hour to run (100,000 iterations) 
*4-gene_6-edge, sigmoidal, graphs, estimate P and fix b took under three minutes

**Comment by kdahlquist** [comment]
We won't have time to do this this week, but we should try to run the executable and the source code version on the same computer to see the performance difference.  We could do this in my lab if we run the source code first and then I uninstall MATLAB and then we install the executable.

**Comment by kdahlquist** [comment]
Also @tessaam , look at the RAM and processor speed on that laptop and compare it to the minimums I recommend on the issue #79 .  Right-click on the computer icon on the desktop and select "Properties" from the menu to see the RAM and processor speed.

**Comment by trixr4kdz** [comment]
I've just published v1.0.10 with the data_samples folder and @tessaam is currently testing it on the laptop.

**Comment by bengfitzpatrick** [comment]
@tessaam @kdahlquist we should try fix_P = 0 and fix_b = 1 for the 22-gene_47-edge example... maybe it'll be faster.

**Comment by trixr4kdz** [comment]
We did not have a chance to run the executable with the larger network because of the time it takes to run, but we tested it on the 4-gene_6-edge network and it worked.

**Comment by bengfitzpatrick** [comment]
@kdahlquist I ran both test input files.  Output files are written to the input folder not the output folder.  If that's not a problem this issue can be closed.  Perhaps this is a functionality problem that should become its own issue.

**Comment by kdahlquist** [comment]
@bengfitzpatrick , sorry I forgot to respond to this.  This was actually by design.  The output folder has the sample output files already packaged in it.  So when the user runs the sample input, they will be saved to the same folder the input files are in and will not overwrite the sample output.  They can then compare their output to the sample provided.

I think we do need to address this issue of overwriting output files.  As part of issue #37, we discussed detecting whether output files with the same name exist in the folder and then incrementing the filename with 1, 2, etc., instead of overwriting.
