### ISSUE TITLE
@bengfitzpatrick will redo L-curve and driver script which automates it

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#116]
@bengfitzpatrick will redo L-curve and driver script which automates it

**Comment by bengfitzpatrick** [comment]
@kdahlquist  : L-curve suggests alpha = 0.001 instead of current 0.01.  Will post details later today. You may want to test this yourself with the current "large" network.  

FYI, the small network's alpha is okay -- that one (due to the lack of noise in measurements: synthetic data) needs a very small alpha.

**Comment by kdahlquist** [comment]
@bengfitzpatrick , remind me, the alpha values are then specific to the structure and genes in a particular network.  When you say "large" network, I assume you mean the 22-gene_47-edge network that @tessaam made the 16 permutations for and not the 21-gene_50-edge network that @NAnguiano and @GraceJohnson have been working on, right?

**Comment by bengfitzpatrick** [comment]
@kdahlquist -- roughly speaking the alpha value represents the ratio of measurement uncertainty to parametric uncertainty.  It's related to the genes mostly through the measurement variance and the network through the range of magnitudes of the parameters. 

Now that we've gotten the scaling corrected, this alpha value should work for a reasonable range of networks for your data.  I would expect high teens to low 30s for genes and 30 to 70 connections would hold up okay for this alpha. You can try it for either of these meso-scale test cases, and I'd expect it to work well.

We'll do some more testing next week, once I've put the L curve driver through a couple more preliminary paces.

**Comment by kdahlquist** [comment]
OK, sounds good.  @tessaam and @Nwilli31 and @GraceJohnson will need to update their input files accordingly.

I'm running the 22-genes_47-edges_Dahlquist-data_Sigmoidal_estimation_fixb-0_fixP-0_graph.xlsx from @tessaam right now and the counter is up to 90000.  I'll report what I get when I finish.

**Comment by bengfitzpatrick** [comment]
@kdahlquist please try to fix_b = 1 too!

**Comment by kdahlquist** [comment]
@bengfitzpatrick, I just did it and it used 71218 when fix_b=1 vs 115810 when fix_b=0.  This particular network has MIG2 in it and needs b to be estimated to effectively model the high expression at t15.

By the way, I'm really liking the individual SSE's in the optimization_diagnostics output sheet.  It's very easy to see at a glance which genes are fit well and not.  And it's easy to compare runs.  For example the overall LSE for when both P and b are estimated is 0.785897065, while it is 1.026851834 when only P is estimated.  Then you can see that MIG2 is a big culprit in this because the individual SSE for wt jumps from 64 to 142.

**Comment by kdahlquist** [comment]
L-curve has been redone, but the driver script is not ready.

**Comment by bengfitzpatrick** [comment]
L curve driver is now available. Tested on the master branch.  Needs an actual test design: we are out-of-order on TDD of this.  Bugs may exist -- beware. In particular check where the result is being written!!! Testing needs to include the fix_b and fix_P parameters.  Functionality improvements are needed too. The code uses a vector of alpha's specified in the code, and it produces an array in .mat format that can be used to plot the actual L curve.

The L Curve Driver currently requires a matlab-capable user, as the code needs to be edited to specify the list of potential alpha values comprising the parameter of the L-curve.  These are set in the vector alphaList.  This list should be constructed in descending order (largest first, smallest last). The output is in .mat format as well.

The code copies a single input file repeatedly. Each new input file is an estimation input file for an alpha in the alphaList vector. The code writes the alpha value from the list into the appropriate cell of the "optimization_parameters" sheet. Currently that cell is "B2".  The code runs the estimation routine for each alpha, generating the usual output files, as well as an array LCurveData with three columns: alpha's, lse's, and penalties.  The traditional L-Curve plot is lse vs penalty. This array is saved out as a mat file.

One additional tweak of the code is that it uses previous results: the optimized parameter values are written to the initial guess sheets for subsequent estimation runs, presumably accelerating the convergence of fmincon. This is performed by reading the output of case alphaList(i-1) and writing that data to the input of alphaList(i).

Functionality considerations: we should probably plot the L Curve after the code completes.  Maybe we should ask the user for alpha values.

**Comment by kdahlquist** [comment]
I just committed the code from @bengfitzpatrick on a new branch called "L-curve"

**Comment by kdahlquist** [comment]
@bengfitzpatrick is going to suspend work on this for the next week while we are sorting out the variable names (#119, #129).

**Comment by trixr4kdz** [comment]
Actually, the change to the variable names have been reverted back so beta now has the original names from the last version. I moved the commit for the changed variable names to a different branch so it's safe to run beta now.

**Comment by bengfitzpatrick** [comment]
merge beta and L-curve branches new issue
