### ISSUE TITLE
Time the length of the run and output it to the optimization_diagnostics worksheet

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#117]
In XMLPipeDB's GenMAPP Builder, we record the time it took to import data into the database and the information displays when it is done.  It would be nice if we could add this feature to GRNmap so that if you started a run and then went away to get coffee (lunch, nap...) and came back when it was finished you would know how long it took.  Ideally, this could be output to the optimization_diagnostics sheet and recorded for posterity.

**Comment by bengfitzpatrick** [comment]
this is relatively easy to do.  matlab has tic and toc to start and stop timers.  I can add that to the beta.

**Comment by kdahlquist** [comment]
Note that when running GRNmap from code, the user can select "run and time" to get the time of the run.

**Comment by kdahlquist** [comment]
Duplicated by #195
