### ISSUE TITLE
Clean up format and variable names of input and output worksheets

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#119]
We have successfully cleaned up the names, presence/absence, and content of the individual worksheets in the input and output files (issue #88).

I think we now need to address the inconsistencies of formatting of these worksheets.  We need to address:
* consistency between worksheets in the input file
* consistency between worksheets that originated with the input file and their corresponding outputs
* consistency of style of what we call things, lowercase_underscores vs. camelCase vs. other
* finalizing any names for maximum clarity to the user

We need to have a discussion about this at a future meeting.  Changing some of these things might trigger variable name changes or other refactoring of the code.  But I think the time has come to settle on some of this.

I'll start making a list in this issue so that we can think about the changes and make some decisions.

**Comment by kdahlquist** [comment]
Tentatively scheduled for discussion at next meeting on 9/16/15 when hopefully @bengfitzpatrick can be here.

**Comment by kdahlquist** [comment]
See note on issue #129 about test-driven development.

**Comment by dondi** [comment]
…with accompanying follow-up comment :)

**Comment by trixr4kdz** [comment]
The code has been modified to adopt the new naming convention as seen in the wiki page: https://github.com/kdahlquist/GRNmap/wiki/New-Naming-Convention except for the part about the `Sigmoid` / `Model` parameter. The code right now is still relying on the user to enter either a 1 or 0 instead of "Sigmoid" or "MM" .

**Comment by trixr4kdz** [comment]
I've changed the optimization parameter "Sigmoid" into "Model" (with accompanying tests) so that the user can enter either "MM" or "Sigmoid" (case insensitive) instead of "0" and "1".

**Comment by trixr4kdz** [comment]
For now, the code would still accept number inputs, but this would cause the program to behave incorrectly since it looks for either "MM" or "Sigmoid". We will have to modify the code so that it throws an error when a number is used instead of those strings.

**Comment by kdahlquist** [comment]
It sounds like you need to have a unit test for this.  I will take a look at it as well.  There will be some other (small changes) that need to be taken care of before closing this issue.  I will post them after I know that all the work has been done on the branch clean-up #164 .

**Comment by kdahlquist** [comment]
Since the branch clean up #164 is done and will be reviewed at the next meeting, I'm moving this issue up to a priority 0 so that we can finish the last remaining tasks.

1. In the documentation on how to format the input sheet for the beta branch, the parameter "Deletion" was not there.  I added it back to the wiki this morning (based on the documentation for the master branch formatting).  We need to complete issue #52, i.e., the code should figure out the deletion strains based on name, not on the order in the gene list.
2. We need to edit the text in cell A1 of the "network" and "network_weights" sheets to read "cols regulators/rows targets".  Right now, having it just say "targets/regulators" is ambiguous.  This will need to be fixed in the code (if need be) and in the documentation.
3. In a version of the input workbook that I got from @GraceJohnson , the optimization_diagnostics worksheet had the word "value" in cells B1, C1, D1, E1, and F1.  Is this necessary?  Does it serve any function?  I am thinking that we should just get rid of it.

**Comment by kdahlquist** [comment]
One more request for the optimization_diagnostics sheet.

Change "Model" to "production_function"; the expected values will remain "Sigmoid" or "MM" for this.

**Comment by kdahlquist** [comment]
Here is a screenshot of what the optimization_parameters worksheet should look like.
![screenshot_optimization_parameters_20150120](https://cloud.githubusercontent.com/assets/6463867/12460468/9b51bc4c-bf68-11e5-9c15-2e9ce97743aa.jpg)

**Comment by trixr4kdz** [comment]
Since MATLAB will not allow us to name our variables with a "-" (i.e., for the L-curve), @juansc and I have decided to name the "L-curve" as "L_curve".

**Comment by kdahlquist** [comment]
That sounds good.

**Comment by trixr4kdz** [comment]
The variable names in the optimization parameters sheet have now been changed to reflect what is in the screenshot posted by @kdahlquist.

**Comment by kdahlquist** [comment]
@kdahlquist checked this and @juansc and @trixr4kdz ran the test suite in our meeting so we are closing this.
