### ISSUE TITLE
GRNmap SURP 2015 Abstract Title

### ISSUE THREAD

**Issue by trixr4kdz** [kdahlquist/GRNmap#120]
I was wondering if this would be a sufficient title to the abstract: 

Functionality Improvements and Test-Driven Development Implementation to GRNmap, a Gene Regulatory Network Modeling Application

The people in charge of McNair want we to submit the abstract by noon today so I apologize for it being sudden.

**Comment by kdahlquist** [comment]
How about this?  I just swapped the two things and removed the word "Implementation".

Test-Driven Development and Functionality Improvements to GRNmap, a Gene Regulatory Network Modeling Application

**Comment by trixr4kdz** [comment]
Ok, I'll submit it to them now and close this issue
