### ISSUE TITLE
Release v1.2 code and executable at end of SURP 2015

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#121]
Let's wrap up SURP 2015 with a release of the code and executable.  I think this should be version 1.2 instead of v1.0.10, we should probably have incremented the middle number one one of the last releases anyway.
* Make sure that the code is in a state that can be merged
* Make sure all of the test files are now compatible with the latest version
 * in particular, the alpha value needs to be changed for the large network sample input sheet that goes into the executable (with the corresponding output changed as well).
* @kdahlquist will make a PDF readme file to be included with the packaged executable
* Update the release notes
* Update the About page
* Update the News page
* Don't forget to manually change the last modified date on the web pages.

**Comment by kdahlquist** [comment]
Assigned the task of creating ReadMe file to @tessaam .

**Comment by tessaam** [comment]
@kdahlquist  I created a README file and Trixie packaged it with the executable.

**Comment by trixr4kdz** [comment]
I have released v1.2 into the world and updated the home page version number, about page release notes, news page, and downloads page for the new release.

@tessaam has tested the executable on the department laptop and it ran successfully.

**Comment by kdahlquist** [comment]
I updated the release notes.  Would you please use these release notes to replace what is currently on the About page?  I included references to issue numbers in the release notes, but do not include them on the About page, only the other text.  Once this has been done and confirmed, this issue can be closed.

**Comment by trixr4kdz** [comment]
Where can I find the updated release notes?

**Comment by kdahlquist** [comment]
Oh, sorry, it is on the releases page here:  https://github.com/kdahlquist/GRNmap/releases.  There is a link for releases across the top of the main code GitHub page.

**Comment by trixr4kdz** [comment]
Done

**Comment by kdahlquist** [comment]
Sorry to be a stickler, but the first bullet points of the release notes needs to have a period.  Thanks.

**Comment by trixr4kdz** [comment]
No worries, it's been updated.

**Comment by kdahlquist** [comment]
confirmed and closing
