### ISSUE TITLE
Toolbox Missing in Computers in UH Lab

### ISSUE THREAD

**Issue by juansc** [kdahlquist/GRNmap#124]
The computers in the Numerical Analysis lab don't all have 2014b installed. The ones we found that has 2014b installed(on the right-hand side of the room, second and third from the right) don't have the optimization toolbox.

**Comment by kdahlquist** [comment]
This has become somewhat moot since the students now have access to S120 and @kdahlquist's research lab.  I'm bumping the priority down.

**Comment by kdahlquist** [comment]
closing this because @bengfitzpatrick is out of town and won't be fixing this anytime soon.
