### ISSUE TITLE
Confirm new normalization script behaves the same for everyone

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#127]
I am going to make new issues for the Microarray Data Analysis Workflow at a much finer granularity so we can track where we are with the individual steps.  This issue is based on the e-mail I already sent out to the group today.

I finally was able to modify the OpenWetWare protocol for the normalization of the microarray data.  I apologize for the delay and I understand that you weren't able to do anything without this information.

The protocol is found on this page:  http://www.openwetware.org/wiki/Dahlquist:Microarray_Data_Analysis_Workflow

If at all possible, please complete the steps including the rounding of the normalized data, but stop before doing any statistics before the GRNmap meeting tomorrow (9/16/15), so that we can make sure that everyone got the same results before moving on to the statistics.  

My e-mail was unclear, I think about which steps I meant.

Also, GitHub only allows me to assign one person.  I think I am going to default group things to @Nwilli31 , since she is the senior member of the data analysis group.  However, this task is also for @GraceJohnson , @tessaam , @khorstmann , and @kjacks48 .

**Comment by kdahlquist** [comment]
I just compared the normalization files that @Nwilli31 and @GraceJohnson sent me via LionShare to the ones I generated myself yesterday with the same scripts.  I got zero differences, even with the unrounded data.  I propose that when @tessaam , @khorstmann , and @kjacks48 do their normalization that they send their files (via Lionshare) to both me and @Nwilli31 and @GraceJohnson.  

If @Nwilli31 and/or @GraceJohnson can then compare the files to their own and verify that there are zero differences, then by the transitive property, they are no different than mine and we can move on.

If we verify that multiple people can run the script on multiple machines and get zero differences, we may not need to do the rounding step after all.

Everyone, keep us all posted by commenting on this issue when your status changes (i.e., you've run the script and sent the data, compared the date, etc.)

I have re-posted @Nwilli31 and @GraceJohnson 's data to my own lionshare and will be giving everyone access via e-mail shortly.

**Comment by kdahlquist** [comment]
I heard from @khorstmann this morning that you guys have been working on this.  Can you each give me an update as to your status?  I'm particularly interested in knowing if the files are matching at this point.  @khorstmann said that hers wasn't, but are the rest of yours matching?  Thanks.

**Comment by GraceJohnson** [comment]
Natalie determined that there was zero difference between our compiled normalized data file (NW_GJ) and the files from Tessa, Monica, and Kayla. As @khorstmann mentioned, her file resulted in differences out to the third decimal place.

**Comment by kdahlquist** [comment]
Did anyone have a chance to check Monica's file?  Also, differences in the third decimal place are too close for comfort.  Did @khorstmann have a chance to redo?

**Comment by khorstmann** [comment]
I went into the lab to work on redoing the R run, but when attempting to move the files into the correct pathways, the computer would crash whenever I would right click, so I was unable to unzip the limma folder into the R directory... Should I just move on to the statistical analysis and ANOVA with Grace and Natalie's data?

**Comment by Nwilli31** [comment]
@kdahlquist, should we retest this step or revisit it, so that we can close this issue? To move forward with confidence, I think that we should figure out why the discrepancy existed - whether it was the software version used or the computer. Both Monica and @khorstmann had varying numbers than the majority of us, which could prove to be an issue in the future when others decide to run the R script with their data.

**Comment by kdahlquist** [comment]
It is OK to close this now.   I have been down this rabbit hole before and I do not want to spend time on this right now.  Because there was a match between my run and that of multiple members of the group, I am satisfied for now.  We can reopen this in the future if we want to do further investigations.  The main thing was that we are all working from a common set of normalized data.
