### ISSUE TITLE
Research Lab computer Cerevisiae does not have Matlab 2014b

### ISSUE THREAD

**Issue by trixr4kdz** [kdahlquist/GRNmap#128]
@juansc and I tried to use the computers in the research lab but only paradoxus had Matlab 2014b.

**Comment by kdahlquist** [comment]
Sorry, I'll take care of that today and post to this issue when it is done.

At 06:46 PM 9/17/2015, you wrote:

**Comment by kdahlquist** [comment]
I installed Matlab and the compiler on that computer.  The next time you come in, try the compiler to make sure it works and I don't need to install anything else.

**Comment by trixr4kdz** [comment]
@juansc and I have confirmed that the Matlab compiler has been installed in the computers in the research lab so I'm closing this issue.
