### ISSUE TITLE
optimization_diagnostic figure must be saved every time.

### ISSUE THREAD

**Issue by juansc** [kdahlquist/GRNmap#132]
This issue came up in #74. The specific post is [here](https://github.com/kdahlquist/GRNmap/issues/74#issuecomment-114299158).We would like to add the following functionality:

The optimization_diagnostic figure will be saved as a .jpg every time GRNmap is run, even if the plots for the strains are not being generated. Currently, GRNmap does not save the optimization_diagnostic figure if makegraphs = 0.

**Comment by juansc** [comment]
To generate the `optimization_diagnostic` we will have to duplicate the code in `general_least_squares_error` that generates the figure and run it in `lse` after the forward simulation is finished.

**Comment by juansc** [comment]
Please review.

**Comment by juansc** [comment]
The createDiagnosticsGraph function that I created is not being called, although the program still behaves correctly. I will have to decide whether delete the function or to refactor the code to make sure it gets called.

**Comment by kdahlquist** [comment]
Let's not work on fixing this just yet.  There are other things that have a higher priority.

**Comment by kdahlquist** [comment]
This is related to #175, so I am elevating it's priority because it is causing a bug with the L-curves.

**Comment by juansc** [comment]
Fixed it in commit  73c21d5483ddec.

**Comment by kdahlquist** [comment]
I have confirmed that this now works with the file: dHAP4_15_gene_network_deletion_added_input_KD_20160126.xlsx with the optimization parameters:

L_curve =1
estimate_params =1
make_graphs =1
fix_P =1
fix_b=1
