### ISSUE TITLE
@trixr4kdz will look into setUp and tearDown methods in the matlab framework so that GRNmap will need to only run once per test file

### ISSUE THREAD

**Issue by trixr4kdz** [kdahlquist/GRNmap#134]
Right now, the current testing framework runs GRNmap every time it does each unit test. This is obviously highly inefficient. @trixr4kdz will look into the setUp and tearDown methods so that for each test file (e.g. when optimization parameters fix_b = 0, fix_p = 0), the program will only run once and then compare each unit test within that run.

**Comment by kdahlquist** [comment]
@trixr4kdz, according to the release notes for v1.4, this has been implemented?  Please confirm whether this issue is now fixed and whether we can close it.

**Comment by trixr4kdz** [comment]
Yes, I was able to modify some of the tests and shave off a little bit of the running time using the setUp and tearDown methods in MATLAB.

**Comment by trixr4kdz** [comment]
I will be closing this issue now
