### ISSUE TITLE
Decide on whether to intercept result before it is written into the output file or create a temp file for comparing outputs in the testing framework

### ISSUE THREAD

**Issue by trixr4kdz** [kdahlquist/GRNmap#136]
Right now, the testing framework is not testing whether the actual values outputted by GRNmap are correct or not since @trixr4kdz still needs to figure out whether to intercept the results or write them out into temporary files so that the original output files are not overwritten. @trixr4kdz will have to decide which method to use.

**Comment by trixr4kdz** [comment]
While working on fixing issue #139, I've decided to write results into temporary folders since it is much easier to do than the alternative.

**Comment by kdahlquist** [comment]
Question: do you delete your temporary files/folders when  you are done with them?  That's a nice feature to have so you are not cluttering your hard drive with a bunch of test results you don't need anymore.

**Comment by trixr4kdz** [comment]
I will need to modify the test framework to delete the files when we're done running the tests

**Comment by trixr4kdz** [comment]
Done modifying the test framework to delete all temp files when done running the tests.
