### ISSUE TITLE
Within-Strain ANOVA for wt, Spar, and each deletion strain

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#137]
Assignments of strains to people:
Kevin Wyllie, Monica Hong: dHAP4, dSWI4
@tessaam: dGLN3, dCIN5, dHAP4
@khorstmann: dZAP1, dGLN3, dSWI4
@kjacks48: dZAP1, dCIN5, wt
@Nwilli31: Spar, wt, dHMO1
@GraceJohnson : Spar, wt, dHMO1

Once the normalization has been confirmed to be the same for all #127 , everyone should do the within-strain normalization procedure on their assigned strains.

Everyone with then check with their partner who did the same strain to make sure that they got the same results.

**Comment by kdahlquist** [comment]
@bengfitzpatrick is working on the corresponding MATLAB script this week so that we can compare results next week.

**Comment by GraceJohnson** [comment]
Confirmed no difference in sanity check numbers for all strains except SWI4 and HAP4. @tessaam will perform Within strain ANOVA for SWI4 and @GraceJohnson will do the same for HAP4.

**Comment by kdahlquist** [comment]
Can you guys annotate this issue with links to your respective electronic lab notebook pages where the work is documented?  Also, something was mentioned at the meeting about differences between calculations in a certain number of decimal places.  Please document that here.

In the next week, @kdahlquist will look at the protocol on the OpenWetWare wiki page and make sure that it correctly deals with missing data.

@khorstmann , confirm when you have corrected the dSWI4 data.

**Comment by GraceJohnson** [comment]
My page can be found here: http://openwetware.org/wiki/Katherine_Grace_Johnson_Electronic_Lab_Notebook#September_23.2C_2015
Differences were found in the Excel calculations for sum of squares, F-stat, and p-values. 
- For wt, differences found in sixth decimal place
- For Spar, differences found in seventh decimal place
- For ZAP1, just the Fstat column had difference in the ninth decimal place

**Comment by khorstmann** [comment]
SWI4 has been corrected and I updated the comparative data onto the Google doc

**Comment by tessaam** [comment]
I did the analysis for SWI4. My numbers did not match @khorstmann's. Can @GraceJohnson, @Nwilli31, or @kjacks48 do it too so we can have a third comparison?

**Comment by GraceJohnson** [comment]
Zero difference was found in the dHAP4 strain when compared to data from @tessaam .

**Comment by bengfitzpatrick** [comment]
Natalie will solve all our problems (meaning check the SWI4)

**Comment by kdahlquist** [comment]
@Nwilli31 , can you contact Kevin Wyllie and get his data and check it?  He did Hap4 and Swi4 on Monday.

**Comment by kdahlquist** [comment]
To sum up, the following people were/are working on the strains as follows:

wt: @Nwilli31 
dCIN5: @kjacks48 
dGLN3: @tessaam and @bklein7 
dHAP4: @GraceJohnson and @maggie-oneil 
dHMO1: no one, we've punted that for now
dZAP1: @khorstmann 
Spar: no one, we've punted that for now

Since @kjacks48 has left and @Nwilli31 is out for the semester, we are going to assign @maggie-oneil to wt and @bklein7 to dCIN5.  They will do the data analysis workflow from normalization through to generating hypothesis networks with YEASTRACT #143 so that they gain first-hand experience with what has led up to the point we are at with the L-curves #172 .

**Comment by kdahlquist** [comment]
@kdahlquist has requested that @bengfitzpatrick look at the MATLAB scripts for the within- and between-strain ANOVAs.

**Comment by kdahlquist** [comment]
@bklein7 has completed his ANOVA and moved on to the YEASTRACT step.  @maggie-oneil needs to finish the sanity check on hers so that they can compare data.

**Comment by kdahlquist** [comment]
Closing this out for Spring 2016.  @kdahlquist will continue validation of workflow during Summer 2016 in preparation for publication.
