### ISSUE TITLE
News Flash! Bulletin of Mathematical Biology article published online!

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#140]
Our article has been published online!  Would you please make updates to the Publications page and News pages as follows:

Publications page
* We should implement collapsible sections on this page in this order:  Papers, Presentations, Posters.  Have it automatically open to the Papers section.
* The text for the Papers section should be as follows:

September 29, 2015
Dahlquist, K.D., Fitzpatrick, B.G., Camacho, E.T., Entzminger, S.D., and Wanner, N.C. (2015) Parameter Estimation for Gene Regulatory Networks from Microarray Data: Cold Shock Response in Saccharomyces cerevisiae. Bulletin of Mathematical Biology. DOI: 10.1007/s11538-015-0092-6, Epub ahead of print. (the name of the journal should be italicized)

View full text in HTML (link that label to this URL: http://link.springer.com/article/10.1007/s11538-015-0092-6/fulltext.html)
Download PDF (1205 KB) link that label to this URL: http://link.springer.com/content/pdf/10.1007%2Fs11538-015-0092-6.pdf
Download electronic supplementary material (65 KB) link that label to this URL: http://link.springer.com/content/esm/art:10.1007/s11538-015-0092-6/file/MediaObjects/11538_2015_92_MOESM1_ESM.zip

Abstract
We investigated the dynamics of a gene regulatory network controlling the cold shock response in budding yeast, Saccharomyces cerevisiae. The medium-scale network, derived from published genome-wide location data, consists of 21 transcription factors that regulate one another through 31 directed edges. The expression levels of the individual transcription factors were modeled using mass balance ordinary differential equations with a sigmoidal production function. Each equation includes a production rate, a degradation rate, weights that denote the magnitude and type of influence of the connected transcription factors (activation or repression), and a threshold of expression. The inverse problem of determining model parameters from observed data is our primary interest. We fit the differential equation model to published microarray data using a penalized nonlinear least squares approach. Model predictions fit the experimental data well, within the 95 % confidence interval. Tests of the model using randomized initial guesses and model-generated data also lend confidence to the fit. The results have revealed activation and repression relationships between the transcription factors. Sensitivity analysis indicates that the model is most sensitive to changes in the production rate parameters, weights, and thresholds of Yap1, Rox1, and Yap6, which form a densely connected core in the network. The modeling results newly suggest that Rap1, Fhl1, Msn4, Rph1, and Hsf1 play an important role in regulating the early response to cold shock in yeast. Our results demonstrate that estimation for a large number of parameters can be successfully performed for nonlinear dynamic gene regulatory networks using sparse, noisy microarray data.

* News page should have a news item for September 29, 2015 that reads:
* Headline: Article describing the sigmoidal model and penalized least squares approach is published online in the Bulletin of Mathematical Biology (italicize the journal name).
* Body text:
Dahlquist, K.D., Fitzpatrick, B.G., Camacho, E.T., Entzminger, S.D., and Wanner, N.C. (2015) Parameter Estimation for Gene Regulatory Networks from Microarray Data: Cold Shock Response in Saccharomyces cerevisiae. Bulletin of Mathematical Biology. DOI: 10.1007/s11538-015-0092-6, Epub ahead of print. (the name of the journal should be italicized)

PubMed Abstract (link that label to this URL: http://www.ncbi.nlm.nih.gov/pubmed/26420504)
View full text in HTML (link that label to this URL: http://link.springer.com/article/10.1007/s11538-015-0092-6/fulltext.html)
Download PDF (1205 KB) link that label to this URL: http://link.springer.com/content/pdf/10.1007%2Fs11538-015-0092-6.pdf
Download electronic supplementary material (65 KB) link that label to this URL: http://link.springer.com/content/esm/art:10.1007/s11538-015-0092-6/file/MediaObjects/11538_2015_92_MOESM1_ESM.zip

**Comment by trixr4kdz** [comment]
Done updating News and Publications pages.

**Comment by kdahlquist** [comment]
Looks good!
