### ISSUE TITLE
Add Kristen and Kayla to the People page

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#141]
I forgot that we should add Kristen and Kayla to the People page on the web site.  Please add them in alphabetical order (by last name) under Current Research Assistants as follows:

Kristen Horstmann (LMU Biomathematics '17) Fall 2015 - present
Kayla Jackson (Spelman College Mathematics '17) Fall 2015 - present

**Comment by trixr4kdz** [comment]
Added Kristen and Kayla

**Comment by kdahlquist** [comment]
confirmed
