### ISSUE TITLE
Feed within-strain ANOVA results into YEASTRACT and generate hypothesis networks

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#143]
This week the data analysis team will do the following:
* For each strain, plug the list of genes that are B-H p < 0.05 into YEASTRACT to determine which transcription factors are enriched among that set of genes.  Be careful to document the date when you retrieved the data and, if you can, the date at which YEASTRACT data was last modified.  Save all of the results into a spreadsheet.
* From these results, each person should generate at least 5 hypothesis networks to run in GRNmap.  The way you chose the genes for the networks should be fully documented as to the choices that were made.
* Generate the input sheets for each of the hypothesis networks.

**Comment by Nwilli31** [comment]
@kdahlquist, I have a question regarding how to pare down the network. I used the p-values given from YEASTRACT; however, @tessaam used the p-values from the ANOVA. Which method is correct in paring down the network?

**Comment by bengfitzpatrick** [comment]
s. paradoxus, SWI4, HMO1, are stricken from the record. We shall no longer speak of them.

**Comment by kdahlquist** [comment]
When I talked about it last week, I meant the YEASTRACT p values.  I had not even thought of using the ANOVA because it is probably the case that not all of the TFs are significant in the ANOVA.  I think for the sake of consistency we should standardize on the YEASTRACT.

**Comment by kdahlquist** [comment]
Everyone has completed their set of networks and have moved on to making input sheets.

**Comment by kdahlquist** [comment]
@bklein7 has begun this step and @maggie-oneil is almost there; she needs to complete her sanity check on the ANOVA first.

**Comment by kdahlquist** [comment]
This has been completed for the Spring 2016 semester.
