### ISSUE TITLE
Slight discrepancy when running the code on different computers (Math dept. vs. Seaver lab)

### ISSUE THREAD

**Issue by trixr4kdz** [kdahlquist/GRNmap#146]
I recently ran the code on both the math department computers and Seaver lab computers and found out that when the code is run in the math department, the calculations are off up to the 4th decimal place. Since the test files originated in Seaver, there were no differences when comparing the test files to what GRNmap actually outputs at the moment. A possible cause would be the system specifications between the machines:

**Seaver  computers**:
Processor: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz 3.40 GHz
RAM: 8.00 GB
System type: 64-bit OS
MATLAB version: 8.4.0.150421
Excel version: 2010

**UHall computers**:
Processor: Intel(R) Core(TM) i7-4790S CPU @ 3.20GHz 3.20 GHz
RAM: 8.00 GB
System type: 64-bit OS
MATLAB version: 8.4.0.150421
Excel version: 2010

**Comment by trixr4kdz** [comment]
Additionally, the files that failed the most tests on the current testing framework (only 19 out of 25 passed) are:

- 4-genes_6-edges_artificial-data_Sigmoidal_estimation_fixb-0_fixP-0_graph.xlsx
- 4-genes_6-edges_artificial-data_Sigmoidal_estimation_fixb-0_fixP-0_no-graph.xlsx

since the tests only account for a difference of up to the 6th decimal place.

**Comment by kdahlquist** [comment]
It seems like we really need an answer to what is our tolerance for differences in output.  I am going to reassign this to @bengfitzpatrick for an answer.

**Comment by bengfitzpatrick** [comment]
After sifting through matlab/stackexchange/etc for a bit, this appears to be a relatively common problem. Hardware/OS differences can apparently have some impact on fmincon. We need to find some reasonable resolution.
(1) What are TolX and TolFun (set in the input sheet optimization_parameters) currently?
(2) We need to do some exploratory runs.  Create a few input sheets (say 30) whose initial guesses are small perturbations of the current test initial conditions.  I'd add normal random numbers with std dev 1e-3 to the weights.  Rerun the optimization and see what the output is.  Ideally fmincon would find the same optimal weights... but we need to check.  Find the standard deviation of that output, and 3x of that number would be a candidate for the testing tolerance.

**Comment by bengfitzpatrick** [comment]
okay, i'm looking at the files you mention.  fix-b-0 and fix-P-0 will almost certainly fail this test. Those examples are in the mix precisely because they are so unstable.

**Comment by trixr4kdz** [comment]
To answer your first question, the TolX = TolFun = 1.00E-05

**Comment by kdahlquist** [comment]
@dondi suggests separating out whether it is Excel that is the issue or whether it is MATLAB by setting up a test where the values are sent directly to MATLAB without reading an input sheet.

**Comment by bengfitzpatrick** [comment]
run the fix_b = fix_P = 1, 4 gene 6 weight test with varying initial guess weights on Seaver and Math computers to see the variability in optimized weights.

**Comment by trixr4kdz** [comment]
I made the perturbations and placed the files in the test_files folder under "perturbation_tests". I also run the code on both Seaver and Math Dept. computers, but I have yet to look through the results.

**Comment by trixr4kdz** [comment]
The perturbation tests have been made in the beta branch under the "test_files/perturbation_tests" folder. I have created 4 other folders within it to separate runs between the math dept. and Seaver lab and between pre- and post-merging the L-curve branch (i.e., there should be 4 different folders each with 30 different initial weight values + their corresponding outputs called "math_post_L-curve", "math_pre_L-curve", "seaver_post_L-curve", and "seaver_pre_L-curve"). To make it easier to navigate to them, here is the link: https://github.com/kdahlquist/GRNmap/tree/beta/test_files/perturbation_tests

**Comment by kdahlquist** [comment]
Superseded by #323, so closing this one.
