### ISSUE TITLE
Install Git in Seaver 120

### ISSUE THREAD

**Issue by juansc** [kdahlquist/GRNmap#152]
We need to install [git for windows](https://git-scm.com/download/win) on all computers in Seaver 120.

**Comment by kdahlquist** [comment]
I just put in the request to IT.  (Sorry for the delay).  I'll comment again when it has been done.

**Comment by trixr4kdz** [comment]
It appears that Git has been installed in the computers

**Comment by kdahlquist** [comment]
Yes, I'm sorry, I forgot to comment when it happened.  Closing now.
