### ISSUE TITLE
Reformat all excel test sheets so that the timepoints are parsed correctly

### ISSUE THREAD

**Issue by trixr4kdz** [kdahlquist/GRNmap#155]
We need to reformat all the excel sheets in order to avoid the error we were having in Issue #154. We will also create more unit tests to verify that the excel sheets are being formatted correctly.

**Comment by kdahlquist** [comment]
I closed #154 because it was now redundant with this one.  Refer back to that issue for details.

**Comment by kdahlquist** [comment]
Here is a screenshot of what the new optimization_parameters worksheet should look like.
![screenshot_optimization_parameters_20150120](https://cloud.githubusercontent.com/assets/6463867/12460400/5a2f6c82-bf68-11e5-951d-a40a7261639d.jpg)

**Comment by kdahlquist** [comment]
There are two things that need to be done:
1. Write a test that looks at the issue where there was 1.2000000001 showing up as an expression timepoint label instead of 1.2.
2. Except for the one you keep to run this specific test, fix all of the Excel spreadsheets so that this problem is gone.

**Comment by trixr4kdz** [comment]
2 tests have been created to check if the row of timepoints are formatted correctly; 1 is for determining which cells are incorrect, and another one is to count how many rows are not read due to incorrect formatting. @juansc has formatted the perturbation tests so that this problem is gone and these 2 tests pass. However, except for 1 sheet (which I used to check if the tests pass), the parameters "production_function" is still called "Model" and "L-curve" is still missing.

**Comment by kdahlquist** [comment]
I think we discussed this at the last meeting:  we need to get *all* of the test files updated to the latest naming conventions.  We cannot move forward without this being done first.

**Comment by trixr4kdz** [comment]
The GRNstruct that we were using for each test was persisting so we had to change the code so that we clear the GRNstruct in between tests.

**Comment by kdahlquist** [comment]
the production_function and L_curve parameters have been added to all the test input files and "Deletion" was gotten rid of and extraneous "value" were removed.

Closing now.
