### ISSUE TITLE
GRNmap must be able to deal with missing values

### ISSUE THREAD

**Issue by juansc** [kdahlquist/GRNmap#158]
We must figure out a way to deal with missing data points, in particular the case where we are missing some log2fold gene expressions for some time replicates. In the Excel sheets these values look empty; when MATLAB reads them in it treats them as NaN's. These cannot be used in computations.

**Comment by kdahlquist** [comment]
The missing values are the result of the new normalization regime for the microarray data.

**Comment by kdahlquist** [comment]
In the meantime, another thing we can do is take an average of the replicate data in Excel and just use the one average value as input instead of the replicates.

**Comment by trixr4kdz** [comment]
This might require a bit of clarification and consultation with @dondi on whether to go ahead and do the averages of the replicate data or come up with a better way of handling the NaNs.

**Comment by kdahlquist** [comment]
To clarify, taking the averages and substituting them for missing values is only a workaround and should not be our real solution.  The program needs to appropriately handle the missing values by adjusting for them in the computation.  If we just took the averages, it would mess up the standard deviaton calculations.

**Comment by kdahlquist** [comment]
Function in MATLAB "isNaN", @bengfitzpatrick thinks it is the case that when a blank data field from Excel comes into MATLAB, it will put a NaN there.

Find will help you find the stuff that fails the NaN test and reduce the array.

You probably want to do this when you read in the data, to do some preliminary processing.

**Comment by trixr4kdz** [comment]
One solution to this problem is to convert the expression data for each timepoint into separate arrays. For example, instead of storing the raw data, we would have steps to process it into an n x m matrix (where n = number of genes, m = number of distinct replicate timepoints) and each element in the matrix would be arrays:

|ID         |     15    |    30    |    60   |
|---        |---        |---        |---       |
|GeneA  |  [1,2,3] | [1,2,3] | [1,2,3] |  
|GeneB  |    [1,2]  | [1,2,3] | [5,6,7] | 
|GeneC  |  [1,2,3] | [2,3,4] |   [1,3]  |

**Comment by kdahlquist** [comment]
We discussed this in the meeting and @trixr4kdz took a picture which she will post here.

Use a cell array.

each array for the gene and timepoint will have one row of data and a second row with the index of which replicate it was.

**Comment by trixr4kdz** [comment]
I forgot to post this diagram about our plan to restructure the way we are storing our data. In essence, we will have a 2 by n matrix (where n is the number of replicate timepoints) for each of the genes in the expression data. The reason for having 2 rows is so that we can keep track of the indices of the existing values.
![img_6879](https://cloud.githubusercontent.com/assets/8975300/19096880/fd2ebb10-8a54-11e6-81da-8b556ba05989.JPG)

**Comment by kdahlquist** [comment]
catalog all places in the code where missing data arrays need work.  Should be a list of code lines with links like the initialization and global issue work.  Starters should be uses of log2FC and .microData arrays.

**Comment by cazinge** [comment]
It’s fairly obvious to say that the conversion to this new data structure will require a fairly sizable portion of our codebase to adapt, but there are three specific areas in which we should be working on. I’ve categorized each of the locations where either the log2FC and .microData arrays or the code surrounding it will need to be changed to accommodate the new data structure.

-Testing
	The change to the nested matrix based data structure will invalidate our current testing fixture in a number of places due to how we’re initializing our arrays as well as how expectations of the arrays are handled.

* log2FC

  * [ConstantGRNStructs.m](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ConstantGRNStructs.m)
    * Lines: [19](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ConstantGRNStructs.m#L19), [20](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ConstantGRNStructs.m#L20), [63](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ConstantGRNStructs.m#L63), [192](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ConstantGRNStructs.m#L192), [323](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ConstantGRNStructs.m#L323), [457](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ConstantGRNStructs.m#L457), [588](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ConstantGRNStructs.m#L588), [730](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ConstantGRNStructs.m#L730), [883](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ConstantGRNStructs.m#L883), [1032](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ConstantGRNStructs.m#L1032), [1177](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ConstantGRNStructs.m#L1177), [1320](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ConstantGRNStructs.m#L1320), [1464](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ConstantGRNStructs.m#L1464), [1604](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ConstantGRNStructs.m#L1604), [1740](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ConstantGRNStructs.m#L1740), [1872](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ConstantGRNStructs.m#L1872), [1998](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ConstantGRNStructs.m#L1998), [2131](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ConstantGRNStructs.m#L2131)

  * [outputTest.m](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/outputTest.m)
    * Lines: [35](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/outputTest.m#L35), [44](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/outputTest.m#L44)

* .microData

  * [deletedStrainTest.m](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/deletedStrainTest.m)
    * Lines: [18](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/deletedStrainTest.m#L18), [19](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/deletedStrainTest.m#L19), [26](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/deletedStrainTest.m#L26), [27](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/deletedStrainTest.m#L27), [34](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/deletedStrainTest.m#L34), [35](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/deletedStrainTest.m#L35), [42](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/deletedStrainTest.m#L42), [43](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/deletedStrainTest.m#L43), [50](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/deletedStrainTest.m#L50), [51](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/deletedStrainTest.m#L51), [58](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/deletedStrainTest.m#L58), [59](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/deletedStrainTest.m#L59), [66](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/deletedStrainTest.m#L66), [67](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/deletedStrainTest.m#L67), [74](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/deletedStrainTest.m#L74), [75](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/deletedStrainTest.m#L75), [82](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/deletedStrainTest.m#L82), [83](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/deletedStrainTest.m#L83), [89](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/deletedStrainTest.m#L89), [90](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/deletedStrainTest.m#L90), [96](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/deletedStrainTest.m#L96), [97](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/deletedStrainTest.m#L97)

  * [initializeArraysTest.m](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/initializeArraysTest.m)
    * Lines: [19](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/initializeArraysTest.m#L19), [20](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/initializeArraysTest.m#L20), [25](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/initializeArraysTest.m#L25), [26](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/initializeArraysTest.m#L26)

  * [MSETest.m](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/MSETest.m)
    * Lines: [30](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/MSETest.m#L30), [34](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/MSETest.m#L34)

  * [simulationTimepointsTest.m](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/simulationTimepointsTest.m)
    * Lines: [19](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/simulationTimepointsTest.m#L19), [21](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/simulationTimepointsTest.m#L21), [22](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/simulationTimepointsTest.m#L22), [31](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/simulationTimepointsTest.m#L31), [33](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/simulationTimepointsTest.m#L33), [34](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/simulationTimepointsTest.m#L34)

  * [ForwardSimulationTest.m](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ForwardSimulationTest.m)
    * Lines: [36](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ForwardSimulationTest.m#L36), [37](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ForwardSimulationTest.m#L37)

  * [outputTest.m](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ForwardSimulationTest.m)
    * Lines: [105](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ForwardSimulationTest.m#L105), [108](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ForwardSimulationTest.m#L108), [121](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ForwardSimulationTest.m#L121), [160](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ForwardSimulationTest.m#L160), [161](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ForwardSimulationTest.m#L161), [168](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ForwardSimulationTest.m#L168), [169](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/ForwardSimulationTest.m#L169)

  * [readInputSheetTest.m](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/readInputSheetTest.m)
    * Lines: [55](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/readInputSheetTest.m#L55), [56](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/readInputSheetTest.m#L56), [58](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/test_files/matlab_codes/tests/readInputSheetTest.m#L58)

-Writing data to array
	The change will also require us to revisit how we deal with adding data to log2FC and .microData as most everywhere we're either populating these arrays with number values instead of matrices, or we're reading data strictly from cells instead of ordering it into a matrix before inserting it into the array.

* log2FC

  * [readInputSheet.m](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m)
    * Lines: [12](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L12), [61](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L61), [62](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L62), [73](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L73), [74](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L74), [150](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L150), [151](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L151), [152](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L152), [161](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L161), [162](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L162), [170](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L170), [171](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L171), [173](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L173)

* .microData

  * [initializeArrays.m](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/initializeArrays.m)
    * Line: [18](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/initializeArrays.m#L18)

  * [readInputSheet.m](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m)
    * Lines: [59](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L59), [60](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L60), [61](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L61), [62](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L62), [75](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L75), [128](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L128), [145](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L145), [146](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L146), [147](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L147), [152](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L152), [153](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L153), [155](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L155), [156](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L156), [159](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L159), [160](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L160), [164](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L164), [166](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L166), [168](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L168), [169](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/readInputSheet.m#L169)

-Reading data from array
    Finally, we'll need to look into how we programmatically read from log2FC and .microData throughout various areas in the code. All this really requires is changing the code from working with each individual cell as a number to working with it as a matrix.

* log2FC

  * [createDiagnosticsGraph.m](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/createDiagnosticsGraph.m)
    * Lines: [4](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/createDiagnosticsGraph.m#L4), [28](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/createDiagnosticsGraph.m#L28)

  * [general_least_squares_error.m](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/general_least_squares_error.m)
    * Lines: [12](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/general_least_squares_error.m#L12), [56](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/general_least_squares_error.m#L56), [57](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/general_least_squares_error.m#L57), [81](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/general_least_squares_error.m#L81), [82](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/general_least_squares_error.m#L82), [95](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/general_least_squares_error.m#L95)

  * [graphs.m](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/graphs.m)
    * Lines: [9](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/graphs.m#L9), [48](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/graphs.m#L48), [54](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/graphs.m#L54), [55](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/graphs.m#L55), [58](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/graphs.m#L58), [59](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/graphs.m#L59)

  * [lse.m](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/lse.m)
    * Lines: [9](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/lse.m#L9), [97](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/lse.m#L97)

  * [output.m](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/output.m)
    * Lines: [12](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/output.m#L12), [53](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/output.m#L53), [56](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/output.m#L56), [81](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/output.m#L81)

  * [runForwardSimulation.m](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/runForwardSimulation.m)
    * Lines: [2](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/runForwardSimulation.m#L2), [16](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/runForwardSimulation.m#L16), [17](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/runForwardSimulation.m#L17), [18](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/runForwardSimulation.m#L18), [19](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/runForwardSimulation.m#L19)

* .microData

  * [output.m](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/output.m)
    * Line: [57](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/output.m#L57)

  * [runForwardSimulation.m](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/runForwardSimulation.m)
    * Lines: [5](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/runForwardSimulation.m#L5), [6](https://github.com/kdahlquist/GRNmap/blob/a43428243f2af4127078d5c541bc9a7c324b4842/matlab/runForwardSimulation.m#L6)

Commit used for this report: [a434282](https://github.com/kdahlquist/GRNmap/commit/a43428243f2af4127078d5c541bc9a7c324b4842/)

**Comment by kdahlquist** [comment]
@cazinge will start by setting up a function called `compressMissingData` that is focused on taking a `.rawExpressionData` array (currently called `.microData` in GRNStruct) and producing a new `.expressionData` structure. This function is cleanly isolated and can therefore be tested without involving the entire flow of the application (i.e., no need to read an xlsx file, etc.). Once validated, `compressMissingData` can then be appended to the end of the `readInputSheet` process. The name of the function itself may be subject to change.

**Comment by dondi** [comment]
@cazinge has started some work but had initial questions about "isolating" the code and these were cleared up at the meeting. He will push his work-in-progress for the next meeting so that the team can look at it on the big screen.

**Comment by cazinge** [comment]
After doing some work on the change to this new data structure in commit [daa7909](https://github.com/cazinge/GRNmap/commit/daa790981a37e51e4cebba3e2811cb8fbc7acf4d), I've realized that our initial way of handling this data structure, nesting vectors within vectors is not supported by matlab's run time. For example [[1,2],[3,4]] is an equivalent matrix to [1, 2, 3, 4] and [[1; 2], [3; 4]] is functionally equivalent to [1, 3; 2, 4]. I've done some looking into alternatives and it seems like there's 3 distinct options that we can go with. We can either turn the entire data structure into a struct where the each of the fields is a different gene at a specific time point, create a vector of structs containing each of the nested vectors or turn the data into a 4-dimensional vector. Each of these options are valid and seem like they will not have any issue being implemented, but come with their own issues with data handling. 

Side Note: due to our reliance on simulation_timepoints in the GRNstruct Data Structure, we'd need to pass in both simulation_timepoints and GRNstruct.microData(soon to be rawExpressionData) into the function. We should discuss once more whether or not we will be isolating this function from the entirety of GRNstruct.

**Comment by kdahlquist** [comment]
Need to use a cell array.

A = {[1,2],[3,4]}

A{1} = [1,2]

Note that simulation_timepoints is not the same thing as expression_timepoints.  expression_timepoints are the actual data (in our usual example 15, 30, 60) simulation_timepoints is when the forward simulation is evaluated and can be any time increments (we currently use 5. 10. 15, 30, 35, etc.).

length(GRNStruct.microData)

MATLAB starts with 1

**Comment by cazinge** [comment]
I separated the tests into 4 areas of concern; Control: Making sure that no data is lost and no extraneous data is introduced into the data structure; MissingData: Testing the Data Structure under the circumstance where it's missing some data; InconsistentData: Testing the data structure under the circumstance where the Timepoints aren't uniform, (some have 4 sets of time points, others 2);  and MissingTooMuchData: Testing the Data Structure under the circumstance where it's missing an entire timepoint's worth of data for a given expression. My understanding of MissingTooMuchData is that we want it to throw an error when any expression is missing a full timepoint's worth of data, but throwing that error might be outside of compressMissingData's scope. I'm unsure of whether I've missed any extraneous cases, but after compressMissingData is finished, I'll throw in a couple of tests that cover all of these edge cases when in combination with each other.

**Comment by kdahlquist** [comment]
We looked at the work on @cazinge's fork at https://github.com/cazinge/GRNmap/commit/1ab075c80789546906738e4336c9044310f8a70a and have the following observations/feedback:

- The missing data case should include additional workbooks where more than one replicate is missing data for a particular gene for a particular timepoint. This expands the coverage for the compressMissingData function
- @bengfitzpatrick observes that the current test sheets are showing the exact same value for each gene at each timepoint across replicates. @bengfitzpatrick will work on producing a test sheet that introduces noise to the data, again to expand coverage of the tests.
- An additional scenario to explicitly test/handle is the situation where a complete extremity column (leftmost column, rightmost column) is blank---this may confuse Matlab's read XLSX function and will need mapping to the header row to ensure that the array is sized correctly.

**Comment by kdahlquist** [comment]
An additional observation about @cazinge's test files is that it isn't actually necessary to read a "genuine" GRNmap input workbook to test the compression. Isolated arrays which call the compression function directly can keep the values simpler and more readable and make the test more focused on precisely the array compression that we are after. It will also be easier to construct multiple edge cases/variations on what's missing in the array.

**Comment by kdahlquist** [comment]
With the comment above, `compressMissingData(GRNstruct)` would thus be just an intermediate function that extracts the arrays from a GRNstruct. You can have a more focused function like, say, `removeNaNs(arrays)` which operates _solely_ on multidimensional arrays regardless of their origin. _This_ function can then be testable in a simpler way without dependencies on the numbers having to be solutions to differential equations or having to come from a workbook file.

**Comment by kdahlquist** [comment]
@cazinge says that they left a note in the code on what tasks are remaining. Will finish working on the convertToNestedStructure tests and code.

**Comment by jtorre39** [comment]
So far we've made progress on converting the data to our new nestedDataStructure but work still needs to be done to finalize it as it is not passing all of our tests as of now.

**Comment by cazinge** [comment]
Make a couple of test cases where there is no missing data and see if the indices are still off.

**Comment by trixr4kdz** [comment]
We are in the process of adding tests for the error handling for when we are checking for missing values. Here is a helpful link that I found that we can use for the next session: 
https://www.mathworks.com/help/matlab/ref/matlab.unittest.qualifications.verifiable.verifyerror.html

**Comment by dondi** [comment]
Inspection of `beta` branch shows new test name but appears to be missing a push as of the meeting. @cazinge, @trixr4kdz, and/or @jtorre39 will make sure the code is updated.

**Comment by trixr4kdz** [comment]
As described in #302, this issue can now be closed since separate issues have been created for the other changes (i.e., #310 and #311).
