### ISSUE TITLE
Beta Cannot Read "degradation_rates" sheet. File Not Found

### ISSUE THREAD

**Issue by Nwilli31** [kdahlquist/GRNmap#160]
When I ran my modified input sheet after deleting all the null values, I received this error:

GRNmodel
The system cannot find the file specified. 
Error using xlsread (line 247)
Worksheet 'degradation_rates' not found.

Error in readInputSheet (line 85)
[GRNstruct.degRates,GRNstruct.labels.TX0]                = xlsread(input_file,'degradation_rates');

Error in GRNmodel (line 88)
        GRNstruct = readInputSheet(GRNstruct);

Attached is the Input file that I ran: 
[15_node_Input_sheet_added_2015_11_08_21deletions.xlsx](https://github.com/kdahlquist/GRNmap/files/50352/15_node_Input_sheet_added_2015_11_08_21deletions.xlsx)

**Comment by kdahlquist** [comment]
I am going to close this issue because it is probably due to using the wrong format of the input sheet for the wrong code (beta vs. master).
