### ISSUE TITLE
MATLAB error when running input sheet on master branch

### ISSUE THREAD

**Issue by tessaam** [kdahlquist/GRNmap#161]
When trying to run the input sheets on the master branch of the code, @kjacks48, @khorstmann, and I all got the same MATLAB error:
Index exceeds matrix dimensions.

Error in readInputSheet (line 166)
    log2FC(i).deletion  = Deletion(i);

Error in GRNmodel (line 30)
GRNstruct = readInputSheet(GRNstruct);

We all formatted our input sheets similarly. I uploaded mine onto openwetware: 
http://www.openwetware.org/wiki/Tessa_A._Morris_Electronic_Lab_Notebook_2015-2016#7_December_2015

**Comment by kjacks48** [comment]
I also got this error when running my input sheet:

Error in readInputSheet (line 116)
    GRNstruct.labels.TX11{ii,1} = GRNstruct.labels.TX1{ii,2};

**Comment by kdahlquist** [comment]
@tessaam I opened your input sheet and the production_rates sheet and degradation_rates sheet were empty.  This would definitely crash the program.  You need to get the degradation rates from the Belle spreadsheet (we used it in class last semester).  There is a value to use in the class instructions if there is no value for your particular gene.  Also, the production rates are then 2X the degradation rates.  Fix this and see if it works.

Also, I was thinking that maybe instead of using the master branch code, you could download the lasted released code from the Downloads web site.

@kjacks48, I don't have your input sheet, so I'm not sure what that problem is.

**Comment by tessaam** [comment]
@kdahlquist I reran it with the production_rates sheet and the degradation_rates sheet filled out like we did it in class, and I got the same errors. 
Do you want me to try running it on beta to see if I get the same errors?

**Comment by Nwilli31** [comment]
When running the most recent code release from the website {http://kdahlquist.github.io/GRNmap/downloads.html}, I got the following error:

Index exceeds matrix dimensions.

Error in readInputSheet (line 116)
    GRNstruct.labels.TX11{ii,1} = GRNstruct.labels.TX1{ii,2};

Error in GRNmodel (line 30)
GRNstruct = readInputSheet(GRNstruct);

Attached is the file that I ran. 
[15_node_Input_sheet_added_2015_11_08_21deletions_m.xlsx](https://github.com/kdahlquist/GRNmap/files/57381/15_node_Input_sheet_added_2015_11_08_21deletions_m.xlsx)

**Comment by GraceJohnson** [comment]
I formatted the input sheet according to the instructions on the Wiki and the program is currently running (i.e. no errors). One run is estimating b and P, and another fixes these two parameters (I realized this will allow the run to take less time. 
My input sheet is here. To account for the NaN's, I calculated averages for the time points and put these values into the empty cells. While this isn't Kosher per se, at least we can see a full sized network.

[master_avgadded_dHAP4_34_gene_network_deletion_added_input_GJ.xlsx](https://github.com/kdahlquist/GRNmap/files/57464/master_avgadded_dHAP4_34_gene_network_deletion_added_input_GJ.xlsx)

**Comment by khorstmann** [comment]
Reran and got completely different errors of: 
"Error using barrier (line 22)
Objective function is undefined at initial point. Fmincon cannot continue.

Error in fmincon (line 799)
    [X,FVAL,EXITFLAG,OUTPUT,LAMBDA,GRAD,HESSIAN] =
    barrier(funfcn,X,A,B,Aeq,Beq,l,u,confcn,options.HessFcn, ...

Error in lse (line 85)
        estimated_guesses =
        fmincon(@general_least_squares_error,estimated_guesses,[],[],[],[],lb,ub,[],options);

Error in GRNmodel (line 32)
GRNstruct = lse(GRNstruct);" 

First error is at line 22, which is a comment on the code. 
Cross checked all my sheets against Grace's from above and Tessa's... Still received error. Sheet is attached. I'll continue working on it after break. 
[redo_12_9_15_DNA_binding_dZAP1_35_Genes.xlsx](https://github.com/kdahlquist/GRNmap/files/57528/redo_12_9_15_DNA_binding_dZAP1_35_Genes.xlsx)

**Comment by kdahlquist** [comment]
I am going to close this since it is probably an error generated by formatting the input sheet for the wrong code (beta vs. master).
