### ISSUE TITLE
Bug in graph.m caused by having too many strains

### ISSUE THREAD

**Issue by juansc** [kdahlquist/GRNmap#163]
We have code in the `graph.m` which prevents us from having more than 5 strains. We can fix this in two ways:
* Expand the number of colors
* Maximize the number of strains, and output and error if the user includes too many strains.

**Comment by kdahlquist** [comment]
@juansc, can we get a quick and dirty fix to this where you hard code a sixth color so that we can run all six strains with make_graphs = 1?  

Fix it on the beta branch and comment on this issue when it is done, so we know.

We'll need to figure out a longer-term fix for this, but it would be great if the data analysis team could run the model with all six strains and not have it crash at the moment.

**Comment by juansc** [comment]
![image for new graphs](https://cloud.githubusercontent.com/assets/6529816/12939554/94f986fa-cf75-11e5-8afc-2f1fb7c4a232.PNG)
Here is an image with the new colors.

**Comment by juansc** [comment]
The new code will support up to 12 strains, with the following color scheme
![color ed people](https://cloud.githubusercontent.com/assets/6529816/12939576/d5f03fd2-cf75-11e5-8741-e6fa4e715e45.PNG)

**Comment by dondi** [comment]
Color scheme was from https://bl.ocks.org/mbostock/5577023.  @kdahlquist will revise order of list slightly.

**Comment by kdahlquist** [comment]
Here is my request for the order of the colors, adding black and grey and getting rid of yellow from the above color scale.

1. black
2. dark blue
3. dark red
4. dark green
5. dark orange
6. dark purple
7. brown
8. grey
9. light blue
10. light red (pink)
11. light green
12. light orange
13. light purple

**Comment by juansc** [comment]
I have created the requested color scheme.

**Comment by juansc** [comment]
I will upload a graph with colors soon.

**Comment by juansc** [comment]
![new_colored_opeople](https://cloud.githubusercontent.com/assets/6529816/13030979/ea461d0a-d270-11e5-87b5-1436d3440e2f.PNG)
Here it is!!!

**Comment by kdahlquist** [comment]
I have confirmed that this now works with the file: dHAP4_15_gene_network_deletion_added_input_KD_20160126.xlsx with the optimization parameters:

L_curve =1
estimate_params =1
make_graphs =1
fix_P =1
fix_b=1
