### ISSUE TITLE
Branch clean-up

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#164]
1. @juansc and @trixr4kdz , in the comments to this issue:  state what is in each of these branches that is different than master:

    - L-curve

    - consolidation_branch

    - beta

    - output-directory

    - super-struct

2. Once this has been stated, on a branch by branch basis, and sequentially, we will consolidate the changes in that branch into beta.  We will do this one branch at a time, so if we are working on "L-curve", then we do not start any new branches or work on any of the other branches.  To validate the consolidation of each branch, we will supply unit tests.  We will start with the branch with the smallest number of changes and work our way up.

3. During the weekly meetings, we will run the tests live.

4. Once the tests have been shown to pass in the meeting, we will move onto the next branch.

**Comment by juansc** [comment]
We reviewed L-Curve and we've concluded that we've merged L-Curve into beta already so we will delete the L-Curve branch.

**Comment by juansc** [comment]
We have decided to delete the super-struct branch since it was 68 commits behind master and not much work had been done on that branch.

**Comment by juansc** [comment]
Beta has the following changes that differ from master:

* The beta branch has changes from the L-Curve branch. 
* Beta has code that generates the diagnostic graph that addresses #132.
* We've renamed several variables from the optimization parameters sheet, as well as some other variables to make the code more readable.
* We have code that allows us to use the strings 'MM' and 'Sigmoid' for the model parameter in the optimization parameter sheet.
* The SSE calculations are different; 
* The LSE calculations are now included in the diagnostic. 
* The beta branch only has one column for the gene name, so the code has been changed to reflect this.
* General cleanup like removing evals.
* We have code to add the reg_out and the counter information to address #145.
* We save the optimization diagnostic whenever we estimate the parameters.
* We have code that figures out which gene row is deleted based on the name #52.
* We have added more tests.

We still need to verify that these changes work before merging into master.

**Comment by juansc** [comment]
The consolidation-branch contained a text file that documented some errors when running the tests. The text file was added to the beta branch and we deleted the consolidation-branch.

**Comment by kdahlquist** [comment]
What about output-directory?

**Comment by trixr4kdz** [comment]
We have discovered that output-directory is very similar to beta. It does have some initial work to allow users to choose an output directory so we might want to leave it for now.

**Comment by kdahlquist** [comment]
Very similar, but not identical?  Then you should merge beta into output-directory so that it is up-to-date with the changes in beta and we have the clean slate we were looking for to start the semester.

**Comment by trixr4kdz** [comment]
Beta has been merged into output-directory.

**Comment by kdahlquist** [comment]
I'm marking this as review requested since it seems like the work has been completed.  We will review at our next meeting.

**Comment by kdahlquist** [comment]
A previous comment by @juansc said that you were going to delete the super-struct branch, but I'm still seeing it.  If you are going to delete it, please do so before Wednesday's meeting so it's all cleaned up by then.  Thanks.

**Comment by juansc** [comment]
The remaining branches that we have are master, beta, gh-pages, and output-directory. beta and output-directory are up to date with each other.

**Comment by juansc** [comment]
We will have to periodically(once a week to once every two weeks) merge beta into output-directory and run the tests to make sure the output-directory branch stays fresh.
