### ISSUE TITLE
Workflow for week of 1/27 to 2/3

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#169]
* @juansc and @trixr4kdz will work on issues #154, #155, and #168.
* Once these are done, merge beta branch in to output-directory branch
* Merge beta branch into master branch and do a release and create an executable so that the data analysis team can move their work to the master branch.
* @bengfitzpatrick is going to work on #165 and give @kdahquist code by Friday, which she will push to the repository.

**Comment by trixr4kdz** [comment]
Just to verify, we are going to merge into master during the meeting on 2/3, right?

**Comment by kdahlquist** [comment]
closing this because we closed the relevant issues.
