### ISSUE TITLE
TRACE documentation for GRNmap

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#170]
I have set up a wiki page for the Data Analysis team to begin to create the TRACE documentation of GRNmap here:

http://www.openwetware.org/wiki/Dahlquist:TRACE_Documentation

There are 8 sections, some of which we don't have enough information for and some of which we do.

By the meeting tomorrow (Friday, 1/29/16) please read the main article about TRACE (http://www.sciencedirect.com/science/article/pii/S0304380014000611) and we will talk about who will work on which sections of the documentation.

**Comment by kdahlquist** [comment]
This is a task for @kdahlquist for the summer.

**Comment by kdahlquist** [comment]
I am reassigning this task to the GRNmap data analysis team.  The documentation page is here:

http://www.openwetware.org/wiki/Dahlquist:TRACE_Documentation

As I mentioned to @khorstmann and @maggie-oneil on Tuesday, I want the data analysis team to split up the task of filling in the documentation, which @kdahlquist will then review.  We'll talk about this more at the meeting on Monday.

**Comment by Nwilli31** [comment]
@bklein7 and I, @nwilli31, have decided that we shall take the last four subjects of the TRACE documentation for GRNmap.

**Comment by kdahlquist** [comment]
This means that @khorstmann and @maggie-oneil will take the first four.  Please log progress on this issue.

**Comment by Nwilli31** [comment]
Because I am working on TRACE documentation Number 5 (Implementation verification), I will enlist the help of @cazinge whose task it is to document everything (bugs, changes in code, etc.) on the developer side. I will also introduce him to TRACE documentation to consider using it to keep track of GRNmap coding.

**Comment by kdahlquist** [comment]
Backlogging this one.
