### ISSUE TITLE
LMU Symposium Abstracts

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#171]
The LMU Undergraduate Research Symposium abstracts are due 2/12 by 5:00PM.  I would like the groups to create the first draft of your abstract on the wiki by Friday 2/5, so they can be edited and submitted by the deadline.
* Name the wiki pages with the last names of the authors and LMU Symposium 2016
* You can start with your previous abstract and update them with the latest work and to keep within the word count.
* Tessa will give a talk (with Kristen and Brandon as co-authors)
* Kristen and Brandon will give a poster with Tessa as co-authors
* Grace and Maggie will give a poster
* Juan and Trixie will give a talk

**Comment by GraceJohnson** [comment]
Draft for @maggie-oneil  and I can be found here: http://openwetware.org/wiki/Johnson_and_O%27Neil_LMU_Symposium_2016

**Comment by tessaam** [comment]
I am supposed to have a unique abstract from @khorstmann and @bklein7, right?
Here's the draft so far: 
http://openwetware.org/wiki/Morris_LMU_Symposium_Spring_2016

**Comment by khorstmann** [comment]
Draft for me, @bklein7, and @tessaam http://openwetware.org/wiki/Horstmann_Klein_Morris_Abstract

**Comment by trixr4kdz** [comment]
The draft for my and @juansc's abstract can be found [here] (https://github.com/kdahlquist/GRNmap/wiki/Roque-and-Carrillo-LMU-Symposium-2016-Abstract).

**Comment by kdahlquist** [comment]
@juansc and @trixr4kdz abstract is ready for submission, please comment when it has been submitted.

**Comment by khorstmann** [comment]
http://openwetware.org/wiki/Horstmann_Klein_Morris_Abstract Edited down to 232 words, added a title, change it around when you can/as you see fit and I will submit tomorrow

**Comment by GraceJohnson** [comment]
I just submitted the abstract for @maggie-oneil and me. The word count for the abstract was 249. Abstract can be found here: http://openwetware.org/wiki/Johnson_and_O%27Neil_LMU_Symposium_2016

**Comment by trixr4kdz** [comment]
The abstract for @juansc and me has been submitted.

**Comment by kdahlquist** [comment]
@khorstmann , I have revised your title and abstract and it is at 248 words.  I just want to verify that the number you quote for significant genes is from the Benjamini and Hochberg corrected p value and not the regular p value.  If it's not, please sub in the B-H numbers.  Otherwise, it's good to go.

**Comment by kdahlquist** [comment]
@tessaam, I have revised your abstract to get it within the word count limit of 250.  As you can see, there are places where you need to plug in information:
* the number of B-H significant genes and the %
* the number of networks in your families (both together)
* the number of genes/edges for the largest and smallest networks in your family.

With these additions, it is ready to submit.  The deadline is 5:00PM today.

**Comment by tessaam** [comment]
@kdahlquist I made the changes and just submitted!

**Comment by khorstmann** [comment]
Made changes and thanks for checking-- the significant genes were not BH. Made that change and submitted.

**Comment by kdahlquist** [comment]
all abstracts submitted.
