### ISSUE TITLE
Extra Values in Optimized Threshold Sheet

### ISSUE THREAD

**Issue by juansc** [kdahlquist/GRNmap#173]
When we were inspecting input sheets given to us by @kdahlquist for issue #165 we noticed these extraneous 0s in the file 

`dHAP4_15_gene_network_deletion_added_input_KD_20160126_output_with_check`.

 We have not yet determined the source of this anomaly.
![capture](https://cloud.githubusercontent.com/assets/6529816/12741490/a9a8c380-c931-11e5-9b74-10e421a5158f.PNG)

**Comment by kdahlquist** [comment]
I think we should ignore this for now, so I'm closing this.  We can reopen it, if this resurfaces again.
