### ISSUE TITLE
L-curve error: when alpha causes fewer than 100 iterations, problem with optimization diagnostic figure

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#175]
As noted in issue #168, I have observed an error when attempting to run an L-curve where fix_b = 1 and fix_P = 1 (in other words when only w is estimated).  I've observed it twice and get the message:

Attempted to access strain_x1(2,:); index out of bounds because numel(strain_x1)=1.

Error in lse (line 104)
        x1 = strain_x1(i,:);

Error in GRNLCurve (line 66)
        GRNstruct = lse(GRNstruct);

Error in GRNmodel (line 32)
   GRNstruct = GRNLCurve(GRNstruct);

It seems to happen when starting the 14th alpha in the array, i.e., the output for the 13th alpha has been made and it has created the input sheet for the 14th.  The starting input file has been pasted below.

[dHAP4_15_gene_network_deletion_added_input_KD_20160126.xlsx](https://github.com/kdahlquist/GRNmap/files/114687/dHAP4_15_gene_network_deletion_added_input_KD_20160126.xlsx)

Do the tests files complete when the L-curve is turned on?

**Comment by trixr4kdz** [comment]
Our tests would pass when the longer list of alphas is uncommented and the shorter list is used for the L-curve runs. The tests would get the same error when the longer list of alphas is used.

**Comment by kdahlquist** [comment]
@juansc says that this bug is caused by the code that creates the optimization diagnostic figure when there is less than 100 iterations.  The shorter list of alphas didn't include the ones that finished the estimation with less than 100 iterations, so we didn't see this before.

**Comment by kdahlquist** [comment]
I have also now seen this error when running the MM production function estimating w, b, and P.

**Comment by kdahlquist** [comment]
This is related to Issue #132, so I am elevating that one so we can close them both when this is fixed.

**Comment by juansc** [comment]
I have created a test for this and fixed the bug.

**Comment by juansc** [comment]
When we perform an L_curve we generate several output files. If we perform an L_curve and any of these output files are in the same directory at the time that we run it(because we did an L_curve before and are doing it again) we will have an error. A suggestion is to remove these output sheets before making another run.

**Comment by kdahlquist** [comment]
I have confirmed that this now works with the file: dHAP4_15_gene_network_deletion_added_input_KD_20160126.xlsx with the optimization parameters:

L_curve =1
estimate_params =1
make_graphs =1
fix_P =1
fix_b=1

There was an optimization_diagnostic figure saved that had only 60 iterations.
