### ISSUE TITLE
Audit and documentation of current tests

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#177]
I'm giving this a 0.5 priority because I want @juansc and @trixr4kdz to tackle this next.

I would like to get a list of all the current tests we have and the test files that correspond to those tests, so we can gain some idea of what kind of test coverage we have.

In addition, I want to know the cases where you have computed an analytical solution to an equation so we know whether we have done this wherever possible or whether there are still some areas outstanding.

Documentation should go on the GitHub wiki.

**Comment by kdahlquist** [comment]
Link to TRACE documentation: http://www.openwetware.org/wiki/Dahlquist:TRACE_Documentation

**Comment by kdahlquist** [comment]
Let's organize this documentation on the GitHub wiki.  The information we want to know is as follows:

1. Category, e.g. reading input file, output sheets produced, analytical solutions to equations (correctness of computations)
2. Lists of the specific conditions you are checking for
3. test files associated with each test, e.g. input file used, results file it is being checked against

While doing this, make a to do list of tests if you notice any areas that are missing test coverage.

**Comment by juansc** [comment]
We created a [page]() on the wiki that contains documentation for the types of tests that are being done. We have not yet made a comprehensive of scenarios that we are not testing, so that can be the focus for this week.

**Comment by kdahlquist** [comment]
add documentation about the forward simulation tests to the wiki.

**Comment by dondi** [comment]
While working on #196, try to document concurrently because things will be fresh in everyone's minds at this time.

**Comment by juansc** [comment]
We have added more documentation while working on #196. This will remain an ongoing process as we are not yet done refactoring the test suite.

**Comment by kdahlquist** [comment]
This is now a duplicate of #361, so closing.
