### ISSUE TITLE
v1.4 release notes, web site

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#179]
* the release notes for v1.4 need to be updated with all the stuff (issues) that went into the release
* the release notes need to be added to the About page of the web site
* a news item needs to be added to the News page
* links to the code and executable need to be added to the Downloads page

**Comment by trixr4kdz** [comment]
The pages mentioned in the above comment have been updated.

**Comment by kdahlquist** [comment]
Please make the changes I requested as part of issues #180 and #181.

**Comment by trixr4kdz** [comment]
This is done.

**Comment by kdahlquist** [comment]
Confirmed and closing.
