### ISSUE TITLE
Release v1.4 missing RunTime Library

### ISSUE THREAD

**Issue by trixr4kdz** [kdahlquist/GRNmap#180]
The current v1.4 is missing the RunTime Library. We will have to include it ASAP.

**Comment by kdahlquist** [comment]
We will increment the version to 1.4.2 and once it is published and then delete 1.4 because it is broken without the run-time library.

**Comment by kdahlquist** [comment]
More specifically, please delete the download button for v1.4 on the Download page and put the following notice in its place:

*Note that the MATLAB Runtime Library was left out of the executable for this release by mistake. Users of the executable are directed to use release v1.4.2 instead.* [link the words "release "v1.4.2" to the download section for that release.]

**Comment by trixr4kdz** [comment]
The download button for v1.4 has been removed and section v1.4.2 has been added.

**Comment by kdahlquist** [comment]
Verified and closing.
