### ISSUE TITLE
Create release notes, about page, News item, downloads page for v1.4.2

### ISSUE THREAD

**Issue by cazinge** [kdahlquist/GRNmap#181]

**Comment by kdahlquist** [comment]
I have updated the release notes for both v1.4 and v1.4.2.  These changes need to propagate out to the About page (without reference to the actual issue numbers), News page, and Downloads page.  In particular, the button to download the executable for v1.4 should be removed, see issue #180 for details.

In the future, @cazinge, when you create an issue, please make a comment in it with further description and give it category labels as well as a priority label.

**Comment by juansc** [comment]
@kdahlquist I posted this issue. It was meant to be a short reminder to do the notes later. I did not realize that I was still using @cazinge's account

**Comment by kdahlquist** [comment]
Also, don't forget to update the last modified date on the web pages.

**Comment by trixr4kdz** [comment]
The above comments have been added to the web pages.

**Comment by kdahlquist** [comment]
Adjusted wording for release notes for v1.4.2 on both the release page and the About page.  Closing.
