### ISSUE TITLE
Next Meeting for Data Analysis Team: Friday, Feb. 19, 4:00PM, Seaver 120 

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#182]
Next week is the showing of Judgment Day: Intelligent Design on Trial for the Biology Seminar from 2:00-3:00 PM in LSB Auditorium.  Since @kdahlquist is hosting it, I kind of need to be there.  We will meet in S120 after the seminar at ~ 3:15.

**Comment by kdahlquist** [comment]
I just realized that the Judgment Day video I am showing is actually almost 2 hours long, so I will not be available to meet with you all until 4:00.

Would you please let me know by replying to this issue whether you can still meet at 4:00 tomorrow (Friday).

If it is not possible for you to meet, please give me an update on your progress for the week.

**Comment by khorstmann** [comment]
I unfortunately cannot meet, as I have a different meeting that was rescheduled a while back to 4 to fit the previous 3:00 meeting time. 

My progress I had been talking about already this week: I was able to start the 33 and 25 gene networks running on SEA 120 that were edited after the L-curve mishaps from two weeks ago. The 25 gene network finished relatively quickly, the 33 gene crashed after 10 alphas when @kdahlquist ran it, and finished to all 16 alphas when ran in SEA 120 after some errors logged in the L-curve post. The L-curve of the first 10 alphas was created yesterday and posted in the L-curve output issue. 
The L-curves for the full 16 outputs of the 33 genes as well as the 25 gene network will be created tomorrow afternoon and posted on github before the meeting.

**Comment by GraceJohnson** [comment]
I can meet at 4

**Comment by bklein7** [comment]
I can also meet at 4:00pm.

**Comment by maggie-oneil** [comment]
I can meet at 4 as well

**Comment by tessaam** [comment]
I can meet at 4 too.

**Comment by khorstmann** [comment]
Reran my l-curve graphs from the new and improved data. 
As stated above, from the first 10 alphas of the 33 gene network, the final few were all stacked on top of each other. unfortunately this did not change with the addition of 6 different alphas. The 33 gene L-curve can be found here: http://openwetware.org/wiki/Image:ZAP1_l-curve_33-genes_fullalphas.pdf and the 25-gene L-curve can be found here: http://openwetware.org/wiki/Image:ZAP1_l-curve_25-genes_fixed_2-19.pdf
