### ISSUE TITLE
Bug when "threshold_b" header omitted from "threshold_b" worksheet

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#185]
@tessaam has observed (and I think it might have happened to @khorstmann as well) that when the header for the second column of the "threshold_b" worksheet is omitted, a problem occurs with the L-curve runs.

For the first alpha, the input workbook is copied over OK and it runs.  However, when the workbook is copied over again for the second alpha, using the parameters from the first run as the initial guesses, the entire column gets shifted over to the right leaving a blank column in between.

Then, it still runs, but gives whacked out results that lead to an "S-shaped" curve instead of an "L" curve.

We need to implement a check of the input worksheet that the correct format of that sheet is in place.

**Comment by tessaam** [comment]
The column gets shifted over for production_rate and threshold_b in the second alpha even when the title "threshold_b" is present in the second column of the threshold_b sheet.

**Comment by kdahlquist** [comment]
@GraceJohnson has also observed this behavior and it has likely caused an issue with the L-curve results that she reported as part of issue #172 .

**Comment by kdahlquist** [comment]
I have verified that this bug still occurs with the L-curves run this summer.  However, it doesn't seem to be tied to weird results.  I'm attaching a sample workbook with the phenomenon.  Look at the production_rates sheet and threshold_b sheet.
[15-genes_28-edges_db5_Sigmoid_estimation_missing-values_L-curve_2.xlsx](https://github.com/kdahlquist/GRNmap/files/1301752/15-genes_28-edges_db5_Sigmoid_estimation_missing-values_L-curve_2.xlsx)

**Comment by kdahlquist** [comment]
I have verified that this bug is fixed with the beta code downloaded on 11/13/17.  I don't want to close this issue until we have unit tests in place, however.

**Comment by kdahlquist** [comment]
@jtorre39: try this input workbook for reproducing the bug:

https://github.com/kdahlquist/DahlquistLab/blob/master/data/Summer2017/L-curve/15-genes_28-edges_db5_Sigmoid_estimation_missing-values_L-curve.xlsx

**Comment by jtorre39** [comment]
Bug reproduced! Will be proceeding with typical TDD procedures.

**Comment by jtorre39** [comment]
See #386

**Comment by kdahlquist** [comment]
This is closable because it is fixed and the test is there.
