### ISSUE TITLE
Convert adjacency matrix to edge list

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#186]
We have a need to convert the adjacency matrix to a list of pairwise interactions (edge list) so that we can do the bar chart of the weight parameters.  A quick Google search turned up this code snippet from R.

From: http://artax.karlin.mff.cuni.cz/r-help/library/PCIT/html/getEdgeList.html

getEdgeList {PCIT}
Converts an adjacency matrix into edge list representation
Description

Given an adjacency matrix, converts it into edge list representation. This edge list can be written to a file for easy import into other software such as cytoscape.

Only the upper triangle is returned as it is assumed the matrix is symmetric. The edge list is returned as a data frame with 3 columns: 'From', 'To' and 'Weight'.
Usage

	getEdgeList(m, rm.zero=TRUE)

Arguments
m 	

- An adjacency matrix.
rm.zero 	

- A boolean to indicate whether zero weight edges should be excluded from the edge list.
Author(s)

Nathan S. Watson-Haigh
Examples

	data(PCIT)
	m <- m[1:200,1:200]        # just use a small subset of the data
	
	el <- getEdgeList(m)
	
	# modify the edge list to include some useful attributes for cytoscape
	el$sign[el$Weight<0] <- '-'
	el$sign[el$Weight>0] <- '+'
	el$Weight <- abs(el$Weight)
	# write the edge list stuff to a file suitable for import into cytoscape
	write.table(el, file="el.txt", row.names=FALSE, col.names=TRUE, sep="\t",

**Comment by bklein7** [comment]
I did not find the PCIT package to be very robust. During testing, this package was prone to frequent crashes and at times did not yield accurate edge lists. However, a separate R package by the name of "igraph" also offers the tools to perform this conversion and yielded consistently accurate results during testing.

I wrote a script that uses the "igraph" package to convert adjacency matrices to edge weight lists. The edge weight lists are output as .csv files, which are easily input into Excel. A brief description and tutorial can be found here: http://openwetware.org/wiki/Converting_Adjacency_Matrices_to_Edge_Lists_in_R

**Comment by GraceJohnson** [comment]
I just discovered that @bklein7's script reverses the order of the "from" and "to" column. To interpret the matrix list correctly, the columns should be switched and re-alphabetized based what was incorretly labeled the "to" column.

**Comment by kdahlquist** [comment]
The issue that @GraceJohnson reported above is still outstanding.  @bklein7 will return to it later.

**Comment by kdahlquist** [comment]
This issue is now superseded because GRNsight has the ability to export a weighted graph in SIF format.  See the GRNsight Documentation page for details.  http://dondi.github.io/GRNsight/documentation.html
