### ISSUE TITLE
Posters for LMU Symposium

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#191]
First draft is due by our Friday, March 11 meeting so that changes can be suggested and made in time to print them out the following week.

**Comment by GraceJohnson** [comment]
@kdahlquist where is the the description of the suggested contents of our posters? I saw you typing it during our meeting Friday but can't find it now for some reason.

**Comment by kdahlquist** [comment]
I think that's because I was writing it on the board.  Here it is (approximately and maybe not in the right order that I had it):

* Background explaining the differential equation (sigmoidal)
* Background explaining the penalized least squares approach to estimation, showing one example of an L-curve
* Method of how the family of networks was created: wt and deletion strains, microarray experimental design, normalization, ANOVA, YEASTRACT, strategy for pairing down networks
* show GRNsight visualization of the five networks for which we are going to do production runs side by side (with the genes arranged in the same order each time so that they can be visually compared)
* show the in-degree/out-degree bar chart for the five networks
* Show a bar chart comparing the w's, b's, and P's for the five networks like we did for the L-curves; the only issue here will be that in the series of networks, nodes and edges are dropped so that there will be missing bars for some of the edges/genes.
* Expression plots for key interesting genes, including the ANOVA p value and the MSE
* Table of LSE, minimum theoretical LSE for each of the five networks (and maybe a ratio of the two)
* From all of this we hope to determine if one of the networks does a better job overall of explaining the data and which genes themselves are modeled particularly well (or not well).

**Comment by GraceJohnson** [comment]
Quick question, does GRNsight automatically read the "network_optimized_weights" sheets in the output file? If you wanted to use an output file from an L-curve analysis run both the "network_weights" and "network_optimized_weights" have non-1 values. I was wondering if there was any confusion about which sheet gets visualized.

**Comment by kdahlquist** [comment]
GRNsight does automatically read the "network_optimized_weights" sheet in the output file if it is there, superseding the "network_weights" sheet, or at least it should.  Are you having a problem?

Selecting the menu item Edit > Preferences > Default to black edges with regular arrowheads will make the graph display as an unweighted graph even if the worksheet "network_optimized_weights" has real numbers instead of 1's to indicated weighted edges.)

**Comment by GraceJohnson** [comment]
No problems I believe, just checking. Thanks for clearing it up.
