### ISSUE TITLE
Test coverage plugin

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#196]
www.mathworks.com/help/matlab/ref/matlab.unittest.plugins.codecoverageplugin-class.html

Use this (if we can) to estimate test coverage of our code for the LMU Symposium Presentation.

**Comment by kdahlquist** [comment]
* plugin has been implemented
* it's not reporting a holistic view of the coverage of all the code, it splits it into different tabs for the different tests
* in order to get a single coverage stat for the entire code, the test suite would need to be refactored.

What needs to be done in the refactoring process is:
* Remove the setup portion of the code from the test runner and put it in its own place.

@juansc will talk to @dondi later today to make sure that we refactor the test suite appropriately.

**Comment by juansc** [comment]
@dondi suggested using `runtests` and passing in an array of tests. Maybe this way the plugin will do an overall coverage for all the tests.

**Comment by juansc** [comment]
@trixr4kdz discovered [paramterized tests](http://www.mathworks.com/help/matlab/matlab_prog/create-advanced-parameterized-test.html) which allow us to iterate over paramters in out test suite.

**Comment by dondi** [comment]
There are 14 more fixtures to make; @cazinge is generally on board so this can be done in parallel among @trixr4kdz, @juansc, and @cazinge. We are currently getting 85-90% test coverage.
![flat 800x800 070 f](https://cloud.githubusercontent.com/assets/382242/14327013/53a4a2f6-fbe5-11e5-82e1-a44f1f9b2685.jpg)

**Comment by trixr4kdz** [comment]
We have finished making all the fixtures.

**Comment by trixr4kdz** [comment]
We combined the tests into a single suite so we get the error reporting and the test coverage for all the refactored code together. Here is the test coverage



![coverage](https://cloud.githubusercontent.com/assets/8975300/14484737/39cec86c-0107-11e6-82fb-546acdb702b7.PNG)
.

**Comment by kdahlquist** [comment]
Refactoring of test suite is complete.  New issues will be opened to refer to specific tests that will be made.
