### ISSUE TITLE
Write test for michaelis-menten

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#199]
The michaelis-menten function is the only equation that hasn't been tested yet, so it is next on our list.

**Comment by juansc** [comment]
We need a numerical/analytical approach to solve the differential equation. We could use traditional methods such as [Euler's Method](https://en.wikipedia.org/wiki/Euler_method) to try to find a numerical solution and then use these to test the Michaelis-Menten function and Sigmoid function.

**Comment by bengfitzpatrick** [comment]
I recommend against Euler's method. You have to debug your testing tool first.  Matlab's ode45 is already debugged.

**Comment by kdahlquist** [comment]
![sigmoid_equation](https://cloud.githubusercontent.com/assets/6463867/14684932/0ec30e72-06e7-11e6-857a-16dab63f217c.jpg)
This is what I think is the correct sigmoidal equation

**Comment by juansc** [comment]
We are unsure if we are using the corect Michaelis-Menten equation. This is the one we're using 
![screen shot 2016-04-20 at 10 59 39 am](https://cloud.githubusercontent.com/assets/6529816/14684937/1313f284-06e7-11e6-8b46-c4f7e09ccdd2.png)

**Comment by kdahlquist** [comment]
@dondi says:
* ideally we want to have test solutions that have maximum independence from the tool being tested.
* most preferable set of answers is the set reached analytically
* barring that, then we would look at a set of answers produced by a reliable, independent tool, like Mathematica
* below that (and not preferable) are ones that are derived from the codebase we are testing.

**Comment by juansc** [comment]
I spend some time looking at using Mathematica to solve the same differential equation. This would be difficult without someone who is very familiar with Mathematica to help us. I suggest we ask Dr. Fitzpatrick or someone familiar with other mathematical software for help on this one.

**Comment by kdahlquist** [comment]
We have disabled MM for now; backlogging this issue.
