### ISSUE TITLE
Coding team wrap-up for the Spring 2016 semester

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#200]
This is what needs to be done to wrap-up for the Spring 2016

@juansc , @trixr4kdz , and @cazinge will meet to do the following:
- [x] reviewing the code
- [x] closing any gaping loose ends in the code
- [x] delete the output_directory branch
- [x] merge beta into master
- [x] release master branch, create executable
- [x] make changes to News, About pages relating to release
- [x] document next steps, if there had been more time to keep going

**Comment by cazinge** [comment]
We've only created a draft release. We will publish the release on Wednesday, as it is a hallowed tradition. We've documented some next steps in issues #203 and #199.

**Comment by cazinge** [comment]
We have decided that me, @cazinge, will work on the News and About pages, as this has been labeled as "Eddie work".

**Comment by juansc** [comment]
The Downloads page, the About page and the News page all need to be updated. The About page should have updated release notes. The Downloads page should be updated appropriately, including adding a button to download the executable.

A reminder: We need to manually update the "last modified date" for all updated pages. This is found on the lower left-hand side of the navigation bar.

**Comment by cazinge** [comment]
I've finished making the above changes in pull request #207, I've already merged the PR, All that's necessary now is for @kdahlquist to close the issue.

**Comment by kdahlquist** [comment]
I was out last week.  I'll take a look at the changes.  When you want me to look at something, you can assign it to me and mark it with the label of "review requested".

**Comment by kdahlquist** [comment]
Verified changes.
