### ISSUE TITLE
Coding meeting schedule for Fall 2016

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#204]
Looking at everyone's schedules for the Fall, it looks like Wednesdays at 11:30 or 12:00 might be a good time for @kdahlquist, @trixr4kdz , @cazinge , @dondi , and @bengfitzpatrick to meet.

**Comment by kdahlquist** [comment]
The GRNmap coding group will meet at 11:30 on Wednesdays.

**Comment by trixr4kdz** [comment]
@cazinge, @jtorre39, @yshin4 here are my available hours:
* Monday: after 5pm
* Tuesday: after 12pm
* Friday: after 12pm

**Comment by trixr4kdz** [comment]
We have decided that we will have the 4-hour block at 4:30pm on Tuesdays.

**Comment by kdahlquist** [comment]
@yshin4 is going to switch over to the GRNsight team as of next week.

**Comment by kdahlquist** [comment]
Settled and closing.
