### ISSUE TITLE
Data analysis meeting schedule for Fall 2016

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#205]
Looking at the schedules for @bklein7 , @maggie-oneil , @khorstmann , and @Nwilli31 for Fall 2016, it looks like a good meeting time that would work for everyone is Mondays at 3:00.

This works out well for me because the GRNsight meeting will be immediately afterwards at 4:00 that day.

**Comment by khorstmann** [comment]
Ideally, I'd like to work in the lab from 2:30-6:30 on Tuesday afternoon

**Comment by maggie-oneil** [comment]
I'd like to work in the lab from 4pm-8pm on Tuesday afternoons

**Comment by kdahlquist** [comment]
Because of scheduling issues for the GRNsight team, the Monday GRNmap data analysis meeting is moved up 15 minutes to 2:45PM in LSB289.

**Comment by Nwilli31** [comment]
@bklein7 and I have decided that we can do Wednesday afternoons, overlapping from approximately 3:00 - 4:20 pm. @bklein7 can do 3:00 - 7:00 pm. @Nwilli31 is available from noon (12 pm) until 4:20 pm. If there is any conflict with our schedules, we will repost a time(s) that we are available.

**Comment by kdahlquist** [comment]
Got it.  I am closing this now.
