### ISSUE TITLE
Add a Privacy Policy to GRNmap web site as required by our use of Google Analytics

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#211]
This needs to be implemented as is being done for GRNsight as part of GRNsight issue 258 here:  https://github.com/dondi/GRNsight/issues/258

**Comment by cazinge** [comment]
Are we to use the same solution to create the Privacy Policy as was suggested by @mihirsamdarshi? It seems like just notifying the user that we use cookies (I'm not sure we do if all we're using is google analytics) doesn't cover everything that a privacy policy seems to entail.

Using [Github's Privacy Policy](https://help.github.com/articles/github-privacy-policy/) as an example, Can we have more context as to what we're to include in said privacy policy? @kdahlquist

**Comment by kdahlquist** [comment]
We are working on this over at GRNsight, issue 258 here:  https://github.com/dondi/GRNsight/issues/258

Once we get it completely implemented, we'll carry over the relevant stuff to GRNmap.  So far, we've added language to the About page here:  http://dondi.github.io/GRNsight/about.html#privacy and have added links to it on the sidebar and footer of each page.

We are going to add a banner notice that users can click through notifying them of the use of cookies as is required by the EU.  @dondi expects to work on this in the next couple of weeks.

**Comment by kdahlquist** [comment]
This has been fully implemented in GRNsight, so we should go ahead and make the changes to GRNmap as well.  GRNsight issue 258 here: dondi/GRNsight#258

**Comment by dondi** [comment]
As it turns out, the banner functionality is not practical to implement until we have ported the site to Jekyll (issue #212). For the moment (as with GRNsight previously), a standalone privacy statement has been added to the [About page](http://kdahlquist.github.io/GRNmap/about.html#privacy). Implementation of a banner + cookie can be done after Jekyll conversion, either as a new issue or as a remaining subtask for this issue.

**Comment by kdahlquist** [comment]
OK.  Can we add the link to the Privacy statement on the sidebar and footer like we did for GRNsight?  I might try to do it myself if I can figure it out, otherwise we can take care of this in the meeting today.

**Comment by kdahlquist** [comment]
Just realized I have to add the privacy links individually on each page because not Jekyll.  Well, here goes...

**Comment by kdahlquist** [comment]
I've finished adding the links.  Since we can't do anything more about this now, I'm closing it.  There's a comment on #212 to remind us to do it once the site is converted to Jekyll.
