### ISSUE TITLE
Convert GRNmap web site to Jekyll

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#212]
It would be convenient to convert the GRNmap web site to Jekyll as was done for GRNsight.

**Comment by cazinge** [comment]
I haven't been able to find any reference to a Pull Request or Issue that addresses the conversion over to Jekyll over in GRNsight. Is there a commit or something that I can reference in order to implement this change? @kdahlquist @dondi

**Comment by kdahlquist** [comment]
I don't know that it was a particular issue in GRNsight.  @NAnguiano made a tutorial for Jekyll on the GRNsight wiki here:  https://github.com/dondi/GRNsight/wiki/Jekyll-Tutorial

@dondi can weigh in when he gets a chance.

**Comment by kdahlquist** [comment]
Copied over comment by @dondi from #211:

As it turns out, the [privacy statement ] banner functionality is not practical to implement until we have ported the site to Jekyll (issue #212). For the moment (as with GRNsight previously), a standalone privacy statement has been added to the About page. Implementation of a banner + cookie can be done after Jekyll conversion, either as a new issue or as a remaining subtask for this issue.

**Comment by cazinge** [comment]
I've initiated a Pull Request for this on #234, please check out the status of the site conversion there.

**Comment by kdahlquist** [comment]
@cazinge will create separate User Documentation and Developer Documentation pages.  The latter will be especially useful as new developers come on board.

**Comment by kdahlquist** [comment]
Remaining tasks have been listed in issue #254, so I'm closing this one.
