### ISSUE TITLE
Create collapsible sections for GRNmap Documentation page

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#214]
There is one collapsible section already there for system requirements, but I need at least a couple more:

How to Format the Input File

How to Interpret the Output File

Put these underneath the system requirements one, and default the first one to open and the others to closed.

Then I'll start moving over the wiki content to the documentation page.

Related to #4

**Comment by dondi** [comment]
OK, this is done. Make sure to keep content within the `div class="panel-body"` (currently put an _Under construction_ placeholder there).

**Comment by kdahlquist** [comment]
Confirmed and closing.
