### ISSUE TITLE
Fix layout of picture on People page

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#215]
@dondi, I forgot to ask you today, can you take a look at the GRNmap People page and fix the layout so the picture is in the upper right corner?  Thanks.

**Comment by dondi** [comment]
This has been fixed. However, in doing so I discovered something: some pages on the GRNmap site link out to the _GRNsight_ CSS file, and not its own (the people page was one of them). I made the people page use GRNmap’s own CSS file, but a few other files remain linked out. This is not practical to fix/maintain until the whole site has been converted to Jekyll, for which we already have issue #212.

**Comment by kdahlquist** [comment]
OK.  I'm going to copy @dondi's previous comment over to #212 and close this one.  I managed to add the Privacy links to the sidebar and footer and didn't mess up the formatting, so I'll go ahead and close this now.
