### ISSUE TITLE
Change to versioning style due to packaging requirements for executable

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#216]
I am testing out how to package the executable using the MATLAB compiler.  I have discovered two things:
1. The version number has not been incremented in the current v1.4.4 version of the executable--it still says version 1 when running the MCR installer.
2. The MATLAB compiler only supports versioning in the form of major.minor, e.g. 1.0 or 1.2, etc.  It does not support a third number like we have with 1.4.4.

Thus, I think so that we can keep the version number of the code and executable in sync, we can only use the major.minor format.

I am going to work on releasing version 1.6 with the purpose of synchronizing the version numbers, updating the readme, and packaging a demo file with the executable.

**Comment by kdahlquist** [comment]
We are going to do a 0% release of the current beta, so we can deal with this issue at the same time.

**Comment by dondi** [comment]
The dev team has handled the file/tech/release issue, looking to see if the documentation part that @kdahlquist was going to do has been completed.

**Comment by dondi** [comment]
Updated to lower priority pending @kdahlquist's availability.

**Comment by kdahlquist** [comment]
Since this issue is only about the versioning numbers and we have another issue about packaging the ReadMe and demo files #208, we can close this one.
