### ISSUE TITLE
Add Code of Conduct to GRNmap website

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#219]
We should consider adding a Code of Conduct to the GRNmap project. Let's discuss this at an early face-to-face meeting this semester.

See: http://contributor-covenant.org/

**Comment by trixr4kdz** [comment]
I've read the Code of Conduct and I see no harm in adding it.

**Comment by kdahlquist** [comment]
A reminder to *all* GRNmap team members to read the Code of Conduct here:  http://contributor-covenant.org/

Please post a comment on this issue when you have read it and agree to add it to the GRNmap project.

**Comment by khorstmann** [comment]
Read through code of conduct. I agree to to add it.

**Comment by maggie-oneil** [comment]
I read through the code of conduct and agree that it should be added to this project.

**Comment by jtorre39** [comment]
I read the code of conduct and it should be added to the project.

**Comment by cazinge** [comment]
I've read through the code of conduct and believe it should be added to the project.

**Comment by kdahlquist** [comment]
Still need a comment from @bklein7 and @Nwilli31.

**Comment by Nwilli31** [comment]
I read the code of conduct, and it should be added to the project.

**Comment by bklein7** [comment]
I have read the code of conduct, and I agree that it should be added to this project.

**Comment by kdahlquist** [comment]
The code of conduct has been added. I think we need to reference it on the About page.

Lets rearrange the collapsible sections and add a new one called "Code of Conduct". The order of the sections should be:
* Availability
* System Requirements and Compatibility
* Release Notes
* Funding
* Privacy
* Code of Conduct

The Code of Conduct needs to be a new collapsible section. The text inside the section should read:

This project has been released with a Contributor Code of Conduct. Participants in this project have agreed to abide by its terms. The full Code of Conduct can be read [here](https://github.com/kdahlquist/GRNmap/blob/master/CODE_OF_CONDUCT.md).

I am assigning the task of updating the About page to @jtorre39, who should work with @cazinge because he is in the process of porting the site to Jekyll #234..

**Comment by kdahlquist** [comment]
All website issues are being assigned to @cazinge.

**Comment by kdahlquist** [comment]
I added the code of conduct to the About page.  I introduced some minor formatting issues with the collapsible sections, but hopefully these can be resolved quickly.  I am closing this one.
