### ISSUE TITLE
Add Justin to People page

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#222]
Add Justin to People page.

**Comment by jtorre39** [comment]
Added myself and updated the date modified line.

**Comment by kdahlquist** [comment]
I saw the change--it seems to me that the picture got shifted a little to the right, but I may be wrong.  Let's quickly discuss at the meeting today.

**Comment by kdahlquist** [comment]
The picture was probably where it was--I'm just not remembering.  Closing.
