### ISSUE TITLE
Investigate graph properties

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#224]
@khorstmann and @maggie-oneil are investigating the literature to find out which graph properties will be relevant to understanding the GRNmap model results.  

The Pavlopoulos et al. 2011 review is a good place to start:  http://biodatamining.biomedcentral.com/articles/10.1186/1756-0381-4-10

**Comment by kdahlquist** [comment]
We are going to start with looking into MATLAB functions for computing the shortest path between two nodes and betweenness centrality.  These are two properties that GRNsight will have implemented soon, but it will be good to have an independent verification of the numbers from a different source.

Look to see if there are some premade functions in the Systems Biology toolbox.

It would also be good to write script for automatically generating degree distribution plots.  @khorstmann and @maggie-oneil can work on a MATLAB implementation and @bklein7 can work on an R implementation (I'll write it up as a separate issue).

**Comment by kdahlquist** [comment]
The lit search is almost done.  @khorstmann and @maggie-oneil will investigate either the <biblio> tag or Zotaro for citation software to ease making the bibliography.

We will focus on betweenness centrality as the first graph statistic to compute.

Don't forget to log progress on this issue during the week.

**Comment by kdahlquist** [comment]
Will @khorstmann and @maggie-oneil post an update on this issue with links to their bibliographies?  Is this issue ready to be closed now?  If so, after posting the links, please mark it as "review requested" and assign @kdahlquist to it.

**Comment by maggie-oneil** [comment]
@kdahlquist The bibliography has been completed, attached to this issue comment is a PDF version of the bibliography, and the following is a shortened link to a Google doc version of the bibliography should you wish to view it a different way. [https://goo.gl/GHJmEm
[Literary Research on Graph Theory.pptx.pdf](https://github.com/kdahlquist/GRNmap/files/509801/Literary.Research.on.Graph.Theory.pptx.pdf)
](url)

**Comment by kdahlquist** [comment]
@maggie-oneil, "review requested" is one of the labels you can assign to an issue.  Look at the upper right hand side of the issues page and Click on the "Labels" heading to assign labels.

@khorstmann 's e-mail worked.  The documentation for SBET toolbox can be accessed from:

https://promis.tamu.edu/projects/sbetoolbox/wiki/SBEToolbox_User_Manual

**Comment by kdahlquist** [comment]
@kdahlquist needs to review.

**Comment by kdahlquist** [comment]
@maggie-oneil and @khorstmann, don't forget to update this issue with progress you've made.  The URL for the documentation is:  https://promis.tamu.edu/projects/sbetoolbox/wiki/SBEToolbox_User_Manual

**Comment by kdahlquist** [comment]
I have reviewed the bibliography and moved discussion of implementing SBET toolbox to a new issue #259.
