### ISSUE TITLE
Preallocate GRNstruct Arrays to Zeros Arrays

### ISSUE THREAD

**Issue by trixr4kdz** [kdahlquist/GRNmap#231]
- [x] We would need to find all the arrays in the code that need to be initialized
- [x] Before actually implementing the initializeArrays function that @bengfitzpatrick mentioned during our meeting to fix issue #51, we would have to first create tests to check whether the necessary arrays are created with the correct dimensions.
- [x] After creating unit tests, we would create a new function for preallocating the necessary arrays.

**Comment by trixr4kdz** [comment]
We have looked through the code for arrays that would need to be initialized and compiled a list which can be found [here](https://github.com/kdahlquist/GRNmap/wiki/Arrays-that-need-to-be-initialized).

We have also started to create the initializeArrays function along with the tests.

**Comment by kdahlquist** [comment]
It seems to me that we should be able to match up all the arrays you listed in the wiki to something in the input sheet.

**Comment by trixr4kdz** [comment]
I've updated the wiki to reflect whether they are coming from the input sheet, are derived data, or are not used/can be removed (with some minor adjustments to the code).

**Comment by kdahlquist** [comment]
b vector should be initialized up front
* if using the sigmoid model, can determine from the adjacency matrix how big it needs to be
* MM doesn't use b

**Comment by kdahlquist** [comment]
@trixr4kdz said on issue #238:

"I've revised the wiki to specify which arrays are read directly from Excel, which are manipulated, etc. Another thorough look at the code shows that there are already initializations for the arrays. I would try to move these preallocations but that would require separating certain operations into new scripts.

I also think that we can just parametrize the variables at the bottom of readInputSheet, which are also listed in the wiki under "Variables that can be parametrized", so that we do not have to keep them as global variables."

For this week, @trixr4kdz and @jtorre39 should clean-up any remaining tasks with this issue so that it can be closed next week.

**Comment by trixr4kdz** [comment]
The initializeArrays function has been finalized so this issue can be closed.

**Comment by bengfitzpatrick** [comment]
Here is the entirety of the GRNstruct data structure.  It's long for an issue comment, but I want to put here for reference.  The initializeArrays function does not treat many of the fields in this data structure.  We need a clear map of where each of these is initialized.

GRNstruct = 

         fileName: '4-genes_6-edges_artificial-data_Sigmoid_estimatio...'
        directory: 'Y:\LMU\Projects\GeneExpression\grnMAPcodeTasks\GR...'
        inputFile: 'Y:\LMU\Projects\GeneExpression\grnMAPcodeTasks\GR...'
        microData: [1x2 struct]
           labels: [1x1 struct]
         degRates: [1 1 1 1]
        GRNParams: [1x1 struct]
    controlParams: [1x1 struct]
        GRNOutput: [1x1 struct]
         GRNModel: [1x2 struct]
           locals: [1x1 struct]
           
GRNstruct.microData

1x (number of Strains) struct array with fields:

    data
    Strain
    deletion
    t
    avg
    stdev       
    
GRNstruct.labels
        
        TX1: {5x1 cell}
        TX0: {5x2 cell}
        TX2: {5x5 cell}
        TX3: {5x5 cell}
        TX5: {5x2 cell}
        TX6: {5x2 cell}
        
GRNstruct.GRNParams
	
		    wtmat: [4x4 double]
	    adjacency_mat: [4x4 double]
		  prorate: [4x1 double]
		num_edges: 6
		num_genes: 4
		   active: [1 2 3 4]
		    alpha: 1.0000e-10
    expression_timepoints: [0.4000 0.8000 1.2000 1.4000]
		num_times: 4
			b: [4x1 double]
		    nData: 52
		   minLSE: 1.8667e-33
		no_inputs: [0x1 double]
		is_forced: [4x1 double]
	       num_forced: 4
		positions: [6x2 double]
	       x0: [4x1 double]
        
>> GRNstruct.controlParams

    simulation_timepoints: [1x21 double]
                   kk_max: 1
                  MaxIter: 100000000
               MaxFunEval: 100000000
                   TolFun: 1.0000e-10
                     TolX: 1.0000e-10
          estimate_params: 1
              make_graphs: 1
      production_function: {'Sigmoid'}
                    fix_b: 1
                    fix_P: 0
                  L_curve: 0       

>> GRNstruct.GRNOutput

            lse_0: 0.0193
          lse_out: 7.0328e-12
          reg_out: 0.9915
          counter: 1248
        lse_final: 1.0619e-10
              SSE: [4x2 double]
                d: [4x12 double]
             name: 'Y:\LMU\Projects\GeneExpression\grnMAPcodeTasks\GR...'
          prorate: [4x1 double]
          degrate: [1 1 1 1]
              wts: [6x1 double]
                b: [4x1 double]
    adjacency_mat: [4x4 double]
           active: [1 2 3 4]
            tspan: [0.4000 0.8000 1.2000 1.4000]
            alpha: 1.0000e-10
            
>> GRNstruct.GRNModel

 1x (number of strains) struct array with fields:
	    
    model
    simulation_timepoints
    
>> GRNstruct.locals
    
    initial_guesses: [10x1 double]
    estimated_guesses: [10x1 double]

**Comment by dondi** [comment]
@trixr4kdz will perform an audit of the properties listed by @bengfitzpatrick and annotate lines in the code where the assignment(s) can be found, e.g.:

[`GRNstruct.fileName`](https://github.com/kdahlquist/GRNmap/blob/4309f009d03b69dd724740aae8152d2bc342de57/matlab/GRNmodel.m#L3)
[`GRNstruct.directory`](https://github.com/kdahlquist/GRNmap/blob/4309f009d03b69dd724740aae8152d2bc342de57/matlab/GRNmodel.m#L3)

...that way it is easy to cross-check the completeness of the initialization.

Links should be derived from the specific version so they do not break with future revisions.

**Comment by trixr4kdz** [comment]
Here are the links for the initialization of the arrays listed by @bengfitzpatrick:

[`GRNstruct.degrates`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/readInputSheet.m#L82)

[`GRNstruct.microData.data`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/readInputSheet.m#L61)
[`GRNstruct.microData.Strain`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/readInputSheet.m#L58)
[`GRNstruct.microData.deletion`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/readInputSheet.m#L59)
[`GRNstruct.microData.t`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/readInputSheet.m#L148)
[`GRNstruct.microData.avg`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/readInputSheet.m#L162)
[`GRNstruct.microData.stdev`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/readInputSheet.m#L163)

[`GRNstruct.labels.TX1`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/readInputSheet.m#L61)
[`GRNstruct.labels.TX0`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/readInputSheet.m#L82)
[`GRNstruct.labels.TX2`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/readInputSheet.m#L83)
[`GRNstruct.labels.TX3`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/readInputSheet.m#L84)
[`GRNstruct.labels.TX5`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/readInputSheet.m#L85)
[`GRNstruct.labels.TX6`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/readInputSheet.m#L118)

[`GRNstruct.GRNParams.wtmat`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/readInputSheet.m#L83)
[`GRNstruct.GRNParams.adjacency_mat`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/readInputSheet.m#L84)
[`GRNstruct.GRNParams.prorate`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/readInputSheet.m#L85)
[`GRNstruct.GRNParams.active`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/readInputSheet.m#L90)
[`GRNstruct.GRNParams.expression_timepoints`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/readInputSheet.m#L92)
[`GRNstruct.GRNParams.b`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/readInputSheet.m#L118)
[`GRNstruct.GRNParams.no_inputs`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/readInputSheet.m#L192)
[`GRNstruct.GRNParams.is_forced`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/readInputSheet.m#L193)
[`GRNstruct.GRNParams.positions`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/readInputSheet.m#L203)
[`GRNstruct.GRNParams.x0`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/readInputSheet.m#L206)

[`GRNstruct.controlParams.simulation_timepoints`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/readInputSheet.m#L98)

[`GRNstruct.GRNOutput.SSE`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/initializeArrays.m#L12)
[`GRNstruct.GRNOutput.d`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/initializeArrays.m#L13)
[`GRNstruct.GRNOutput.prorate`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/initializeArrays.m#L14)
[`GRNstruct.GRNOutput.degrate`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/initializeArrays.m#L15)
[`GRNstruct.GRNOutput.wts`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/initializeArrays.m#L16)
[`GRNstruct.GRNOutput.b`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/initializeArrays.m#L17)
[`GRNstruct.GRNOutput.adjacency_mat`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/initializeArrays.m#L18)
[`GRNstruct.GRNOutput.active`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/initializeArrays.m#L19)
[`GRNstruct.GRNOutput.tspan`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/initializeArrays.m#L20)

[`GRNstruct.GRNModel.model`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/initializeArrays.m#L10)
[`GRNstruct.GRNModel.simulation_timepoints`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/initializeArrays.m#L10)

[`GRNstruct.locals.initial_guesses`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/initializeArrays.m#L9)
[`GRNstruct.locals.estimated_guesses`](https://github.com/kdahlquist/GRNmap/blob/48da7b9d78a4640a38b20a64220967f489501706/matlab/initializeArrays.m#L10)

**Comment by bengfitzpatrick** [comment]
This work looks complete. Willing to close upon testing evidence that code works.

**Comment by kdahlquist** [comment]
@bengfitzpatrick said that @trixr4kdz should comment along the lines of "Here are the folders and files for test comparisons..."

**Comment by kdahlquist** [comment]
We ran the test suite pertaining to this during the meeting and all tests passed.

**Comment by trixr4kdz** [comment]
The files requested are in my fork located [here](https://github.com/trixr4kdz/GRNmap/tree/beta/test_files/review-requested/requested-files-from-101216). I noticed though that the files from the master branch do not have the corrected MSE calculations that have been implemented in beta. That is, the MSE values are accumulating for each of the gene instead of being calculated for each individual gene. I've included the files from last semester's commit after this correction has been added so we can compare it with the new changes concerned with preallocation.

Additionally, the 21-gene network doesn't have the "optimization_diagnostics" sheet since the sheet did not exist when these bigger networks were created.

**Comment by kdahlquist** [comment]
We haven't merged beta into master for a long time, so I can imagine that there are many things out of sync.  I'm not sure what to do about this because the rest of the code isn't in a state where we would want to merge.  @bklein7 is going to clean up some remaining issues with the formatting of the "16 tests" files today as well.

**Comment by dondi** [comment]
@dondi and @bengfitzpatrick reviewed the last fix for a bug involving `adjacency_mat` and after finding that the code didn't clearly show _how_ the bug was fixed, we discovered that due to lack of time, the scenario was not retried after @trixr4kdz and @jtorre39 merged his branch. We suspect that the merge was faulty, but we need to confirm this. If the merge _was_ faulty then it should be fixed.

**Comment by kdahlquist** [comment]
Look at every place in the code where adjacency_mat is touched.

Log the W matrix inside general_dynamics_sigmoid function where to find when the dimension changes.

@bengfitzpatrick is going to look at it in parallel and @trixr4kdz will look at it, too.

**Comment by trixr4kdz** [comment]
The problem arises when the global variable ```deletion``` is not cleared properly instead of adjacency_mat. Note that this is not an array, but a variable that contains the index of genes that have been removed (i.e., if gene cin5 is removed, then it tells GRNmap the row index of that gene in the dcin5 expression data sheet). More specifically, the error is created on line 37 seen here:

![w-error](https://cloud.githubusercontent.com/assets/8975300/19819438/7fc493c6-9d09-11e6-8116-ec2bf74cc5df.PNG)

The result is seen here where the top matrix is before the if-statement is executed and the bottom is after):
![iteration](https://cloud.githubusercontent.com/assets/8975300/19821152/c497f92c-9d11-11e6-87e5-efafbd7cc173.PNG)

The 4x4 matrix becomes a 6x6 since deletion = 6.

**Comment by bengfitzpatrick** [comment]
Thus the question arises, why is deletion not set to 0 at the beginning?  Is it not read?  Where does deletion first appear?  I think there's a hidden array of strains that may be causing this.

**Comment by trixr4kdz** [comment]
After revisiting this problem yet again, the actual root cause of the problem is ... LINE 6 OF THE FORWARD SIMULATION ROUTINE (which we basically extracted from the lse routine last semester):

![runforwardsimulation](https://cloud.githubusercontent.com/assets/8975300/19909945/55a65d68-a047-11e6-904a-81c1ccf74df5.PNG)

GRNstruct.microData was not cleared properly X-P. I'm wondering if just having ```GRNstruct = {}``` at the beginning of each runs would be good enough or would that be considered cheating, too? And if we ever need to save the data from the previous run we can just have something ```PreviousGRNstruct = GRNstruct```. In any case, I've written up tests to make sure that ```deletion``` from the previous run did not carry over. The fix is [here](https://github.com/trixr4kdz/GRNmap/blob/beta/matlab/readInputSheet.m#L20).

**Comment by bengfitzpatrick** [comment]
Since we create GRNStruct implicitly by assignment (through the construction of the filename to be read) in the main code, I guess we need to initialize it there.  I will defer to Dondi on best practices for this matter.

**Comment by dondi** [comment]
After hashing things out at the meeting, we've established that clearing out `GRNstruct` is a distinct operation from initializing its properties explicitly, and I'm OK with performing _both_ operations. The clear-out guarantees that there is absolutely _no_ leftover data from previous runs, and that does not release us from the obligation to explicitly initialize this at the beginning of a new run.

Another footnote is that this fix does not yet include the removal of globals from @jtorre39's work, so a merge task is coming up for when both threads are finished.
