### ISSUE TITLE
@bengfitzpatrick needs to update his computer lab to MATLAB 2014b

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#237]
@bengfitzpatrick needs to update his computer lab to MATLAB 2014b

**Comment by kdahlquist** [comment]
Related to this, a third computer has been added to my research lab.  It has Git and MATLAB 2014b installed, along with the compiler package and various toolboxes.  Let me know if there is additional software you need on it.  Login using your student account/domain.

**Comment by kdahlquist** [comment]
@bengfitzpatrick should e-mail Peter Alison directly, cc'ing Michelle Yeung.  Peter can arrange for getting administrator rights to the machines.

@kdahlquist will e-mail @bengfitzpatrick with the list of students, IDs, and e-mail addresses for the students who need card-key access to the lab.

**Comment by bengfitzpatrick** [comment]
Peter Alison solved the problem. All computers in 2752 are now equipped with 2014b.  Closing.
