### ISSUE TITLE
Re-run "sixteen_tests" to get output workbooks

### ISSUE THREAD

**Issue by jtorre39** [kdahlquist/GRNmap#241]
In the tests located in the "sixteen_tests" folder there seems to be an extra row in the optimization_parameters sheet titled "deletion" which looking through past issues is an entry we no longer require in the input sheet. 

Solution would be to go through and manually delete the deletion rows from the tests.

**Comment by kdahlquist** [comment]
I think we mentioned last week at the meeting that in 2015, we revamped the formatting of the input workbook.  If there are any holdovers from the previous format, we need to fix that so all the test files are clean and reflective of our new and finalized format.  Good catch.

**Comment by kdahlquist** [comment]
I'm elevating this as a priority 0 because we should fix these things as we notice them.

**Comment by bklein7** [comment]
@Nwilli31 and I are working on creating model input sheets for 5 database-derived networks #245 . It would be helpful if @jtorre39 or @cazinge could share an input sheet that they successfully ran through GRNmap for comparison.

**Comment by dondi** [comment]
Merged https://github.com/kdahlquist/GRNmap/pull/247 after resolving conflicts in lse.m

**Comment by bklein7** [comment]
While completing issue #245, I ran into two further issues with input sheet formatting in the "sixteen_tests" folder. These errors are as follows:
1. A row titled "Sheet" is present in the optimization_parameters sheet that no longer conforms to proper input sheet format. This row needs to be deleted.
2. Cell A1 in the network and network_weights sheets reads "targets/regulators". It should read "cols regulators/rows targets".
3. This is a more minor concern, but a wide range of font styles and sizes are present in the test input sheets. These will be homogenized to the font Arial 10.

**Comment by kdahlquist** [comment]
I'll add that @bklein7 is making these changes on the beta branch.

**Comment by bklein7** [comment]
The changes outlined above have been made in all files located within the "sixteen_tests" folder on the beta branch.

**Comment by kdahlquist** [comment]
The 16 tests input workbooks should be run to get new output workbooks so that they are completely up-to-date with changes to GRNmap.

**Comment by kdahlquist** [comment]
The inputs should be run off of the beta branch to be up to date with the coding team changes.

**Comment by bklein7** [comment]
I ran the 16 test input workbooks through GRNmap (beta) to generate the new output workbooks. Upon comparing these new output workbooks to the ones currently uploaded to the beta branch, I noticed one small discrepancy. The MSE values output in the optimization_diagnostics worksheet are now different for both strains. For wt, all MSE values have decreased by an order of magnitude (i.e. divided by 10). For dcin5, the MSE values are rather dissimilar across the board, with no obvious pattern defining the differences. Also of note is that the cin5 MSE values for the dcin5 strain are consistently reported as 0 in the new output sheets (I am not sure if this is intentional).

If the above discrepancies are all expected, I will move forward and upload the new output sheets to the sixteen tests folder.

**Comment by kdahlquist** [comment]
@bklein7 we need to look into your test results some more.  Would you attach them to a comment on this issue? (thus avoiding posting them to the repository before we make a decision on them).

**Comment by bklein7** [comment]
Here are the output workbooks:
- [4-genes_6-edges_artificial-data_MM_estimation_fixP-0_graph_output.xlsx](https://github.com/kdahlquist/GRNmap/files/634686/4-genes_6-edges_artificial-data_MM_estimation_fixP-0_graph_output.xlsx)
- [4-genes_6-edges_artificial-data_MM_estimation_fixP-0_no-graph_output.xlsx](https://github.com/kdahlquist/GRNmap/files/634691/4-genes_6-edges_artificial-data_MM_estimation_fixP-0_no-graph_output.xlsx)
- [4-genes_6-edges_artificial-data_MM_estimation_fixP-1_graph_output.xlsx](https://github.com/kdahlquist/GRNmap/files/634688/4-genes_6-edges_artificial-data_MM_estimation_fixP-1_graph_output.xlsx)
- [4-genes_6-edges_artificial-data_MM_estimation_fixP-1_no-graph_output.xlsx](https://github.com/kdahlquist/GRNmap/files/634689/4-genes_6-edges_artificial-data_MM_estimation_fixP-1_no-graph_output.xlsx)
- [4-genes_6-edges_artificial-data_MM_forward_graph_output.xlsx](https://github.com/kdahlquist/GRNmap/files/634690/4-genes_6-edges_artificial-data_MM_forward_graph_output.xlsx)
- [4-genes_6-edges_artificial-data_MM_forward_no-graph_output.xlsx](https://github.com/kdahlquist/GRNmap/files/634692/4-genes_6-edges_artificial-data_MM_forward_no-graph_output.xlsx)
- [4-genes_6-edges_artificial-data_Sigmoidal_estimation_fixb-0_fixP-0_graph_output.xlsx](https://github.com/kdahlquist/GRNmap/files/634687/4-genes_6-edges_artificial-data_Sigmoidal_estimation_fixb-0_fixP-0_graph_output.xlsx)
- [4-genes_6-edges_artificial-data_Sigmoidal_estimation_fixb-0_fixP-0_no-graph_output.xlsx](https://github.com/kdahlquist/GRNmap/files/634693/4-genes_6-edges_artificial-data_Sigmoidal_estimation_fixb-0_fixP-0_no-graph_output.xlsx)
- [4-genes_6-edges_artificial-data_Sigmoidal_estimation_fixb-0_fixP-1_graph_output.xlsx](https://github.com/kdahlquist/GRNmap/files/634697/4-genes_6-edges_artificial-data_Sigmoidal_estimation_fixb-0_fixP-1_graph_output.xlsx)
- [4-genes_6-edges_artificial-data_Sigmoidal_estimation_fixb-0_fixP-1_no-graph_output.xlsx](https://github.com/kdahlquist/GRNmap/files/634696/4-genes_6-edges_artificial-data_Sigmoidal_estimation_fixb-0_fixP-1_no-graph_output.xlsx)
- [4-genes_6-edges_artificial-data_Sigmoidal_estimation_fixb-1_fixP-0_graph_output.xlsx](https://github.com/kdahlquist/GRNmap/files/634698/4-genes_6-edges_artificial-data_Sigmoidal_estimation_fixb-1_fixP-0_graph_output.xlsx)
- [4-genes_6-edges_artificial-data_Sigmoidal_estimation_fixb-1_fixP-0_no-graph_output.xlsx](https://github.com/kdahlquist/GRNmap/files/634694/4-genes_6-edges_artificial-data_Sigmoidal_estimation_fixb-1_fixP-0_no-graph_output.xlsx)
- [4-genes_6-edges_artificial-data_Sigmoidal_estimation_fixb-1_fixP-1_graph_output.xlsx](https://github.com/kdahlquist/GRNmap/files/634695/4-genes_6-edges_artificial-data_Sigmoidal_estimation_fixb-1_fixP-1_graph_output.xlsx)
- [4-genes_6-edges_artificial-data_Sigmoidal_estimation_fixb-1_fixP-1_no-graph_output.xlsx](https://github.com/kdahlquist/GRNmap/files/634699/4-genes_6-edges_artificial-data_Sigmoidal_estimation_fixb-1_fixP-1_no-graph_output.xlsx)
- [4-genes_6-edges_artificial-data_Sigmoidal_forward_graph_output.xlsx](https://github.com/kdahlquist/GRNmap/files/634700/4-genes_6-edges_artificial-data_Sigmoidal_forward_graph_output.xlsx)
- [4-genes_6-edges_artificial-data_Sigmoidal_forward_no-graph_output.xlsx](https://github.com/kdahlquist/GRNmap/files/634701/4-genes_6-edges_artificial-data_Sigmoidal_forward_no-graph_output.xlsx)

**Comment by dondi** [comment]
Reverting to priority 1 so that the dev team can focus on LSE test coverage leading to LSE refactoring to handle missing data.

**Comment by kdahlquist** [comment]
@cazinge and @jtorre39 read through the comment thread on this issue to follow what happened.  These output workbooks will have had the bug from #289, so will need to be redone.

**Comment by jtorre39** [comment]
Are we going to eventually recreate these 16 outputs after we fix the bug?

**Comment by kdahlquist** [comment]
I think we should, but it is something that can be done at anytime.  I think it's a good idea to have a set of test input and output workbooks as actual files and these were created with that originally in mind.

**Comment by kdahlquist** [comment]
OK.  I'm going to backlog this issue then.
