### ISSUE TITLE
Unused variable t in general_network_dynamics_sigmoid and general_network_network_dynamics_mm

### ISSUE THREAD

**Issue by jtorre39** [kdahlquist/GRNmap#248]
On line 1 the parameter t that is passed into the function general_network_dynamics_sigmoid seems to be unused throughout the entire function. 

This also seems to be the case in the general_network_dynamics_mm function.

**Comment by bengfitzpatrick** [comment]
the format of the calling sequence of those two functions is governed by matlab's ODE45 routine.  ODE45 accepts the function as an input, and the function has to have a particular calling structure.

**Comment by bengfitzpatrick** [comment]
i consider this resolved and will close.
