### ISSUE TITLE
Jekyll Conversion Post-Mortem

### ISSUE THREAD

**Issue by cazinge** [kdahlquist/GRNmap#254]
I've merged the Jekyll change to the live website under this repo, but there are still some tasks to be looked into for a later date.
- [ ] Fixing the People Page Portrait on the sidebar.
- [x] Adding the Code of Conduct to the site.
- [ ] Fixing the Download links and minor upkeep.
- [ ] Removing unused assets.
- [ ] Streamlining the site to use a blog based format in order to make updating the site automatic

Future revisions to the site can be added here as well to provide a jumping off point for developers wanting to add to / revise the site.

**Comment by kdahlquist** [comment]
One other item.  There used to be a statement in the footer that said something like (I don't remember the exact wording):

"The GRNmap code and executable has been downloaded xxx times."

**Comment by kdahlquist** [comment]
I added the code of conduct to the About page and re-ordered the Privacy section to just above the code of conduct.

**Comment by kdahlquist** [comment]
Backlogging this issue.
