### ISSUE TITLE
Implementation of a banner + cookie for Privacy Statement

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#256]
Now that the conversion to Jekyll has been performed, we need to implement the banner + cookie for the Privacy statement, like has been done with GRNsight.

**Comment by kdahlquist** [comment]
If @jtorre39 and @cazinge need a break from other issues, this needs to be done like it has been for GRNsight.

**Comment by kdahlquist** [comment]
This is also a priority 0 for @johnllopez616.

**Comment by johnllopez616** [comment]
The banner is up :) Ready for review!

**Comment by kdahlquist** [comment]
This looks good!  A couple of notes:

- Can you make one minor change to the wording, changing _uploads_ to _downloads_?  For GRNsight, we are counting file uploads, but for GRNmap, we are counting file downloads.
- We have a special "review requested" label to tag the issue.  So when it is ready to review, you can add this label and assign the issue to me (or whoever needs to review it).
- However, in this instance, once you fix the wording, you can go ahead and close the issue; I won't need to review it again.

**Comment by johnllopez616** [comment]
Made the change!
