### ISSUE TITLE
Error when running 21-gene network then 4-gene network

### ISSUE THREAD

**Issue by trixr4kdz** [kdahlquist/GRNmap#264]
Here is the screenshot of the error when I ran the 21-gene network then the 4-gene network.

![error-when-running-big-network-then-smaller-network](https://cloud.githubusercontent.com/assets/8975300/19623734/e2a5dd9c-988b-11e6-8fbe-29431720cb18.PNG)

I put back the change that I made with removing the 'microData' field from GRNstruct since we didn't run the test and it didn't fix the problem (Forgive me Uncle Bob-Dondi :-P)

**Comment by bengfitzpatrick** [comment]
Okay, so this problem is arising from the dimension of W, because zz is an input variable to the function. The code version I have handy declares W to be zeros(size(adjacency_mat)), so adjacency_mat is not being properly initialized.  That's the place to start.

**Comment by trixr4kdz** [comment]
This problem has been solved with the pre-allocation of arrays in issue #231. I will be closing this issue now.
