### ISSUE TITLE
Failure to Receive Output .xlsx after running GRNmap

### ISSUE THREAD

**Issue by Nwilli31** [kdahlquist/GRNmap#271]
I ran GRNmap today, 02 Nov. 2016, on boulardii 2 in Dr. Dahlquist's lab. The file I uploaded to be run on GRNmap was not saved in the same folder as the matlab scripts. After its completion, I received all 16 images with their data points and model generated dynamics, but did not receive an output .xlsx file or .m nor an optimization/iteration count image. I am rerunning the model with all the information in the same folder to see if I get the same result.

This is the error from MATLAB:
Error using copyfile
No matching files were found.

Error in output (line 31)
copyfile(GRNstruct.inputFile, output_file, 'f');

Error in GRNmodel (line 29)
    GRNstruct = output(GRNstruct);

**Comment by bengfitzpatrick** [comment]
check that you have write permission for that folder.

**Comment by Nwilli31** [comment]
I will look into that issue when I come back into the lab. I reran the model with the excel input sheet saved in the same folder as the MATLAB files on the same computer.

**Comment by kdahlquist** [comment]
Since @Nwilli31 was able to re-run this with no problems, I am going to close this.  If we see it again, we will re-open the issue.
