### ISSUE TITLE
Scheduling Research for Spring 2017 semester

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#272]
It's time to start thinking about scheduling research next semester, both our coding/data analysis team meetings and the 4-hour time slots that you will work.

I don't quite have information about what time we will be able to schedule our research meeting, but I can tell you when it will *not* be:
Monday 1:10-5:00 (@kdahlquist teaching)
Tuesday 9:40-10:55 (@kdahlquist, @bengfitzpatrick, @dondi teaching)
Tuesday 11:30-12:45 (@kdahlquist department meetings, @bengfitzpatrick teaching)
Tuesday 4:20-5:35 (@dondi teaching; applies to coding meeting only)
Wednesday 1:10-5:00 (@kdahlquist teaching)
Thursday 9:40-10:55 (@kdahlquist, @bengfitzpatrick, @dondi teaching)
Thursday 11:30-12:45 (@benfitzpatrick teaching)
Thursday 4:20-5:35 (@dondi teaching; applies to coding meeting only)

I will be scheduling my wet lab students from 1:00-5:00 on Thursday afternoons. This doesn't preclude a meeting during that time, but it may mean that I will have to drop out of the meetings from time to time if we have an intense experiment going on in the lab.

For the data analysis team, @Nwilli31 has already arranged her schedule so that she can work her 4 hours on Thursday afternoons when I am available; it would be great if @khorstmann, @bklein7, and @maggie-oneil could do so as well. If it is not possible to schedule Thursday afternoon research, then you should at least coordinate with each other so that you can find a common time in your partnerships.  We are seeing this semester that it is helpful if I can be available during the work period to answer questions.

The coding team should likewise find a common time in their schedules where they can work together.

**Comment by kdahlquist** [comment]
Data analysis team should look at each other's schedules and what is posted for @kdahlquist and @bengfitzpatrick above to figure out a time for the research meeting.

**Comment by kdahlquist** [comment]
It looks like a potential time for the data analysis team meeting would be 4:00-5:00 on Thursdays.  Would @bengfitzpatrick , and the data analysis team members please confirm their availability at this time?

**Comment by kdahlquist** [comment]
It looks like a potential time for the coding team meeting for Spring is exactly the same time as the Fall, Wednesdays 11:30-12:30.  Would the coding team, @dondi and @bengfitzpatrick please confirm their availability at this time?

**Comment by dondi** [comment]
That slot is ok for me.

**Comment by trixr4kdz** [comment]
That slot also works for me.

@cazinge @jtorre39 work-wise, I will be available: MW 11:30am - 4pm, TR 1pm - 5pm, and anytime on Friday

**Comment by jtorre39** [comment]
I am free after 4:10 on all days. Friday I am free after 10:10 am as I only have one class on Friday.

**Comment by kdahlquist** [comment]
Happy New Year!  

The coding team will have its first meeting on Wednesday the 11th at 11:30.  All meetings will take place in LSB 331, which is the conference room on the third floor on the North side of the building. 

The data analysis team will have its first meeting on Thursday the 12th at 4:00, also in LSB 331.

See you there!

**Comment by kdahlquist** [comment]
Coding team is meeting on Fridays.

**Comment by jtorre39** [comment]
To that note we've settled on Fridays 11:00 AM - 3:00 PM for a 4 hour block. @bengfitzpatrick requested that we let him know of this in case of potential scheduling.

**Comment by kdahlquist** [comment]
Since this is settled, closing.
