### ISSUE TITLE
Output Graph Analysis of Model Runs for 5, "15"-Gene Networks

### ISSUE THREAD

**Issue by bklein7** [kdahlquist/GRNmap#275]
The transcription factor output estimation graphs generated in #265 will be further analyzed per the guidelines specified during the Data Analysis Team meeting on Monday, November 7th:

1. Display within-strain ANOVA values for each transcription factor on their respective output estimation graphs. 

2. Determine if there is a trend between within-strain ANOVA values and goodness-of-fit for the transcription factor output estimations.

3. Create graphics that display all 14-16 updated transcription factor output estimation graphs for each of the individual networks.

**Comment by Nwilli31** [comment]
@kdahlquist is there a specific location (OWW or Github repository) to find the within-strain ANOVA values for each transcription factor? Or would I have to run through the statistical analysis protocol again?

**Comment by kdahlquist** [comment]
I'm posting the ANOVA results to a directory in the DahlquistLab repository here:

https://github.com/kdahlquist/DahlquistLab/tree/master/data/within-strain_ANOVA_results

**Comment by kdahlquist** [comment]
OK, results are posted for wt, dCIN5, dGLN3, dHAP4, dHMO1, dZAP1.  Can't do dSWI4 because it only has 4 timepoints and the script is expecting 5.  I'll need to talk to @bengfitzpatrick about that.

In these files the column "B&H comps" has the Benjamini and Hochberg corrected p value.

**Comment by bklein7** [comment]
I compiled the within strain ANOVA B&H p-values for each of the 6 strains in the wild type network in an [excel file](https://github.com/kdahlquist/DahlquistLab/blob/master/data/15-gene_networks_analysis/Output-Graph-Analysis_BK20161116.xlsx). I then copied these values over into the testing results PowerPoint from #265 and posted this updated version of the presentation [here](https://github.com/kdahlquist/DahlquistLab/blob/master/documents/NEW_BK_GRNmap_Testing_network_presentation-all-strains_20161030.pptx). There are sheets for each of the 5 networks in the excel file if @Nwilli31 would like to continue working with this issue this week.

**Comment by kdahlquist** [comment]
Item 2 on list at top of this issue is now superseded by #315, so closing this one.
