### ISSUE TITLE
Model runs with Random Networks

### ISSUE THREAD

**Issue by bklein7** [kdahlquist/GRNmap#276]
After establishing a consistent protocol for the analysis of model run data, the "true networks" modeled in #265 will be compared to random networks.

To do this, the gene lists from each of the 5 database-derived networks will be used to generate 10 equivalent networks with randomly assigned connections using the R script from #223. Model runs will then be performed using each of these random networks. The random network models will be compared to the "true network" models to determine if either are superior.

If the "true network" models are in fact better, this will pave the way for model inference.

**Comment by kdahlquist** [comment]
For now, we are focusing on the "dHAP4" database-derived network.  As of this week, @Nwilli31 re-ran the random networks #316, so this issue is closable now.
