### ISSUE TITLE
Identify Common Edges in Weighted "15"-Gene Networks

### ISSUE THREAD

**Issue by bklein7** [kdahlquist/GRNmap#279]
During the Data Analysis Team meeting on Monday, November 7, @bengfitzpatrick and @kdahlquist pointed out various regulatory relationships that were highly conserved among all 5 weighted "15"-gene networks asses in #265. 

All edges that are maintained in each of the 5 weighted networks should be documented should be documented. Further, the raw magnitudes output for these regulatory relationships should be recorded and compared.

**Comment by kdahlquist** [comment]
This has been completed by @bklein7 in conjunction with #315, so closing this one.
