### ISSUE TITLE
All input sheets must be copied over to the output spreadsheet

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#28]
All worksheets from the input file for the model need to be copied over to the output spreadsheet.  In other words, the output file should contain all of the same sheets that the input file did plus the additional sheets that are calculated.

**Comment by juansc** [comment]
As of now the beta code copies over the entire input workbook and then appends the other sheets that are found in the output sheet.

**Comment by kdahlquist** [comment]
@bengfitzpatrick saw that there may be duplicated sheets in the output sheet, so we need to look at this further and make sure that this isn't happening.  We want all sheets from the input spreadsheet to be in the output, but not to duplicate them.

**Comment by kdahlquist** [comment]
Output spreadsheet should include sheets:
* all the input workbook sheets
* all the strain optimized expression
* a sheet for each parameter that is being estimated (w, P, b)  If it's not being estimated, do not make another copy since it was already copied over from input file.
* this should work whether the optimization or the forward simulation only was run

**Comment by juansc** [comment]
Done. Please review.

**Comment by kdahlquist** [comment]
verified that this works with the beta code as of 2015-03-25 with the following input sheet "Input_21_Gene_Network_Sigmoid_Model_Estimate_WTCIN5.xlsx" that I copied from Natalie from 2014-11-13. Will need to do further exhaustive testing with all possible choices of how to run (MM-Sigmoidal, fixP, fixB, etc.), but we can close this for now.
