### ISSUE TITLE
Identify Regulatory Motifs in Weighted Networks

### ISSUE THREAD

**Issue by bklein7** [kdahlquist/GRNmap#280]
During the Data Analysis Team meeting on Monday, November 7, @kdahlquist suggested that the five weighted networks generated in #265 could be broken down into regulatory motifs and compared in this way.

Although there are an abundance of regulatory motifs that exist, highly conserved regulatory relationships identified in #279 could be used to constructed conserved motifs.

**Comment by kdahlquist** [comment]
I'm going to mark this as "backlog" and close it for now because there are several other things we need to do before returning to this one.
