### ISSUE TITLE
Create a "28"-Gene Network Based on the 6, "15"-Gene Networks

### ISSUE THREAD

**Issue by bklein7** [kdahlquist/GRNmap#281]
During the Data Analysis Team meeting on Monday, November 7, @bengfitzpatrick and @kdahlquist suggested that a giant "28"-gene network encompassing all genes involved in the 5 "15"-gene networks should be created. Such a network could give us a reference point to use and perhaps even be used for hypothesis testing.

A list of the genes necessary to create this network can be found in the last worksheet of [this Excel file](https://github.com/kdahlquist/DahlquistLab/blob/master/data/GRNmap_input_workbooks/GRN_Gene_Lists.xlsx).

**Comment by kdahlquist** [comment]
@bklein7 is close to having done this after compiling the weight data for the 6 db-derived networks.  He could easily make an unweighted SIF file from that and create the visualization of the unweighted network in GRNsight.  I don't think it will be a fair comparison, though, to run this large of a network in GRNmap itself, although the visualization might be useful.

**Comment by kdahlquist** [comment]
Labeling this as "backlog" and closing since we won't be doing this in the Spring 2017 semester.
