### ISSUE TITLE
Coding team tasks for the week of 11/16, 11/23, 11/29

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#286]
Triple-team (swarm) on #158.

**Comment by trixr4kdz** [comment]
Work for this week consisted of creating tests for the compressMissingData and removeNaNs (now to be called convertToNestedStructure) and some discussion on the final structure we want to accomplish at the end of this issue based on the comments from 2 weeks ago.

**Comment by cazinge** [comment]
Our work thus far on #158 can be seen in pull request #294 for the purpose of reviewing the code during the meeting. We've created a foundation to write comprehensive tests off of and split the duties into the functions @trixr4kdz outlined above.

**Comment by kdahlquist** [comment]
For replicate timepoints where the entire column is empty, we should alert the user to fix their input workbook.

The milestone for the end of the semester is to merge this with beta (even though it won't function with the LSE part of the code).

**Comment by kdahlquist** [comment]
Meet in LSB 118 as usual on 12/7.

**Comment by trixr4kdz** [comment]
The Matlab licenses for the computers in the Numerical Analysis lab (the room across @bengfitzpatrick's office) have expired. I'm just gonna write it here so that we can maybe renew the licenses before next semester begins. For now, the GRNmap coding crew will work in the PC lab in UHall.

**Comment by trixr4kdz** [comment]
The changes on the different forks have been merged and compressMissingData is practically finished. 

Right now, convertToNestedStructure is the main function that needs to be finished, and will probably have to be done in the spring. The current beta is still at a functional state since we have not been calling the compressMissingData function.

**Comment by jtorre39** [comment]
I wrote two test cases to test various configurations for our convertToNestedData function and submitted a pull request.

**Comment by kdahlquist** [comment]
closing.
