### ISSUE TITLE
TriBeta Holiday Ornament Contest

### ISSUE THREAD

**Issue by Nwilli31** [kdahlquist/GRNmap#287]
Hi all!

TriBeta is having a holiday ornament contest. BIO 1 & 2 sections, upper-division labs, and research labs are invited to submit one. The ornament is due **Monday, Nov. 28** to **John Kaufman in LSB 101**
Winners will be chosen based on:
1) Most beautiful ornament, 2) Funniest ornament, and 3) Best Bio-themed ornament

Prize: Donut Part for winning classes (week of 12/5)
Winners announced at TriBeta Cookie Decorating Party, Fri. 12/2 from 4 - 6 pm (LSB Terrace, 2nd floor)

The entire Dahlquist lab (GRNmap, GRNsight, and wet lab) will be submitting one ornament. See [GRNsight #352](https://github.com/dondi/GRNsight/issues/352) , for GRNsight thread.

Please suggest ideas here! Creativity knows no limits - no idea is a stupid idea.

**Comment by khorstmann** [comment]
It seemed like everyone was really busy, so I just grabbed the ornament last night and quickly decorated it with some GrnSight graphics. 
I am really not a crafty person and it is by far not the most beautiful thing I have ever seen, so apologies, but just wanted to turn it in and help out everyones schedule. Hope thats ok!

**Comment by kdahlquist** [comment]
Thanks @khorstmann!
