### ISSUE TITLE
10 Simple Rules for Taking Advantage of Git and GitHub

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#299]
See this article on [10 Simple Rules for Taking Advantage of Git and GitHub](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004947) published in PLoS Computational Biology.  How many are we following?

**Comment by kdahlquist** [comment]
Please check off your name after you have read the article; please make any comments you have about it on this issue.

- [ ] @cazinge 
- [ ] @jtorre39 
- [ ] @trixr4kdz 
- [ ] @Nwilli31 
- [ ] @bklein7 
- [ ] @maggie-oneil 
- [ ] @khorstmann

**Comment by jtorre39** [comment]
To me it seem we follow most rules that are applicable to our code base.

**Comment by trixr4kdz** [comment]
I agree with @jtorre39 that we are following most of the points listed in the article.

Some interesting/noteworthy points:
- There is a separate storage for files larger than 50 MB called Git LFS (Large File Storage)
- Apparently, it's ideal to have a README, LICENSE, and CITATION files in our repo according to the article. The only one we don't have is the CITATION, which is used for instructing users on how to credit us.
- We are still trying to look into continuous integration with GitHub, but there are other issues that need immediate concern so it seems very unlikely that we can include it in the near future. The article recommends Travis CI for integration and CodeCov for coverage but neither support Matlab.

**Comment by kdahlquist** [comment]
Opened new issue #304 for Zenodo so we can get a DOI for GRNmap.

I forgot to explicitly tell the data analysis team about this issue.  The top priority for the data analysis team is posters for Saturday, but we'll hit this one next week.
