### ISSUE TITLE
Create activity diagram for GRNmap

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#30]
Create Use Case diagram and State Diagram for GRNmap

**Comment by dondi** [comment]
What is currently labeled a state diagram is actually an *activity diagram* in current terminology (known as *flowchart* previously). We should rename the file accordingly. For reference, search for "uml activity diagram" on the web.

**Comment by dondi** [comment]
Some specific items:
* Clarify that the diagram on the left is an overview
* Indicate individual function via bounding boxes/partitions, but still connect across to show how they interact
* Indicate the information that goes in and out of each self-contained function (specifically geared toward unit tests)
* For publicly visible variables, indicate their names; provide a short blurb of what they hold

**Comment by juansc** [comment]
Will make the overview section horizontal and have the functions dangle down below their corresponding boxes.

**Comment by kdahlquist** [comment]
The changes that @juansc described in his previous comment were made on the LMU symposium poster, but not on the main "GRNmap Activity Diagram.pdf" document in the Documents folder.

I am reassigning this to @trixr4kdz to complete tasks in bullet points 3 and 4 of @dondi 's Jan 28 comment.

**Comment by trixr4kdz** [comment]
@dondi for items 3 and 4 in your Jan 28 comment, what would be the best way to put the information in the activity diagram? I was thinking that putting more information in the diagram would make it too crowded. The updated activity diagram that Juan made is in the beta branch under "documents" in case you want to see it. I've started documenting the public variables for each of the functions we use in this openwetware page: http://openwetware.org/wiki/Trixie_Anne_Roque:_Electronic_Lab_Notebook#June_1.2C_2015_.28Monday.29

**Comment by kdahlquist** [comment]
@trixr4kdz reported on this in the 6/10/15 lab meeting.  She is working on updating and organizing the LSE portion.  

@bengfitzpatrick noted that in the future, we should refactor the code to separate out a "statistics" module to compute the average, standard deviation, and ANOVA p values ( #73 ), which is now living in the readInput function.

@trixr4kdz made a list of all global variables and whether they were still used or not.
* @bengfitzpatrick noted that the functions ode45 and fmincon have to use global variables because there is no way to use local ones for those two functions.
* "log2FC" was identified as a potential duplicate of another variable (@trixr4kdz could you update this with the correct names because I wasn't able to transcribe it at the meeting).

**Comment by kdahlquist** [comment]
@trixr4kdz should move her list of global variables to a wiki page on this GitHub project (it is on OpenWetWare right now).

**Comment by trixr4kdz** [comment]
I've uploaded the updated activity diagram to the GRNmap wiki (click [here](https://github.com/kdahlquist/GRNmap/wiki/Activity-Diagram-for-GRNmap) to view it).
I've also made a new wiki page for the list of the global variables [here](https://github.com/kdahlquist/GRNmap/wiki/GRNmap-Global-Variables-List).

**Comment by kdahlquist** [comment]
This is getting assigned to @cazinge so that he can update it and include it in the developer documentation he is working on.

**Comment by kdahlquist** [comment]
Let's take a look at this with the eye to closing.  I know that there is an updated diagram of some sort that has been appearing on posters.  Let's make sure that it's correct, the file is named appropriately, and it is stored in a logical place in the repository so we can close this out.

**Comment by dondi** [comment]
@jtorre39 will look through versions of activity diagram and delete old ones.  Look in repo and wiki.  Commit latest and greatest in the documents folder.

**Comment by kdahlquist** [comment]
@jtorre39: there is a file called "Updated GRNmap Activity Diagram SURP 2015.jpg" in the documents folder.  I'm assuming this is old and can be deleted, but want to check with you.  Please delete it since we have the newer one that you posted.

Question: on the wiki, will it always update to the version in the code (if it gets updated later, but keeps the same filename?)

Finally, the link at the bottom of the wiki page that says click here for better image is broken, do we need it?

**Comment by kdahlquist** [comment]
Took care of last comment. Closing now.
