### ISSUE TITLE
LMU Undergraduate Research Symposium on Saturday, March 25 

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#301]
The LMU Undergraduate Research Symposium on will be on Saturday, March 25.  All members of the group will present (in either pairs or threes).

Abstracts are due Feb. 10.

In the next couple of weeks, students will draft abstracts for review by @kdahlquist, @dondi and @bengfitzpatrick .

**Comment by trixr4kdz** [comment]
Drafts for the coding team abstracts can be located here: https://github.com/kdahlquist/GRNmap/wiki/2017-LMU-Symposium-Abstract-for-Roque,-Azinge,-and-Torres

**Comment by khorstmann** [comment]
For my talk, I was thinking of discussing HAP4's stats found via Gephi and comparing it to the random networks Natalie and Brandon have been working on. Abstract draft can be found in the repository or here: https://github.com/kdahlquist/GRNmap/tree/master/documents/abstracts

**Comment by bklein7** [comment]
Based on preliminary results from the edge weight analysis discussed in #315, I have drafted an updated abstract. This abstract can be found here:
https://github.com/kdahlquist/GRNmap/blob/master/documents/abstracts/Klein_Williams_LMU-URS-2017_Abstract.docx.

**Comment by Nwilli31** [comment]
Because I hope to present the material in conjecture with the data for my Honors Thesis, I hope to discuss the results of multiple generated random networks compared to a network derived from the lab's data. The abstract can be found here:  https://github.com/kdahlquist/GRNmap/blob/master/documents/abstracts/Williams_Abstract_URS_2017.docx

**Comment by kdahlquist** [comment]
updated link for abstract submission: http://mylmu.co1.qualtrics.com/SE/?SID=SV_4Sjyc2MtNPJgDpH

**Comment by kdahlquist** [comment]
@bklein7, I looked at the document you referenced and it looked identical to the one submitted for the SoCal Systems Biology conference--did you make changes or were you keeping it the same?

**Comment by kdahlquist** [comment]
@Nwilli31, I looked over your abstract and have the following feedback:
* There is a hard limit of 250 words; you have 263 now, so it will have to get shorter.
* This is largely based on your thesis prospectus which is written as what you will do in the future.  You need to shift into past tense because an abstract is about what you have already done (even though some of it will happen between now and the symposium next month.
* So, you need to be more concrete about the results you already have and also be a little more concrete about the results you expect to get.

**Comment by kdahlquist** [comment]
@khorstmann , I looked over your abstract and have the following feedback:
* I think you should use the title that you used for the SoCal Sytems Biology conference: Dynamical systems modeling and gene regulatory network structure analysis reveal's Hap4's role in regulating the response to cold shock in _Saccharomyces cerevisiae_
    * You can still talk about the random network with this title
    * It's not really a "Hap4" network; I think you were gone when we made these changes to the poster, but we renamed the networks just 1, 2, 3, etc.
    * It's not really a statistical analysis.  
* For this section:
    From this, we generated a candidate ^[database-derived] GRN of 15 genes and 28 edges and random network^[s] of similar size. <s>based on the Hap4 deletion strain family was created using Excel.</s> GRNmap was used to estimate the production rates, expression thresholds, and regulatory weights for these networks. Gephi was used to analyze the networks’ structures in terms of the node in- and out-degree<s>s</s>, eccentricity, and betweenness centrality. ^[We found that the random networks had a different degree distributions than the database-derived network.] Also, Hap4 had a different betweenness centrality value in the random networks, which affected the estimated parameter values, <s>From this analysis, Hap4’s role in the gene regulatory network  can be analyzed and compared to the randomly generated network to</s> help^[ing us to] further understand ^[its role in] the cold shock response in yeast.

I'm not sure of the word count on this, but we can do final tweaks on Thursday.

**Comment by kdahlquist** [comment]
@maggie-oneil, it would be good to have a draft of your abstract to review ahead of Thursday, so I can give you an initial round of feedback.

**Comment by kdahlquist** [comment]
I made some changes to the coding team's abstract on the wiki.  Some of the changes are still visible because I used <s>strikethrough</s> when cutting.  It's at 251 words in this version, but I didn't do any wordsmithing of the technical details, just the biological and what I noted in the comments I put on the page.  At the meeting tomorrow, would @dondi and @bengfitzpatrick please review and group-edit the final version for submission (I don't think I'll be making it to the meeting).

**Comment by maggie-oneil** [comment]
My apologies, I thought I responded to this earlier. 

Here is the link to my abstract for the symposium. [https://github.com/kdahlquist/GRNmap/blob/master/documents/abstracts/Horstmann_O-Neil_Southern-California-Systems-Biology_2017_abstract.docx](url)

**Comment by trixr4kdz** [comment]
Abstract for the coding team has been submitted.

**Comment by maggie-oneil** [comment]
Here is a draft version of my new abstract for the symposium

[https://github.com/kdahlquist/GRNmap/blob/master/documents/abstracts/ONeil_LMU_symposium_2017_Updated_draft.docx]

**Comment by maggie-oneil** [comment]
Here's the final version of my draft for the symposium:

https://github.com/kdahlquist/GRNmap/blob/master/documents/abstracts/ONeil_LMU_symposium_2017_Updated_finaldraft.docx

**Comment by bengfitzpatrick** [comment]
Maggie:

Thanks for the mods.  This is much better and very close.  I felt it ended a little too evasively, so I tried to make the punchline a little more specific, based on the data in your ppt. I left the previous version in place, just in case.  Make sure I've done the upper/lower cases correctly. 

Dr. Dahlquist:

if you can phrase the punchline better, please do so. I wasn't sure if I could refer to Brandon's abstract (which also noted interest in these three tfs), so I didn't.

**Comment by kdahlquist** [comment]
@bengfitzpatrick , the file you uploaded to the repo is a blank document.  I will proceed to look at @maggie-oneil 's other draft.  If you can re-upload your document before 12:30, I will be able to review both, but otherwise I'll go based off of what is in @maggie-oneil 's version.

**Comment by bengfitzpatrick** [comment]
reuploaded.  viewed successfully. should be fine now.

**Comment by kdahlquist** [comment]
I've merged @bengfitzpatrick's changes with mine and there is just one version on the repository now at:

https://github.com/kdahlquist/GRNmap/blob/master/documents/abstracts/ONeil_LMU_symposium_2017_Updated_finaldraft_USETHISONE.docx

@maggie-oneil, please go ahead and submit by 5:00 PM (ideally, sooner).

**Comment by kdahlquist** [comment]
Dropping this to a priority 0.5 until 2 weeks before the symposium when drafts of the posters will be reviewed and the first practice run of the talks will take place at that week's meetings (Wed 3/15, Thurs 3/16).

**Comment by kdahlquist** [comment]
This is a reminder to everyone that drafts of your talks and posters for the LMU Symposium are due at the next meeting after the break.

**Comment by kdahlquist** [comment]
Notes on Coding Team poster review from 3/15/17.

* In the UML diagram, need to insert box in readInputSheet that says "detect missing data".
* Need to remove box saying "initiate additional global variables".  For our documentation, remove it, for the poster, "X" it out.
* Add new box to lse to say "poplulate global variables" and "extract global variables"
* All GRNmap-related GoogleDocs need to be collected in a folder and shared with the entire team.  Sharing needs to be set for "edit" for the team and view for the general public.  The link to the doc needs to be in a prominent place so it can be accessed from the repo, like the ReadMe on the master branch.  Right now the document is on @trixr4kdz 's individual Google Account, it needs to be moved to the GRNmap google account.
* we're looking at the general_least_squares_error, working on the loop; but will not put on poster.  However, this needs to be updated for posterity.
* Data structure change
* References section to Dahlquist et al. (2015) paper
* need to put GRNmap URL prominantly 
* symbolize "cleaning up" global variables by scattered words being put neatly into boxes.
* References and acknowledgments section can be small.
* Background needs to explain GRNmap from the point of view of a user--why does someone want to use it? What types of data are input?  What comes out?
* Future work includes further refactoring, fixing bugs, and improving test coverage.  The Data analysis team is working on ways to analyze the model output that we would like to automate in the future.
* As soon as you have something for review, post a comment to this issue and point us to a link in the repo with the poster (in the poster folder under Documents on the master branch).

**Comment by bklein7** [comment]
The draft of my poster for the LMU Symposium can be found here: https://github.com/kdahlquist/GRNmap/blob/master/documents/posters/Klein-Williams_LMU-URS-2017-Poster_20170315.pptx.

The new graph statistics bar charts that were generated have been complied here: https://github.com/kdahlquist/DahlquistLab/blob/master/data/15-gene_networks_analysis/Graph-Statistics-Comparison_BK20170315.pptx.

**Comment by trixr4kdz** [comment]
The coding team has finished the draft of the poster based on what we discussed during our previous meeting. Here is the [link](https://github.com/kdahlquist/GRNmap/blob/master/documents/posters/Roque_Azinge_Torres_URS-2017-poster.pdf) to the one in the documents folder: It has also been shared with the mentors on Google Drive so that you can comment. 

Additionally, the figures that were originally in my Google Drive has been moved to the grnmap.lmu gmail account.

**Comment by kdahlquist** [comment]
Ok. Standby for some feedback, hopefully sometime this weekend.

**Comment by kdahlquist** [comment]
This comment is for @trixr4kdz, @cazinge, and @jtorre39 and is feedback on their poster draft.

* The title for the first section is "Running Simulations using GRNmap".  The word "simulation" refers to the forward part of running the model once the parameters have been estimated.  This title should be a little more specific: "Estimating Parameters and Running Forward Simulations with GRNmap"
* A picture is worth a thousand words.  This first section would be greatly improved by providing both a contextual figure, but also providing the equations, both the differential equation and the LSE that are discussed later in the poster.  I'm attaching two PowerPoint slides with this information to this comment so you can include them in your poster.  You need to explain that the parameters are being estimated from the expression data so the connection of why we need to pay special attention to it is clear.  In the section below, you also talk about strains.  You either need to introduce what you mean by that in the background or don't mention it in the section below.
[for-GRNmap-coding-team-poster.pptx](https://github.com/kdahlquist/GRNmap/files/855697/for-GRNmap-coding-team-poster.pptx)
* The screenshot of the input expression sheet should probably mirror the diagrams of the data structures shown below.  So, either you need to remove a gene from the screenshot (so there are three) or add to the figure below.
* The title for the next section should be "Improved Data Structure Allows for Missing Expression Values"
* The first bullet needs to be clear that we are not allowing missing data in _any_ worksheet, just the worksheets with the expression data.
* I already mentioned that you either need to introduce what you mean by strains or not mention it at all here.
* Third bullet should read: "When missing values are encountered, it causes an error which crashes the program."
* "by an index in the lower row of the matrix"
* Your last bullet point in that section says that you've simplified the data structure.  Actually, isn't it more complicated?  It would be easier to tell the user not to have missing data.  However, that is not realistic for biological data.  You needed to refactor the program to deal with the messiness of data from the real world.

I have to go to a meeting now.  I'll be back with more comments on the rest of the poster later today.

**Comment by kdahlquist** [comment]
More feedback for @trixr4kdz, @cazinge, and @jtorre39 on their poster.

* The title for your top-right panel should be "A Unified "GRNstruct" Data Structure Passes Data through the Multiple GRNmap Routines"
* In this section, you need to connect the idea that you created a new data structure, called the "GRNstruct" to store the data from the user input workbook described in your background section at the left.
* It seems that the figure legend and bullet point 2 need to be swapped.
* remember that GRNmap doesn't just do simulation, but estimation and simulation.  So for bullet point 1, "that conduct the estimation and forward simulation"; also, what do you mean by the results are displayed in a "user-friendly format"  do you mean the Excel sheet, the graphs?

* The section called "Localized Global Variable" should be titled "Code Refactored to Localize Global Variables"
* bullet 2 of this section should read "The holdover of values in the global variables caused bugs when users ran the model twice in a row."
* Draw the connection for the reader between the diagram in this section to the diagram in the section above and to the GRNstruct.

* For future work, can you include a statistic that reports how much test coverage we have now?
* For the last bullet in this section, "Add new features for data analysis requested by the GRNmap data analysis team members."

* In the links section, mention that it is available under an Open Source license.  Can you document how many total downloads of our software have been performed?  Can you look up the Google Analytics?  The readouts for that seem to be broken on the downloads page, but if you can look them up directly, that would be a nice thing to include on the poster.

* The citation is not complete for the Dahlquist et al. paper.  Please look it up in Google Scholar and use the APA citation format, along with the DOI that you have provided.

* For the Acknowledgments section, you do not need to acknowledge anyone that was a co-author on the Dahlquist et al. paper.  However, you do need to acknowledge Katrina Sherbina and Juan Carrillo!  The funding support needs to be relevant to the people actually listed as co-authors on the poster, so for example, a reference to K.S. (Katrina Sherbina) isn't necessary.  However, Trixie needs to acknowledge her SURP support.

Post a comment to this issue when a new version is ready to review.

**Comment by bklein7** [comment]
The updated draft of my LMU Research Symposium poster can be found here: https://github.com/kdahlquist/GRNmap/blob/master/documents/posters/Klein-Williams_LMU-URS-2017-Poster_20170315.pptx.

**Comment by maggie-oneil** [comment]
Forgot to include the link here when I posted last night, but the updated draft of my poster can be found here: 
https://github.com/kdahlquist/GRNmap/blob/master/documents/posters/ONeil_Undergraduate_Research_Symposium_2017_poster.pptx

**Comment by kdahlquist** [comment]
Reminder to everyone that your revised posters need to be reviewed tomorrow (Wednesday) so that they can be printed in time for Saturday.  The Biology Department is printing lots of posters and we need to be able to get ours in the queue.

Based on the preliminary schedule sent out to students, @anuvarsh and @NAnguiano are presenting in a session that starts at 11:00 AM and the rest of the group, @Nwilli31, @khorstmann, and Monica are presenting in a session from 1:30-3:00.

It looks like all the posters are in the session from 3:00-4:30.  Please be there to support your fellow lab members in their presentations/posters.

**Comment by trixr4kdz** [comment]
The updated poster for the coding team has been uploaded and can be viewed [here](https://github.com/kdahlquist/GRNmap/blob/master/documents/posters/Roque_Azinge_Torres_URS-2017-poster.pdf).

**Comment by Nwilli31** [comment]
My final presentation is up for review before submitting it for my LMU Undergraduate Symposium talk: https://github.com/kdahlquist/GRNmap/blob/master/documents/presentations/LMUURS17_NEW.pptx

**Comment by kdahlquist** [comment]
@Nwilli31, thanks for the notification.  I've been in lab all day and probably won't have a chance to review this.  I'm sure it's great.  Just to clarify, we are not submitting electronic copies of our slides/posters to the symposium, so all you need to do tomorrow is bring the presentation on a flash drive.

**Comment by kdahlquist** [comment]
Great work, everybody, at the symposium on Saturday.  For those who gave talks (@Nwilli31 , @khorstmann), please make sure that the final version of your slides has been uploaded to the repository.  For those who gave posters, that has already been done.

I'm going to close this now (and create separate issues for updating the web site).

For this week, we go back to working on the research project, so for those whose work sessions precede the meeting, please pick up where you left off before we stopped to work on the symposium stuff.
