### ISSUE TITLE
Start converting the current tests to assert the structure of our new data structure

### ISSUE THREAD

**Issue by trixr4kdz** [kdahlquist/GRNmap#311]
Because of the data structure overhaul, the tests we have at the moment need to be revised to accommodate the new structure.

**Comment by jtorre39** [comment]
![newtestparadigm](https://cloud.githubusercontent.com/assets/16827894/22524182/1ef46f80-e877-11e6-937f-cdbb1e59d63d.jpg)

This will be our workflow for working on the test suite.

**Comment by dondi** [comment]
Pre-existing tests with complete data have been migrated, but now new test cases that intentionally have missing data (e.g., corners, missing first, missing last) need to be created.

**Comment by kdahlquist** [comment]
Finished and ready for release.
