### ISSUE TITLE
Create a 0% release of current beta (v1.5), called v 1.6

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#312]
With the purpose of merging the current beta into master, we are going to do a 0% release with the new data structure, but without it being functional.  This will help us identify conflicts and issues and prevent an uglier merge later.

We need to follow the instructions on the wiki on how to do a release here: https://github.com/kdahlquist/GRNmap/wiki/How-To-Create-a-New-Release.  In addition, we need to incorporate Issue #216.  @kdahlquist will need to provide the readme and sample data for inclusion.

Again, because the MATLAB executable builder can't handle the third digit in semantic versioning, we need to call this relase 1.6.

**Comment by trixr4kdz** [comment]
A draft of release v1.6 is created with the GRNmap executable.

**Comment by dondi** [comment]
Draft release looks ready to go under the following conditions:
- Selected team members (likely @bengfitzpatrick, @kdahlquist, data analysis members) will download the draft release and test it just to ensure that there aren't any unexpected regressions. The draft release does not allow a download of the .zip that is in prep, so the dev team will need to make the _exact_ file available through other means, like Box or something else. (dev team to email the link)
- The draft release notes need to include links to the issues that the changes addressed (see prior release notes for examples)
- Upon validation of the .zip download, the release can be published and this issue can be closed.

**Comment by kdahlquist** [comment]
@trixr4kdz, I am running the executable you uploaded to Box, however there wasn't a zip of the code that goes with the release.  Ideally, I would run the executable, run it from code and compare both versions to the results of v1.4.4.  Is it fair to just run the code from Master at this point or has it already changed?  Please give clarification.

**Comment by kdahlquist** [comment]
Release of v1.8 supersedes this.
