### ISSUE TITLE
Standardize computer on which data analysis team models will be run, re-run networks as needed

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#316]
@bklein7 and @Nwilli31 need to standardize on one computer and run the six network families on it.  Output model data will potentially need to be replaced with these new runs, and the PowerPoint summaries updated accordingly.

We should also re-run the dHAP4 random networks that were used in the posters on the same computer and updated with the worksheets from the current dHAP4 network (i.e., redo the inputs by replacing the real network with the random one so we are sure we are comparing apples to apples).

**Comment by Nwilli31** [comment]
Monday afternoon, I reran the networks derived from dgln3, dhap4, and dzap1 on boulardii 2. I ran the wt and two dcin5 networks on that computer originally. In the Dahlquist Lab repository, I created a new folder with these new output sheets, using the same input workbooks as before. The files can be found [here](https://github.com/kdahlquist/DahlquistLab/tree/master/data/bouldardii2_GRNmap_outputs) in the Dahlquist Lab repository.

**Comment by kdahlquist** [comment]
Fantastic.  We can plug away at the random ones then in the next couple of weeks.

For easy reference, here is the link to the repo with the files:  https://github.com/kdahlquist/DahlquistLab/tree/master/data/bouldardii2_GRNmap_outputs

**Comment by Nwilli31** [comment]
I've rerun all of the random networks that Grace generated last year, inserting her adjacency matrices into the network and network weight sheets of Brandon's original file. The results can be found here:
https://github.com/kdahlquist/DahlquistLab/tree/master/data/bouldardii2_GRNmap_outputs/Random_network_intput_output

**Comment by kdahlquist** [comment]
OK, then this one is closable.  We'll discuss at the meeting next steps.
