### ISSUE TITLE
Broken links in readme

### ISSUE THREAD

**Issue by jtorre39** [kdahlquist/GRNmap#321]
Under "Release Notes" the "GRNmap About Page" link is broken. 

In addition under "Documentation" the "GRNmap Documentation Page" link is broken as well. 

It's a simple solution to correct the links the README.md file leads to but to make sure the links are corrected properly I've submitted this issue to bring it to attention.

**Comment by jtorre39** [comment]
The about page link was corrected and the documentation link had an extraneous .html within the links. I also noticed the two links were using http while other links were using https so I had the two links use https now as well. This was done in the beta branch.

The fix has been committed to beta pending approval so this issue may be closed. Also to note is the broken links are featured in the same exact way in master and need to be corrected but I'm hesitant to change master without approval.

**Comment by kdahlquist** [comment]
It's OK with me to go ahead and change the Master ReadMe.  Since this doesn't touch code, I'm OK for that branch to be directly modified (we have been adding stuff to the documents folder like this).

If you are going to do this, please double-check all the links in the ReadMe.  Thanks.

**Comment by jtorre39** [comment]
I fixed a remaining broken downloads link and double checked all the links. The issue will be closed.
