### ISSUE TITLE
Analyze MSE's for db-derived and random networks

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#326]
As discussed in the meeting, @Nwilli31 will focus attention on analyzing the MSE data for individual genes.  Moving the open questions from #315:

* What is the relationship of the MSE to the within-strain ANOVA p value for each gene.
    * does p < 0.05 give a better fit?
    * does p > 0.05 give a better fit?
    * is there no relationship?
* Are genes with no inputs modeled worse or better or no relationship?
    * use in-degree, out-degree, total-degree tables for this
* do genes with decreases in expression have a worse fit?
* Will need to generate additional expression plots that are less complicated than the ones automatically output by GRNmap.

**Comment by kdahlquist** [comment]
As discussed at the 2/23 meeting, trying to compare the actual expression plots to each other is very difficult and we need to focus on the numerical MSE data.

However, what we really need is the MSE/minMSE ratio for each gene in each strain, not just the MSE, for a fair comparison.

@bengfitzpatrick noted that the minMSE is gettable from the within-strain ANOVA computation.  The MATLAB script for that is found in the DahlquistLab repository here:

https://github.com/kdahlquist/DahlquistLab/blob/master/statistics/oneStrainMissingDataHandler.m

It wasn't clear whether @bengfitzpatrick or @Nwilli31 was going to work on getting the minMSE, but it needs to be done before forward progress can be made on this issue.

**Comment by Nwilli31** [comment]
I looked at the MATLAB script, but could not figure out how to calculate the minMSEs from the ANOVA data. I emailed @bengfitzpatrick about these computations.

I've added comparison files of  random networks 4 - 19 onto the MSE_pvalue file (https://github.com/kdahlquist/DahlquistLab/blob/master/data/15-gene_networks_analysis/pvalue_MSE_comparison.xlsx)

**Comment by kdahlquist** [comment]
@bengfitzpatrick sketched out on the board what the appropriate calculation will be to do this.
![20170302_165659](https://cloud.githubusercontent.com/assets/6463867/23539003/deff88b0-ff8c-11e6-8c74-4c99ab039ea5.jpg)

(you have to do them upside down!) :)

**Comment by Nwilli31** [comment]
I calculated the minMSE values and the MSE:minMSE ratio can be found on the pages of the networks that will be analyzed - db5, rand7, rand12, rand15, rand16, rand24, and rand31. It appears that there is no distinguishable relationship between MSE:minMSE value and p-value for better or worse fits.

The workbook with these comparisons can be found here in the DahlquistLab Repository: https://github.com/kdahlquist/DahlquistLab/blob/master/data/15-gene_networks_analysis/pvalue_MSE_comparison.xlsx

**Comment by kdahlquist** [comment]
As noted in #343, @Nwilli31 needs to create an Excel spreadsheet that is "plug-and-play" so that we can copy/paste data into it and get the MSE/minMSE ratios.  Having done this, then we need to complete:
- [ ] db1
- [ ] db2 
- [ ] db3 
- [ ] db4 
- [ ] db6
- [ ] rand7
- [ ] rand12
- [ ] rand15
- [ ] rand16
- [ ] rand24
- [ ] rand31
- [ ] the rest of the rand (only if time)

**Comment by Nwilli31** [comment]
I've uploaded these network's MSE:minMSE ratios files into their own separate folder. They can be found here: https://github.com/kdahlquist/DahlquistLab/tree/master/data/Spring2017/15-gene_networks_analysis/MSE_minMSE_analysis

**Comment by Nwilli31** [comment]
I have not yet done the other random network's MSE:minMSE ratios, but if I manage to find time by the end of the semester, I will post what I have done onto the repository. I will also leave detailed instructions on how I calculated the minMSE.

**Comment by Nwilli31** [comment]
I have left instructions on how to compute the minMSE value on my openwetware page: http://www.openwetware.org/wiki/Natalie_Williams:_Electronic_Notebook. It is under the heading of Week of March 4, 2017 for Thursday's work description.

**Comment by kdahlquist** [comment]
This is complete, @Nwilli31 is not going to do the rest of the randoms so that she can focus on finishing her thesis.
