### ISSUE TITLE
Finish generating 30 random networks based on db5 and run GRNmap on them

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#327]
@Nwilli31 has already generated 27 random networks based on db5; let's go ahead and round that up to 30.  They will all need to be run through GRNmap (and Gephi #325), but that is a background task while she works on issue #326.  Hold off on doing the GRNsight visualization on them until later because that is time-consuming and we will pick and choose which ones to look at.

**Comment by kdahlquist** [comment]
@Nwilli31 will you comment on this issue to let us know the status?

**Comment by Nwilli31** [comment]
Currently running Random Network 23. I have uploaded the most recently run random networks (13-22) onto the respository. All other output files to the DahlquistLab Repository: https://github.com/kdahlquist/DahlquistLab/tree/master/data/bouldardii2_GRNmap_outputs/Random_network_intput_output

**Comment by kdahlquist** [comment]
@Nwilli31 has three more to go.

However, @khorstmann noted that when she pulled random networks 4 and 5 to run the Gephi analysis, she saw that they were the same.  @Nwilli31 is tasked with checking all the input and output workbooks for the random networks to make sure that the input for the same network matches the output and that each random network is unique.

@Nwilli31 has also charted the LSE/minLSE ratios for the outputs that she has and has found that the average ratio is higher than db5, from which they were derived.

@Nwilli31 is also going to take the three networks with the highest LSE/minLSE ratio and the three networks with the lowest LSE/minLSE ratio and plug them into @bklein7's spreadsheet to generate the descriptive stats.  She will need to first run them through GRNsight to generate the SIF files.  Since the networks all have different edges, it will take a little time to concatenate the edges, but once that is done, the rest of it should be fairly straightforward.

**Comment by Nwilli31** [comment]
I looked over the random networks, and @khorstmann was correct. When I took random networks 1-10 from Grace's research last year, networks 4 & 5 were the same in her workbooks. I will generate another random network (random 31) to compensate for the identical networks.

**Comment by Nwilli31** [comment]
All the random networks & their input and output workbooks can be found in the DahlquistLab Repository: https://github.com/kdahlquist/DahlquistLab/tree/master/data/bouldardii2_GRNmap_outputs/Random_network_intput_output.

Further, I have used Brandon's spreadsheet to generate the descriptive stats of the 7 networks of interest (db5, random 15, 16, 24 for lowest ratio, and random 7, 12, and 31 for highest ratio). This file can also be found in the DahlquistLab Repository: https://github.com/kdahlquist/DahlquistLab/blob/master/data/15-gene_networks_analysis/Regulatory-Relationships_Six-Networks_NEW_db5.xlsx

**Comment by kdahlquist** [comment]
As noted by the comment by @Nwilli31 above, the model runs have been completed.  What remains of this task is compiling the data.
As noted on #343:
- [ ] @Nwilli31 has compiled the weight values using @bklein7's spreadsheet for the three best (rand15, rand16, rand24) and three worst (rand7, rand12, rand31) random networks, but we need to compile the data for all 30 of the random networks.
- [ ] We still need to compile the production rates and b values into a single spreadsheet
- [ ] compile expression plots into a PowerPoint; or at least making sure zipped .jpg's are in the repository

**Comment by Nwilli31** [comment]
I've uploaded the zip files for the random network expression plot figures, which can be found here: https://github.com/kdahlquist/DahlquistLab/tree/master/data/Spring2017/bouldardii2_GRNmap_inputs_outputs/GRNmap_db5-derived-random-network-1-through-31_input_output/Expression-plots_Random-network-1-through-31

**Comment by dondi** [comment]
Hi, I'm @dondi!

@kdahlquist says remember to logout!

**Comment by Nwilli31** [comment]
I've uploaded the zip files of the expression plots for db1 - db6 networks, which can be found here: https://github.com/kdahlquist/DahlquistLab/tree/master/data/Spring2017/bouldardii2_GRNmap_inputs_outputs/GRNmap_db1-through-db6_input_output/GRNmap_db1-through-db6_figures

**Comment by kdahlquist** [comment]
This is complete!  Closing.
