### ISSUE TITLE
Compute weighted in-, out-, and total-degree for db-derived networks

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#328]
Instead of using Gephi to compute weigted degree stats, we can easily do it in Excel by summing across the rows and columns of the "network_optimized_weights" sheet.  This is priority 0.5.

In Excel we can also compute the average, median, max, min of weights across the rows and columns to get the descriptive stats for all incoming and outgoing edges for a gene.

**Comment by kdahlquist** [comment]
Elevating this to priority 0 for @maggie-oneil.

**Comment by bklein7** [comment]
@maggie-oneil, let me know when these weighted values are uploaded to the repository so that I may access them.

**Comment by maggie-oneil** [comment]
Here is my excel sheet to show for today - should be close to being done 
[MO_Compiled_db6_Network_Weighted  .xlsx](https://github.com/kdahlquist/GRNmap/files/815456/MO_Compiled_db6_Network_Weighted.xlsx)

**Comment by kdahlquist** [comment]
Copied this over from #290 because I realized that I wrote it in the wrong issue.

@maggie-oneil, As discussed in the meeting, we are interested in the per gene statistics, not just the overall stats on the totality of the edge weights.

What we want to know is what is the sum and average of the in-degree weights (the rows) and the out-degree weights (the columns). You basically have this information already for the sum, you just need to organize it. For computing the average, we need to be careful and not include the zeros in the average, just the positive and negative numbers. You can probably tweak the Excel equation with an "if" statement to include just the non-zero weights in the computation.

Once you have that, please post the results to the repo and make a comment on the issue so @bklein7 knows where they are.

We are interested in this because we would hope to see a relationship where if a gene was up-regulated, the incoming weights would either sum or average (or both) to be positive, and conversely if the gene is down-regulated, the incoming weights would either sum or average to be negative.

We are also interested in knowing the relationship between these values and the MSE's for genes.

**Comment by kdahlquist** [comment]
I believe that this has been done and compiled by @maggie-oneil.  She should comment on this issue with the link to both the raw and complied data files and we can close this one.

**Comment by kdahlquist** [comment]
It's there, so closing.
