### ISSUE TITLE
Default open dialog to files of type xlsx instead of xls

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#33]
We should default the open dialog to files of type xlsx instead of xls for maximum compatibility with GRNsight.

**Comment by juansc** [comment]
I think we should allow the dialog box to display both .xls and .xlsx files. I say this because GRNmap works with both file formats. Additionally, if you wish to use an .xls file to run GRNmap you must click "All Files" in the dialog box, which shows not only the .xls file but all the .m files.

**Comment by kdahlquist** [comment]
The reason why we want to default to .xlsx is that GRNsight can only accept .xlsx files.  We want to default to the one that is compatible with GRNsight, even though .xls is still compatible with GRNmap.  The workflow is that once you run the model with GRNmap, you will want to visualize it with GRNsight.

**Comment by kdahlquist** [comment]
Verfied that this is happening and closing.
