### ISSUE TITLE
Write protocol for generating graph statistics with Gephi

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#335]
@khorstmann and @maggie-oneil are reminded to record in their lab notebooks the details of how they are computing the graph statistics with Gephi so that they don't waste time trying to figure it out again.  Recording this information is important for reproducible and repeatable research, i.e., documenting our work in preparation for publication.

Moreover, they are tasked with writing a general protocol for future students (who may be using Gephi for the first time) to use.  This is priority 0.5, to be completed immediately upon completion of the LMU Undergraduate Symposium preparations.

**Comment by kdahlquist** [comment]
This has now been elevated to a priority 0 as part of the wrap-up for the Spring 2017 semester.

**Comment by maggie-oneil** [comment]
The file has been created, and can be found on my openwetware page, linked directly here: http://www.openwetware.org/images/6/66/MO.GephiProtocol.pdf

**Comment by kdahlquist** [comment]
OK, I've moved the protocol into the DahlquistLab repository.  However, presumably you made it in Word, can I have the editable version as well?

**Comment by maggie-oneil** [comment]
The editable version can be found on my open wet ware page under the March 30th entry, and is also attached to this comment 
[MO.GephiProtocol (1).docx](https://github.com/kdahlquist/GRNmap/files/963071/MO.GephiProtocol.1.docx)

**Comment by kdahlquist** [comment]
captured and put in DahlquistLab repo, so closing.
