### ISSUE TITLE
Scheduling GRNmap meetings for Fall 2017

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#345]
Registration for Fall 2017 is just around the corner and we should start talking about when our GRNmap team meetings will be in the Fall.

Times that are off the table due to @kdahlquist's teaching and meeting schedule are:
Mondays 10:10-12:30
Tuesdays 11:30-12:30, 2:40-3:55
Wednesdays 10:10-12:30
Thursdays 2:40-3:55
Fridays 10:10-12:30

From what I see on the schedule of classes, @dondi is not available
Mondays 09:10 - 10:00 AM, 11:40 - 12:30 PM
Tuesdays 2:40-3:55 and 04:30 - 05:20 PM
Thursdays 2:40-3:55
Fridays, not available

@bengfitzpatrick is not available
Tuesdays 	09:45 - 11:00 AM, 11:30 - 12:45 PM
Thursdays 09:45 - 11:00 AM, 11:30 - 12:45 PM

Please chime in if I missed something.

**Comment by bklein7** [comment]
Based on my current course schedule for Fall 2017, I will not be available at the following times:

Mondays 9:10 - 11:10 AM
Tuesdays, not available
Wednesdays 9:10 - 11:10 AM
Thursdays 8:00 - 11:00 AM, 1:00AM-4:50PM
Fridays 9:10AM - 3:00PM

**Comment by maggie-oneil** [comment]
Based on my current schedule, I won't be available for the following:

Mondays 10;20am-12:30pm
Tuesdays 1:00pm-4:50pm
Wednesdays 10;20am-12:30pm
Thursdays 1:00pm-4:50pm
Fridays 10;20am-12:30pm

**Comment by maggie-oneil** [comment]
On Mondays and Wednesdays I will now not be available from 10:30am-12:30 pm, and from 2;20pm-3:50 pm

**Comment by kdahlquist** [comment]
Thanks for the update, but I want to hold off on trying to nail down a schedule until August.  You all will hear from me then.

**Comment by kdahlquist** [comment]
@dondi, @bengfitzpatrick, and I have reviewed your course schedules for Fall and propose the following meeting times:
- GRNmap data anaylysis:  Wednesdays at 1:30-2:15
- GRNmap coding: Wednesdays at 2:15-3:00

Location is TBA.  Please confirm that you are available to meet at that time; we will be meeting the first week of class on August 30:

- [ ] @bklein7 
- [ ] @maggie-oneil 
- [ ] @jtorre39 
- [ ] @cazinge

**Comment by maggie-oneil** [comment]
I can meet at that time. Looking forward to the first meeting!

**Comment by jtorre39** [comment]
Likewise for me! It works fine with my schedule.

**Comment by bklein7** [comment]
Wednesday meetings from 1:30pm—2:15pm work perfectly for me as well.

**Comment by kdahlquist** [comment]
I got confirmation from @cazinge that the Wednesday coding meeting time of 2:15-3:00 works.  I'll see the coding team on the 30th.  Location is TBA.  I'll post here once I reserve the room.  The data analysis team meeting will be at 1;30, location also TBA.

**Comment by kdahlquist** [comment]
Both the coding team and data analysis team meetings will be held in LSB 118 throughout the semester.  See everyone on Wednesday!

**Comment by kdahlquist** [comment]
@bklein will work Monday afternoons; @maggie-oneil will work Thursday mornings.
