### ISSUE TITLE
Slight edit to GRNsight web page footer

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#35]
Can we make a slight edit to the GRNmap web site footer that appears on every page? Instead of

This web site is free and open to all users and there is no login requirement.
Web site content is available under the Creative Commons Attribution Non-Commercial Share Alike. GRNsight code is available under the open source BSD license.

Can it say (with the appropriate links preserved)?

This web site is free and open to all users and there is no login requirement.
Web site content is available under the Creative Commons Attribution Non-Commercial-Share Alike 3.0 Unported License.
GRNsight code is available under the open source BSD license.

**Comment by juansc** [comment]
Done.

**Comment by kdahlquist** [comment]
There are two periods after the word "license".  Please delete one of them.  Thanks.

**Comment by juansc** [comment]
Done.

**Comment by kdahlquist** [comment]
Verified and am closing.
