### ISSUE TITLE
Sigmas are not being calculated for genes/times with missing values

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#352]
Sigmas are not being calculated for genes and timepoints with missing values.  I believe the standard deviation can be computed as long as there are two replicates, so we need to check on this.

**Comment by kdahlquist** [comment]
Please make sure we have complete test coverage on this as well as functionality.

**Comment by dondi** [comment]
Code review comment in #353 applies here because stddev is included within the same unit test.

**Comment by kdahlquist** [comment]
Can close because #353 has been closed.
