### ISSUE TITLE
minLSE is not being computed when data contains missing values

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#353]
minLSE is not being computed when data contains missing values.  Need to fix.

**Comment by cazinge** [comment]
Leaving comment here due to there being no central thread for this week, both this and #352 have been fixed in beta, with tests passing. We are currently making tests for the new function, "computeStatistics".

**Comment by kdahlquist** [comment]
Track down the undeclared qq variable.

**Comment by kdahlquist** [comment]
We need to document the actual minLSE computation since it seems to keep coming up as a white board exercise.  Will @cazinge and @jtorre39 write up the equation (in an equation editor) and post?  Create a page for it on the wiki; later it will be moved to more formal documentation.

I understand that tests and function need to be written for this issue this week.

**Comment by jtorre39** [comment]
I have a picture of the equation but am not quite sure how we are handling posting images to the wiki. I will be able to post it on the wiki after the next meeting however.

**Comment by cazinge** [comment]
We found some bugs in computeStatistics which we fixed and have also finished the test for it. @jtorre39 will run the full test suite on his laptop before the next meeting to make sure everything is else good.

**Comment by jtorre39** [comment]
Ran the tests on the current beta branch and all tests passing!

**Comment by dondi** [comment]
Code review results:
* Include a comment in the computeStatisticsTest explaining when the "zero threshold" is 1E-15 vs. 1E-4
* Remove TODO comment
* Add test cases with negative numbers and zeroes

**Comment by jtorre39** [comment]
Added test cases and removed the TODO comment.

**Comment by jtorre39** [comment]
Added the diagram of minLSE to the wiki and also added the comment in our test specifying our use of lesser precision.

**Comment by kdahlquist** [comment]
Two final clean-up items and we can close this:
- Add a trivial all-zero case to the calculation tests, just so we have that corner case
- Add a description of the variables in the minLSE wiki page

**Comment by jtorre39** [comment]
Added the trivial all-zero case and added the description of the variables in the minLSE page.

**Comment by kdahlquist** [comment]
Looks good; closing.
