### ISSUE TITLE
Data Analysis Team Tasks for Week of 8/30/17

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#354]
Data analysis team tasks for week of 8/30/17:
 - [x] @bklein7 work on L-curve plots to get them on the same scale
 - [ ] @maggie-oneil #344

**Comment by bklein7** [comment]
An updated version of the _R_ script for generating L-curves has been uploaded to the Dahlquist Lab repository: https://github.com/kdahlquist/DahlquistLab/blob/master/R_scripts/L-Curves.Rd. Although this code is still a work in progress, the following features have been successfully added:

- The user can now manually adjust the x and y axes.
- The user can opt not to plot alpha value labels.
- The user can plot up to seven L-curves on the same graph (this limitation stems from the fact that only 7 distinct colors have been hard-coded into the script).

I can provide a demonstration this Wednesday. Documentation and instructions are coming soon.
