### ISSUE TITLE
Honors Thesis Abstract Due Sept. 30

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#357]
@maggie-oneil, your Honors Thesis Abstract is Due Spet. 30.  @kdahlquist and @bengfitzpatrick will need to review it before submission.  Please give us a draft by the meeting on September 20.  You can use the wiki for your draft so we can group edit.

**Comment by maggie-oneil** [comment]
In reviewing my abstract from last semester's symposium along with the requirements for honors, I have uploaded an abstract to the gihub wiki for editing, which can be found here:

https://github.com/kdahlquist/GRNmap/wiki/ONeil-Honors-Thesis-Abstract

Considering honors has not specified any requirements for the abstract, and has also mentioned the abstract may change between now and when my thesis is completed, I figure the succinct explanation of work from last symposium's abstract should suffice.

**Comment by kdahlquist** [comment]
@maggie-oneil will revise abstract based on thinking prospectively about what she wants to accomplish this year.  Brainstorm some questions and then @kdahlquist and @bengfitzpatrick will assist with scoping out the work.

**Comment by maggie-oneil** [comment]
Discussed the idea of systematically removing edges, one at a time, to determine the role each edge plays in the db5 network (in terms of graph stats). This will be done in tandem with performing the same protocol on a random network that has a very similar LSE/minLSE ratio, but no similar edges. The result will be 56 experiments to run, and to compare the graph statistics for each.

**Comment by kdahlquist** [comment]
Also, @maggie-oneil is going to give us a recap on the graph stats next meeting now that she's computed them all by hand so we can have a discussion of which are worth pursuing further.

The other two items we discussed were
* writing up the copious results from last Spring
* investigating the effect of weights on the graph stats (@maggie-oneil has determined that Gephi is only computing stats for unweighted networks)

**Comment by maggie-oneil** [comment]
Update from talking with Dr. Dahlquist - thesis will also cover a write up of the data and statistics compiled at the end of last semester, and looking at how weights might be incorporated into graph statistics, which are all currently unweighted statistics. At the next meeting, I will have a recap on graph stats so that we are able to address the last point of making unweighted statistics weighted

**Comment by maggie-oneil** [comment]
Here is my updated thesis - it is 257 words, with the cap being 250. https://github.com/kdahlquist/GRNmap/wiki/ONeil-Honors-Thesis-Abstract

**Comment by maggie-oneil** [comment]
submitted abstract and closed issue
