### ISSUE TITLE
Task list for Coding team Fall 2017

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#359]
SCCUR abstract:
- [x] #362 

Issues on the verge of closure:
- [x] #353
- [x] #352 
(add trivial zero case; annotate wiki page)

Next up:
- [x] #289
(unit tests; clean up incoming data structure when doing iterative runs)
- [x] #185 
- [x] #375 

Last on the list, if there is time:
- [ ] #241
- [ ] #361

At your work session today, before doing any "work" sit down and look at each of these issues and write out your plan of attack for these.

1. Replicate the bug
2. Write the test for the bug (it should fail initially)
3. fix the code
4. run the entire test suite
5. Rinse and repeat

**Comment by kdahlquist** [comment]
I gave some issues a 0.5 priority so that you have a menu of tasks to work on if you need a break from the priority 0 tasks.  I don't mean them to be distracting, but they are either the next things we need to work on or relatively minor (I hope).

**Comment by kdahlquist** [comment]
I updated the tasks.

**Comment by jtorre39** [comment]
From the previous meeting we've been working on the test file audit and familiarizing ourselves with the corresponding issues. I focused on the test file audit while @cazinge can talk about addressing the bug in output.m. I have a couple questions moving forward on the test audit that I will ask at the meeting.

**Comment by jtorre39** [comment]
We weren't able to get to it in the meeting, but am I able to go to the One Card Office and request access for Dahlquist's lab and the UH lab?

**Comment by kdahlquist** [comment]
Sorry, @jtorre39, forgot to answer this.  The permission for my lab should already be there, so you could get it coded at the OneCard office at any time.  @bengfitzpatrick needs to chime in about the UH lab because he controls that.

**Comment by jtorre39** [comment]
Just to update, I've gotten OneCard access and can confirm that I have access to the lab in LSB.

**Comment by jtorre39** [comment]
For this week, I've been continuing work on the test file audit #361 and getting things squared away with that.

**Comment by jtorre39** [comment]
We've finished the poster for review and for this week I spent a long time finishing LSETest and removing its need for an input sheet. In the process I seemed to have discovered a bug related to compressmissingdata. I found GRNmap read in an input sheet and incorrectly made the compressed matrix which will be shown in the pictures below.

**Comment by jtorre39** [comment]
![log2fc 1 _compressed](https://user-images.githubusercontent.com/16827894/32571318-e06a48b6-c47b-11e7-990b-df4cf2ba31b2.PNG)

**Comment by jtorre39** [comment]
![log2fc 2 compressed](https://user-images.githubusercontent.com/16827894/32571322-e40bec9a-c47b-11e7-9963-e557397b897c.PNG)

**Comment by jtorre39** [comment]
The data cells in column 4 are incorrectly being appended to column 4 instead of column 3. This pushes the data cells that should be in column 4 to column 5. This bug might possibly be related to the inputsheet since it is a bit old or some oversight we did not catch. I will attach a link to the input sheet.

**Comment by jtorre39** [comment]
[LSETest input sheet](https://github.com/kdahlquist/GRNmap/blob/master/test_files/lse_tests/4-genes_6-edges_artificial-data_Sigmoidal_estimation_fixb-0_fixP-0_no-graph.xlsx)

**Comment by dondi** [comment]
I see the difference in behavior although from my vantage point I don't yet have a full sense for what is going on here. I do agree that this would be a new issue. Write this up as a new issue, then at the meeting, assess whether this might block the data analysis team.

**Comment by jtorre39** [comment]
Copied the information I wrote here into a new issue. #380

**Comment by cazinge** [comment]
Updating on this ticket due to having resolved these tickets without running the ENTIRE test suite to fully resolve, but #289, #185, and #375 have been tested for and resolved by my latest commit. The problem with these tickets pertained to information being copied over into rows that were one off, and similarly for the threshold b problem, the data was being carried over from a previous spreadsheet. I've written tests that check for the issue, but they're solely testing for the size of the tables rather than the values (which for threshold_b was the main issue), so for next week I'll be addressing that and finishing up more comprehensive tests for the L_Curve script.

**Comment by jtorre39** [comment]
Ran full test suite with Eddie's code to double check everything's passing. Everything's all good!

**Comment by dondi** [comment]
OK, it's merged @jtorre39

**Comment by jtorre39** [comment]
Double checking the input sheets for issue #361 has been taking a while. I've found at least one that had extra rows that no longer conformed to the current input sheet standards. In the meanwhile I updated the readme.md to describe each of the folders in the directory level under test_files.

**Comment by kdahlquist** [comment]
Closing this and creating new list for Spring 2018 semester.
