### ISSUE TITLE
Coding Team Should Present at SCCUR 11/18/17

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#362]
We would like the coding team to present at the Southern California Conference for Undergraduate Research on Saturday, November 18, all day from ~8:00 AM to ~6:00 PM. http://www.sccur.org/

Abstracts are due October 5.

**Comment by kdahlquist** [comment]
Look up the abstract guidelines on the SCCUR website and write a draft on a wiki page for review at next Wednesday's meeting.

**Comment by jtorre39** [comment]
Looked up the requirements for the abstract submission:

- The submission's title
- 250 words max abstract
- A list of keywords (10 maximum)

**Comment by jtorre39** [comment]
Submitted a first draft.

**Comment by kdahlquist** [comment]
Ready to submit :shipit:

**Comment by kdahlquist** [comment]
When this has been submitted, don't close the issue but just lower the priority in case reviewers request changes.

**Comment by jtorre39** [comment]
I submitted the abstract. It is possible to submit revisions at any time.

**Comment by jtorre39** [comment]
We've gotten accepted and @cazinge and I have to complete registration.

**Comment by jtorre39** [comment]
I've completed registration!

**Comment by kdahlquist** [comment]
@cazinge, the registration is due on Friday, so please be sure to take care of this soon.

**Comment by dondi** [comment]
Poster changes:
* Work in progress becomes work that has been done
* Major result: uniform computations across multiple machines
* Bug fixes for minLSE and refactoring of statistical tests, allowing easier bug fixing in general
* Future Work becomes Conclusions; decrease header sizes to get more space
* Move link to title section of poster

**Comment by jtorre39** [comment]
We have a revised poster ready for review for Tuesday!

**Comment by jtorre39** [comment]
[Revised Issue](https://docs.google.com/presentation/d/13ND9lB2V15HQZJl8ltWYo3gJoerQGyG8rHl5MKtPlq0/edit?usp=sharing)

**Comment by jtorre39** [comment]
Start Date
18-11-2017 2:15 PM 

End Date
18-11-2017 3:15 PM

**Comment by kdahlquist** [comment]
Poster has been submitted to John Kaufman for printing.  He will send an email when it is ready for pick-up.

**Comment by kdahlquist** [comment]
Done!
