### ISSUE TITLE
Write Up Results from Spring and Fall 2017 Semesters

### ISSUE THREAD

**Issue by bklein7** [kdahlquist/GRNmap#374]
@bklein7 and @maggie-oneil will return to results from spring 2017 as well as preliminary results from fall 2017 and write up conclusions regarding this work. In doing so, previous data analyses will be synthesized to work towards upcoming publications—including senior theses and a journal article—as well as to inform future directions.

**Comment by bklein7** [comment]
I have gone through and compiled results regarding db1-db6 and random networks derived form db5 into a single powerpoint: 

https://github.com/kdahlquist/DahlquistLab/blob/master/documents/GRNmap_2017-Data-Analysis-Results_BK20170928.pptx.

These results were organized thematically. Links to original files on GitHub and relevant GitHub issues are included in the "notes" sections of each slide.

**Comment by bklein7** [comment]
The gene list for db1-db6 and updated L-curve step-down experiment graph (LSE vs. parameter #) were added to the cumulative results powerpoint:

https://github.com/kdahlquist/DahlquistLab/blob/master/documents/GRNmap_2017-Data-Analysis-Results_BK20170928.pptx

An accompanying Word document analyzing the results presented in this powerpoint was uploaded (this is a work in progress):

https://github.com/kdahlquist/DahlquistLab/blob/master/documents/GRNmap_2017-Data-Analysis-Results_BK20171010.docx

**Comment by kdahlquist** [comment]
@maggie-oneil should also be working on this one.  She should look at all the data we have already gathered and write an interpretation of the results.

**Comment by maggie-oneil** [comment]
Almost complete with writing up results for closeness centrality. Will upload the write-up document to this thread this weekend with sections for closeness and betweenness centrality complete

**Comment by kdahlquist** [comment]
@bklein7 and @maggie-oneil are there any updates that I can review before the meeting today?

**Comment by maggie-oneil** [comment]
Unfortunately, no, my updates will not be ready until right before meeting today. I still have some final notes I have to make. I will print a handout for everyone to bring to meeting and post the link to the document here around 1:15pm.

**Comment by maggie-oneil** [comment]
[MO.db5GraphStatsWriteup.docx](https://github.com/kdahlquist/GRNmap/files/1396238/MO.db5GraphStatsWriteup.docx)

**Comment by bklein7** [comment]
Here are my updated files for this week regarding our write-up:

https://github.com/kdahlquist/DahlquistLab/blob/master/documents/GRNmap_2017-Data-Analysis-Results_BK20171010.docx

https://github.com/kdahlquist/DahlquistLab/blob/master/documents/db5-random-network_edge-analysis_BK20171018.xlsx

**Comment by bklein7** [comment]
This week, I expanded the analysis comparing edges found in 30 random networks (modeled off of db5) to those in db5. The files I uploaded include:

- An updated Excel spreadsheet with compiled edge counts for the 30 random networks and graphs: https://github.com/kdahlquist/DahlquistLab/blob/master/documents/db5-random-network_edge-analysis_BK20171018.xlsx
- A new Excel spreadsheet in which an exploratory "ideal network" was built: https://github.com/kdahlquist/DahlquistLab/blob/master/documents/db5-random-networks_ideal-network_BK20171024.xlsx
- A PowerPoint presentation summarizing the results produced in the files above: https://github.com/kdahlquist/DahlquistLab/blob/master/documents/db5-random-network_edge-analysis_BK20171024.pptx

**Comment by kdahlquist** [comment]
@kdahlquist and @maggie-oneil met this morning to discuss next steps.

@maggie-oneil will run db7 in Gephi when @bklein7 has produced the input workbook #377.

@maggie-oneil will continue to write-up in detail the graph statistics results that we have already gathered, focusing first on db5.

@maggie-oneil should post the Word document "MO.db5GraphStatsWriteup.docx" in the DahlquistLab > documents folder and keep updating it there as she works on it.

**Comment by maggie-oneil** [comment]
Final touches put on the "MO.db5GraphStatsWriteup.docx" document, and uploaded to the appropriate folder. This document can also be found at the end of this comment. Similar documents will be produced in subsequent weeks for each network. Investigation into the graph statistics for db5 yielded some interesting potential applications derived from looking at Brandon's presentation yesterday, and those applications will be summarized in a presentation for next week's lab meeting, which I am wrapping up now. 

https://github.com/kdahlquist/DahlquistLab/blob/master/documents/MO.db5GraphStatsWriteup.docx

**Comment by maggie-oneil** [comment]
Here is my presentation today, focusing mainly on the uses for each statistic, and the best way to glean information from the graphs, which can be found below. 

https://github.com/kdahlquist/DahlquistLab/blob/master/documents/MO.11.2.17.StatisticsSuggestions.pptx

**Comment by kdahlquist** [comment]
@bklein7 made corrections to 
* A new Excel spreadsheet in which an exploratory "ideal network" was built: https://github.com/kdahlquist/DahlquistLab/blob/master/documents/db5-random-networks_ideal-network_BK20171024.xlsx
* A PowerPoint presentation summarizing the results produced in the files above: https://github.com/kdahlquist/DahlquistLab/blob/master/documents/db5-random-network_edge-analysis_BK20171024.pptx

because one of the edges went the wrong way.

**Comment by maggie-oneil** [comment]
Today I worked on compiling information on what each graph statistic means for every node in db5. I still have 6 nodes to complete the explanation for, as part of the way through I was able to determine more information about closeness centrality, and went back to ensure the node summary includes that. The following is a draft of this document, and I will comment the final version by tomorrow afternoon at the latest, as today I unforuntately have to run to a meeting at 12:15.
https://github.com/kdahlquist/DahlquistLab/upload

What I found is that closeness centrality relies mostly on in degrees, so even if the betweeness of a node is 0, it can still have a closeness centrality > 0 because the statistic is looking at a number of shortest paths going through/emanating from the node in question.

**Comment by maggie-oneil** [comment]
Below is the final version of my node writeup for this week. It seems as though YHP1 has a lot more going on than we realized, as it is an important hub that is connected to other important hubs in the graph, which is why the statistics end up looking weird when isolating the node and not looking at the full picture. 
https://github.com/kdahlquist/DahlquistLab/blob/master/documents/MO.db5NodeWriteup.docx

**Comment by maggie-oneil** [comment]
Today I compiled the betweeness centrality measures for the random networks as compared to db5. In compiling these betweeness values, I recorded the number of nodes in each network with a betweeness of 0, the number of nodes with a betweeness greater than 0 (used as N for average magnitude calculations) and the number of nodes with a betweeness higher than 14, which is the highest betweeness centrality measure seen in db5. The average magnitude of each network was calculated by summing the positive betweeness, and dividing by N. I then did a t-test to determine what random networks varied significantly from db5. Of the 30 random networks, 12 had an average magnitude that **was not** significantly different from db5 (highlighted in green).

https://github.com/kdahlquist/DahlquistLab/blob/master/data/Fall2017/MOdb5_rand1-31_BetweenessComparison.xlsx

**Comment by maggie-oneil** [comment]
Today I made the adjustments mentioned during research meeting yesterday, with doing a p-value correction and paired t test for the betweenness centrality document I generated last week, and performing the same analysis of production rates this week. Over the thanksgiving break I will be completing the ANOVA writeup as well. Below is the documentation for this week, and if there are any suggestions from @bengfitzpatrick or @kdahlquist for how to better analyze the differences between measures for a given node (ex. ASH1 production in db5 compared to Rand1), please let me know so I can include that analysis. 


https://github.com/kdahlquist/DahlquistLab/blob/master/data/Fall2017/MOdb5_rand1-31_BetweenessComparison.xlsx

https://github.com/kdahlquist/DahlquistLab/blob/master/data/Fall2017/MOdb5_rand1-31_ProductionRates.xlsx

**Comment by maggie-oneil** [comment]
My apologies as I forgot to comment on the issue last week. Below is a compilation of the LSE:minLSE ratios for all random networks, along with the t-test results comparing betweeness centrality and production rates of each random network to db5. 
https://github.com/kdahlquist/DahlquistLab/blob/master/data/Fall2017/MO.Compiled%20LSEminLSE%20ratios.%2011.30.17.xlsx

**Comment by bklein7** [comment]
Here are links to the articles I had mentioned during our Wednesday, December 6 meeting hypothesizing that HMO1 functions as a linker histone:

http://pubmedcentralcanada.ca/pmcc/articles/PMC5312240/

https://epigeneticsandchromatin.biomedcentral.com/articles/10.1186/s13072-016-0062-8
