### ISSUE TITLE
Problem with production_rates sheet in second input workbook during L-curve run

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#375]
This issue is related to #185 and #289.  When an L-curve is run, GRNmap automatically creates a new input sheet for each sequential alpha value.  GRNmap is offsetting the production rate values by one column in the production_rates sheet starting with the second input workbook in the L-curve run.  Look at that sheet in the file attached.
[15-genes_28-edges_db5_Sigmoid_estimation_missing-values_L-curve_2.xlsx](https://github.com/kdahlquist/GRNmap/files/1357494/15-genes_28-edges_db5_Sigmoid_estimation_missing-values_L-curve_2.xlsx)

**Comment by kdahlquist** [comment]
I have verified that this is fixed in the beta code downloaded on 11/13/17.  However, I don't want to close this issue until unit tests have been written.

**Comment by jtorre39** [comment]
See #386

**Comment by kdahlquist** [comment]
This is closable because it is fixed and the tests are there.
