### ISSUE TITLE
Run @bklein7's consolidated network (db7)  in GRNmap and Gephi

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#377]
In the meeting yesterday, @bklein7 showed a consolidated network that was generated by looking at common edges between db5 and rand1-rand31.  @bklein7 should run this new network in GRNmap in two ways:
- having the initial guesses for the network weights all = 1
- having the initial guesses for the network weights be 1 or -1 based on his predictions as to whether that edge should be activating or repressing

@maggie-oneil will also take this network and run it in Gephi so that we have the corresponding graph statistics.

@maggie-oneil and @bklein7 need to coordinate to use the same input workbooks.

Let's call this new network "db7".

Please save the files in DahlquistLab > data > Fall2017

**Comment by kdahlquist** [comment]
This is running right now in Seaver 120.

**Comment by bklein7** [comment]
The two db7 input sheets, containing either unweighted or weighted initial guesses, can be found here:
- https://github.com/kdahlquist/DahlquistLab/blob/master/data/Fall2017/14-genes_22-edges_BK-db7-unweighted_Sigmoid_estimation.xlsx
- https://github.com/kdahlquist/DahlquistLab/blob/master/data/Fall2017/14-genes_22-edges_BK-db7-weighted_fam_Sigmoid_estimation.xlsx

The two associated db7 output sheets can be found here:
- https://github.com/kdahlquist/DahlquistLab/blob/master/data/Fall2017/14-genes_22-edges_BK-db7-unweighted_Sigmoid_estimation_output.xlsx
- https://github.com/kdahlquist/DahlquistLab/blob/master/data/Fall2017/14-genes_22-edges_BK-db7-weighted_fam_Sigmoid_estimation_output.xlsx

Note that regardless of the weighting of initial guesses, both runs converged to a nearly identical solution for db7. However, the run starting with weighted initial guesses did require approximately 15,000 fewer iterations to reach this solution. The LSE:minLSE ratio for db7 (1.4471) was higher than that of db5 (1.4263).

**Comment by bklein7** [comment]
Results write up for hypothesis networks: https://github.com/kdahlquist/DahlquistLab/blob/master/data/Fall2017/hypothesis-network-testing_BK20171115.pptx

**Comment by kdahlquist** [comment]
@lkelly9 will run the network through Gephi on Tuesday.

**Comment by kdahlquist** [comment]
Need to double check if we have Gephi file for this.

**Comment by lkelly9** [comment]
[Gephi_node_stats_weighted_all_6_db_MO_02232017 (1) (1).xlsx](https://github.com/kdahlquist/GRNmap/files/2322672/Gephi_node_stats_weighted_all_6_db_MO_02232017.1.1.xlsx)

My apologies for not uploading these earlier! Are these the correct files?

**Comment by lkelly9** [comment]
[BKconsolidatednetwork.xlsx](https://github.com/kdahlquist/GRNmap/files/2324786/BKconsolidatednetwork.xlsx)

**Comment by kdahlquist** [comment]
Completed.
