### ISSUE TITLE
GRNmap coding/data analysis team meetings Spring 2018

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#386]
Based on the class and teaching schedules of all involved, it looks like the only viable time for a GRNmap meeting this Spring semester is Fridays from 10:30-11:30 AM.  We will combine the coding and data analysis team meetings this semester.  Please confirm your availability by posting a comment to this issue.

Once everyone has responded, I'll confirm the meeting location for Friday, January 12.

**Comment by jtorre39** [comment]
That works for me!

**Comment by bklein7** [comment]
Friday mornings from 10:30AM-11:30AM work well for me.

**Comment by maggie-oneil** [comment]
This works well for me, but I will have to leave around 11:25 to make it to class

**Comment by kdahlquist** [comment]
No problem, @maggie-oneil.  The meetings will be held in LSB 331.

@lkelly9 and @jtorre39 will need to pick up independent study forms from me.  I'll post here or e-mail when they are ready to pick up.  They will need to be turned in by Friday's add deadline to Isabella Rand in North Hall 100.

@lkelly9 will need to do safety training so that I can authorize her for access to my lab.

**Comment by kdahlquist** [comment]
Independent study forms are ready for pick-up for @lkelly9 and @jtorre39.  They are pinned to the bulletin board outside my office door.  You need to fill out the top and take them to Isabella Rand in North Hall 100.  They are due by Friday 1/12.

**Comment by maggie-oneil** [comment]
This semester I plan to do the bulk of my work on Tuesday's from 1pm-6pm, and on Monday's from 3pm-6pm.

**Comment by lkelly9** [comment]
This semester I will be working Tuesday's from 2-5pm and Wednesday's from 3-4pm.

**Comment by bklein7** [comment]
I plan to work on GRNmap projects this semester on Monday and Wednesday afternoons, from 3:00pm—7:00pm. This will include overlap with @lkelly9's schedule on Wednesday afternoons for training & collaboration.

**Comment by kdahlquist** [comment]
@jtorre39 and @johnllopez616, remember to comment on this issue with your planned weekly day/times for research this semester.

**Comment by jtorre39** [comment]
We'll have it posted by the end of the day!

**Comment by jtorre39** [comment]
We have it planned for a four hour block right after the coding/data analysis team meeting. So around 11:30 am - 3:30 pm on Fridays. 

Since @johnllopez616 and I did not meet last Friday since we were still figuring out the schedule, we're having a make-up work session this Wednesday.

**Comment by kdahlquist** [comment]
Sounds good!

**Comment by jtorre39** [comment]
Worked on verifying that the changes made by Eddie correctly caught the bug for #375 and #185 and correctly tested it. Good news! His fixes are valid and correctly address the bug. I believe this validates these two issues to be closed.

#289 however, I believe its fix is unrelated to the two mentioned above, so this issue still warrants investigation. Unfortunately, I will have to get to this next week as running LCurve to test things took massive amounts of time.

**Comment by kdahlquist** [comment]
this issue is getting confusing, let's close it.
