### ISSUE TITLE
LMU Undergraduate Research Symposium Spring 2018

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#387]
The LMU Undergraduate Research Symposium will take place on Saturday, March 24.

Abstracts are due Friday, February 9, 5:00 PM.

This will become a higher priority, closer to the date.

**Comment by kdahlquist** [comment]
Abstract drafts will be reviewed at the meeting on 2/2.  @bklein7 and @maggie-oneil will each give talks, @lkelly9 will give a poster with the assistance of them.

@johnllopez616 and @jtorre39 will do a joint poster.

**Comment by lkelly9** [comment]
Here is the rough draft of the abstract for my poster.

https://github.com/kdahlquist/GRNmap/blob/master/documents/abstracts/LK_TriBetaAbstract.md

**Comment by jtorre39** [comment]
@johnllopez616 and I have our abstract posted in the wiki:

[Link to the wiki!](https://github.com/kdahlquist/GRNmap/wiki/2018-LMU-Symposium-Abstract-for-Lopez-and-Torres-Draft-%231)

**Comment by maggie-oneil** [comment]
https://github.com/kdahlquist/GRNmap/blob/master/documents/abstracts/MO_Symposium_Tri-Beta.md

**Comment by kdahlquist** [comment]
All abstracts are ready to submit!

**Comment by jtorre39** [comment]
Submitted abstract!

**Comment by kdahlquist** [comment]
@johnllopez616 and @jtorre39, I sent you an e-mail yesterday that your poster is ready for printing.  Please post the PDF to the repository.

Schedule for Saturday:
* @mihirsamdarshi, @jtorre39, and @johnllopez616 are presenting posters 1:30-3:00pm
* @yshin4, @maggie-oneil, and @Nvafadari and Kat are presenting in a session from 3:10-4:25, UH1405
* @eileenchoe and @bklein7 are presenting in a session from 1:50-3:05, UH3222
* @lkelly9 is presenting a poster in the session from 3:00-4:30

Let's all meet at 1:15 at the big tree outside of UH first floor for our group pictures.

**Comment by jtorre39** [comment]
Poster printed! There's a bit of white space at the top, but it can be folded over. Poster also added to the repository.
