### ISSUE TITLE
TriBeta Conference for Data Analysis Team, Saturday, March 17

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#388]
The TriBeta Conference will be held on Saturday, March 17 at Concordia University in Irvine.  Abstracts are Due Feb. 17. @bklein7 and @maggie-oneil will give oral presentations.  @lkelly9, we'll see if there will be enough results for you to present a poster by then.

The Sample abstract form is in the repo on the master branch under documents/abstracts

https://github.com/kdahlquist/GRNmap/blob/master/documents/abstracts/TriBeta-Conference_2018_Sample-Abstract-Form.doc

Abstract submission site: https://docs.google.com/forms/d/e/1FAIpQLSeT1HZaa9GWBMQBy-Yx0-yW1LNB-JWA3kEtg7EdNCF-c70Ixg/viewform

**Comment by maggie-oneil** [comment]
Below is the rough draft of my thesis for both the symposium and the TriBeta conference, since both have a 250 word limit. I also have uploaded the file as the abstract submission form. 

Editable text: https://github.com/kdahlquist/GRNmap/blob/master/documents/abstracts/MO_Symposium_Tri-Beta.md

TriBeta Abstract Submission Form:
https://github.com/kdahlquist/GRNmap/blob/master/documents/abstracts/MO_Symposium_TriBeta-Conference_2018.doc

**Comment by lkelly9** [comment]
Below are links to the draft of my abstract for my poster.

Editable Text:
https://github.com/kdahlquist/GRNmap/blob/master/documents/abstracts/LK_TriBetaAbstract.md

TriBeta Abstract Submission Form:
https://github.com/kdahlquist/GRNmap/blob/master/documents/abstracts/LK_Symposium_TriBeta-Conference_2018.doc

**Comment by bklein7** [comment]
Two separate word documents containing my abstract, one of which is formatted specifically in accordance with the Tri-Beta guidelines, can be found in the abstracts folder of the Dahlquist Lab repository: https://github.com/kdahlquist/DahlquistLab/tree/master/documents/abstracts

**Comment by bklein7** [comment]
Here is the draft of my Tri-Beta presentation to be presented at today's meeting: https://github.com/kdahlquist/GRNmap/blob/master/documents/presentations/DeNault_0230_Klein.pptx.

**Comment by maggie-oneil** [comment]
Here is a mostly final draft of my presentation https://github.com/kdahlquist/GRNmap/blob/master/documents/presentations/MO.TriBetaPresentation.Draft.pptx

**Comment by kdahlquist** [comment]
Congratulations to Brandon for winning 2nd place for his presentation at this conference!
