### ISSUE TITLE
Data Analysis Team Senior Theses

### ISSUE THREAD

**Issue by bklein7** [kdahlquist/GRNmap#389]
The purpose of this issue is to provide a centralized thread where @maggie-oneil and @bklein7 can provide weekly status updates and work collaboratively on senior thesis materials.

A folder on the Dahlquist Lab repository has been created for the housing of thesis related documents, which can be found here: https://github.com/kdahlquist/DahlquistLab/tree/master/documents/theses.

**Comment by bklein7** [comment]
During Week 1, I produced a literature review primarily concerning the molecular mechanisms underlying the cold shock response in _Saccharomyces cerevisiae_ and the modeling of GRNs from microarray data and otherwise: https://github.com/kdahlquist/DahlquistLab/blob/master/documents/theses/Brandon%20Klein%20-2018-/GRNmap-Thesis_Annotated-Bib_BK20171115.docx.

I uploaded PDF documents of all references listed in this document along with Figures adopted from these journal articles, which can be found in this folder:
https://github.com/kdahlquist/DahlquistLab/tree/master/documents/theses/Brandon%20Klein%20-2018-/References.

I would suggest that @maggie-oneil create her own folder in the https://github.com/kdahlquist/DahlquistLab/tree/master/documents/theses folder for parallel storage of documents.

**Comment by kdahlquist** [comment]
Acknowledging receipt of @bklein7 and @maggie-oneil's annotated bibliographies by the deadline.  Have  good weekend!

**Comment by kdahlquist** [comment]
I gave @maggie-oneil feedback on the hard copy of her bibliography.  I'll provide my feedback for @bklein7 here since there are only few points:
- There is a more recent reference for the YEASTRACT database; they had an article in the 2018 _NAR_ database issue, which is probably more appropriate to cite.
- please remove the bold style from the references
- please provide the DOI numbers for the references when available (most, if not all of yours should have them.  Unfortunately Google Scholar does not automatically supply them in their reference format so you will need to get them from the articles themselves)
- when you turn in your outline, please include the list of references, non-bolded, with doi's as well.

**Comment by bklein7** [comment]
I revised my **annotated bibliography** following the feedback provided by @kdahlquist above and uploaded the updated file here: https://github.com/kdahlquist/DahlquistLab/blob/master/documents/theses/Brandon%20Klein%20-2018-/GRNmap-Thesis_Annotated-Bib_BK20171115.docx.

Further, I have uploaded my thesis **outline** here: https://github.com/kdahlquist/DahlquistLab/blob/master/documents/theses/Brandon%20Klein%20-2018-/GRNmap-Thesis_Outline_BK20171115.docx.

**Comment by kdahlquist** [comment]
@bklein7 I got your updated bibliography and outline.  Get some rest!

**Comment by bklein7** [comment]
The draft of my thesis results has been uploaded and can be accessed here: https://github.com/kdahlquist/DahlquistLab/blob/master/documents/theses/Brandon%20Klein%20-2018-/GRNmap-Thesis_Results_BK20180129.docx.

**Comment by kdahlquist** [comment]
Got it!

At 05:01 PM 2/9/2018, you wrote:

**Comment by bklein7** [comment]
The draft of my thesis discussion is uploaded and can now be accessed here:
https://github.com/kdahlquist/DahlquistLab/blob/master/documents/theses/Brandon%20Klein%20-2018-/GRNmap-Thesis_Discussion_BK20180215.docx.

**Comment by bklein7** [comment]
The draft of my thesis introduction is uploaded and can now be accessed here: https://github.com/kdahlquist/DahlquistLab/blob/master/documents/theses/Brandon%20Klein%20-2018-/GRNmap-Thesis_Introduction_BK20180316.docx.

**Comment by bengfitzpatrick** [comment]
to @bklein7 @maggie-oneil @kdahlquist 

In the theses folders of the dahlquist lab github repository I have placed word docs with notes on thesis drafts.

**Comment by bklein7** [comment]
The first full draft of my thesis is uploaded and can now be accessed here:
https://github.com/kdahlquist/DahlquistLab/blob/master/documents/theses/Brandon%20Klein%20-2018-/GRNmap-Thesis-Draft-Formatted_BK20180413.docx

**Comment by bklein7** [comment]
The final draft of my thesis has been uploaded and can be accessed here: https://github.com/kdahlquist/DahlquistLab/blob/master/documents/theses/Brandon%20Klein%20-2018-/BrandonKlein_Biology_Thesis_2018.pdf
