### ISSUE TITLE
 'rdiscount' Markdown engine is no longer supported by GitHub Pages 

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#392]
@johnllopez616, can you look into this warning that I'm getting e-mailed about:

The page build completed successfully, but returned the following warning for the `gh-pages` branch:

You are currently using the 'rdiscount' Markdown engine, which is no longer supported by GitHub Pages and may cease working at any time. To ensure your site continues to build, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/.

For information on troubleshooting Jekyll see:

https://help.github.com/articles/troubleshooting-jekyll-builds

**Comment by johnllopez616** [comment]
Removing the setting now, I will place it back if the site loses functionality.

**Comment by johnllopez616** [comment]
The website seems stable, let me know if you receive another error.

**Comment by kdahlquist** [comment]
No longer seeing this warning, so closing.
