### ISSUE TITLE
Test suite is failing silently; if individual test fails, then suite needs to fail

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#397]
@jtorre39 found that when the test suite is run, it only reports at the end if the tests completed, not if they passed or failed, so tests are failing "silently" if you don't scroll up to look at the results.  The test suite has to report that it failed if an individual test failed to alert the developer.

**Comment by jtorre39** [comment]
Added a check at the end of the test suite to check if any tests failed. A msgbox is now displayed in a new window regarding whether any test failed, or if they all passed. I believe it is sufficiently failing "loudly" as of now.

**Comment by bengfitzpatrick** [comment]
notes on this in "Addressing Issues" comment above.  Tests all passing. closing
