### ISSUE TITLE
GRNmap Coding Team Tasks for Spring 2018

### ISSUE THREAD

**Issue by jtorre39** [kdahlquist/GRNmap#398]
Will be using this issue to do general progress reports on various issues.

Tasks for @jtorre39

- [x] Fix Failing LCurve Tests
- [x] #289 
- [x] #397

**Comment by jtorre39** [comment]
Previously posted on issue #386 

Worked on verifying that the changes made by Eddie correctly caught the bug for #375 and #185 and correctly tested it. Good news! His fixes are valid and correctly address the bug. I believe this validates these two issues to be closed.

#289 however, I believe its fix is unrelated to the two mentioned above, so this issue still warrants investigation. Unfortunately, I will have to get to this next week as running LCurve to test things took massive amounts of time. 

EDIT: On closer inspection, I ran the tests again. Two of the LCurve test had been failing but the call to callTests was not letting me know this. For future cases, I will be giving the output of the test suite more scrutiny to prevent this happening again.

One of them was a test case that was incorrectly implemented, so I removed it as it was not a valid test case. Additionally, the second test to fail has to do with the NetworkWeights not being copied over properly. The difference in values ranges between a thousandth to a very small insignificant number. I will have to spend some time investigating the issue but believe it should not be a significant fix.

**Comment by jtorre39** [comment]
On investigation, I narrowed down the source of the LCurve failure to be from the test sheet changes I made a few weeks ago. Will revert the test sheets, and do a more methodical fix for the hidden decimal values.

**Comment by jtorre39** [comment]
Fixed the test sheets (took a while!) and noticed there were two test cases in LSETest.m that did a poor job of testing if general_least_squares_error got called properly. I fixed those two as well, the silently failing tests unfortunately set me back and I could not make progress on the new issues.

**Comment by kdahlquist** [comment]
While @johnllopez616 is waiting to meet with @dondi regarding Google Analytics, he will begin work on cleaning up the BioDB work on GRNsight so it can be merged into the main GRNsight project.  

@jtorre39 is working on the release and they are both working on the poster.

**Comment by jtorre39** [comment]
@johnllopez616 and I have finished our first draft of the poster. We've emailed the draft of the poster to @kdahlquist for review.

**Comment by jtorre39** [comment]
Additionally, I've drafted the release and have it pending approval for v1.9.

**Comment by kdahlquist** [comment]
@jtorre39 is going to wrap-up on issue #195 as his last issue for the semester.  Closing this one.
