### ISSUE TITLE
Documentation of input/output spreadsheet format.

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#4]
We need documentation of the input spreadsheet format.  All sheets should be listed and described in detail what data need to be provided.  Additionally, a description of all new worksheets in the output file should also be described.  This information could initially begin on the GRNmap wiki and then be moved to the Documentation page on the web site.

**Comment by kdahlquist** [comment]
As part of our initial round of tests, we need to make absolutely sure that the wiki is up-to-date with the current implementation of the code.

**Comment by trixr4kdz** [comment]
I've updated the input/output wiki. I only changed the names of the input sheets for "How to format the input file for GRNmap", but I added some descriptions for the output sheets. Not quite sure if they're sufficient though.

**Comment by trixr4kdz** [comment]
Should I also include the "optimization_diagnostics" section to the output wiki even though we haven't started that one yet?

**Comment by kdahlquist** [comment]
Yes, go ahead.  You can add a note that it hasn't been implemented yet and reference the issue number.  You can edit it later to take the note off when it has been done.

**Comment by trixr4kdz** [comment]
Finished

**Comment by kdahlquist** [comment]
I reviewed and edited both wiki pages for the input (https://github.com/kdahlquist/GRNmap/wiki/How-to-format-the-input-file-for-GRNmap) and output (https://github.com/kdahlquist/GRNmap/wiki/How-to-interpret-the-output-file-for-GRNmap) workbooks.

I'm going to assign this to @bengfitzpatrick now so that he can review what I wrote about the optimization_diagnostics sheet and make any additions and corrections.  In particular:
* I'm pretty vague about the LSE
* I don't know what to say at all about the penalty
* I'm also not sure if I described the min LSE correctly
* Ditto for the SSE

Anyhow, please review and make additions/corrections as needed.

While I was looking at the output workbook to verify this documentation, I noticed some additional inconsistencies with the way various sheets are formatted.  We might be in a good place to try to clean this up as well.  I'll start another issue for this.

**Comment by bengfitzpatrick** [comment]
I have edited the wiki, adding a definition of the penalty and tweaking language here and there. Modulo checking my work and sheet naming, this issue is ready to close

**Comment by kdahlquist** [comment]
I am leaving this issue open pending changes made in issue #119.  Right now we have two pages specifying input workbooks and one specifying output workbooks.  The output wiki page needs to be updated because of the changes made to the input workbook, but I'll leave editing it until changes have been made and verified in the code.

**Comment by kdahlquist** [comment]
@kdahlquist has updated this with the latest changes "Model" --> "production_function", adding L_curve, and getting rid of "Deletion".  I'm putting a review requested on this to remind me to go through it once more before closing.

**Comment by kdahlquist** [comment]
Related to #214 which I just opened.

**Comment by kdahlquist** [comment]
The documentation on the wiki on these two pages:
* https://github.com/kdahlquist/GRNmap/wiki/How-to-format-the-input-file-for-GRNmap-v1.4-and-above
* https://github.com/kdahlquist/GRNmap/wiki/How-to-interpret-the-output-file-for-GRNmap

Needs to be migrated to the Documentation page in their respective sections.

The idea is the the website documentation is for the User of GRNmap and the wiki documentation is for the developers.

**Comment by kdahlquist** [comment]
Documentation is on web site. Closing.
