### ISSUE TITLE
Testing new beta code

### ISSUE THREAD

**Issue by juansc** [kdahlquist/GRNmap#40]
The new beta code outputs optimized log2expression sheets for each strain. We need to test this code to make sure that the output stayed the same. The only change that was made to the code is that the data is outputted differently.

**Comment by kdahlquist** [comment]
This seems to be redundant to #32, which is closed.  I am going to close this one, too.  There is a little mystery because this same thing basically appears in the release notes to version 1.0.2 and 1.0.6.  However, I think we shouldn't worry about it too much and just move on from here.
