### ISSUE TITLE
Disable Michaelis-Menten until tests can be written checking the math

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#402]
Since Michaelis-Menten is not fully tested right now, we want to disable it until we have time to write the tests.  We intend to publish something with GRNmap this summer and it would be best to not have functionality we are not sure of included.

Suggestion for how to do this:
1. If a user selects Michaelis-Menten in their optimization_parameters sheet, detect it, and return an error with the following message:

"The Michaelis-Menten function is currently disabled until testing can be completed.  Please select "Sigmoid" in order to run GRNmap.

2. Then, certain tests will have to be commented out because they will now fail.

**Comment by jtorre39** [comment]
Dug through a lot of files that used MM and refactored tests where needed when MM is used.

For future GRNmappers I tagged the lines of code that would need to be uncommented and changed when we do run Michaelis-Mitten in the future. Simply search through the project (using an editor's search function or through Github) for the following line:

```    % Currently disabled until testing for Michaelis-Menten is completed! ```

ReadInputSheet was changed to display a warning and error out when "MM" is detected in the optimization parameters for the production function, and a corresponding test was added to ensure this feature is working properly. In the future, this test will be extraneous once "MM" is fully tested and ready to be used again in GRNmap. 

Currently running the entire test suite before I submit a pull request for this particular issue.

**Comment by jtorre39** [comment]
Currently functions besides readinputsheet do not need to touched, they can be reverted besides readinputsheet.

**Comment by jtorre39** [comment]
Code merged onto beta! Tests all passing.

**Comment by kdahlquist** [comment]
I forget--was this change included in v1.9 or is it new in v1.10?

**Comment by kdahlquist** [comment]
Confirmed in v1.10.  @jtorre39, please add a note regarding this issue to the release notes of either v1.9 (retroactively) or v1.10.  Then you can go ahead and close this one.

**Comment by jtorre39** [comment]
Release v1.9 is updated!
