### ISSUE TITLE
GRNmap Download page has style issues

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#408]
The GRNmap Download page has some style issues that are different than the other GRNmap pages.
* text at bottom of page is no longer centered
* the section bars are the wrong color and font style from what is found on other pages

**Comment by johnllopez616** [comment]
Will investigate immediately

**Comment by johnllopez616** [comment]
Converted the download tabs to the GRNmap Style. There are some small issues with the tabs overlapping the set margins. Will investigate more tomorrow.

**Comment by johnllopez616** [comment]
I believe my recent changes should have solved the problem and met the style changes requested. The downloads page now has an accordion with one tab staying open at a time with the style of the old one.

**Comment by kdahlquist** [comment]
Confirmed fixed and closing.
