### ISSUE TITLE
GRNmap fatal error

### ISSUE THREAD

**Issue by bengfitzpatrick** [kdahlquist/GRNmap#41]
I'm trying to move my VV&A files to the current GRNmap source for testing and evaluation, with the new MATLAB r2014b release, and I'm having a problem.  Running the GRNmodel code producing the following error. I tried three distinct input files.  I tried two versions of the code (one from last summer, one from https://github.com/kdahlquist/GRNmap/tree/master/matlab).  Juan, what is up with this?

Undefined function 'max' for input arguments of type
'matlab.graphics.GraphicsPlaceholder'.

Error in GRNmodel (line 15)
nfig        = max(figHandles);

**Comment by juansc** [comment]
I talked about this bug in [issue 39](https://github.com/kdahlquist/GRNmap/issues/38). The beta code no longer has this issue. However, this bug is so significant that I think that it might be worth while doing a hot fix in the master branch and make it GRNmap v1.01 or something.

**Comment by kdahlquist** [comment]
I agree that we should patch the master code.  To conform to our numbering system, we would call this version 1.0.2 (even numbers being release versions, and the x.x.2 meaning it is a patch).  You will need to go through the process of tagging the release, making the executable and the release.  There will need to be an announcement on the News page and release notes added to the About page.  You can take a look at the GRNsight news and about pages to see how we organize new releases.

**Comment by kdahlquist** [comment]
this was fixed when we merged beta and master
