### ISSUE TITLE
Missing data error on v1.10 pre-release (beta)

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#411]
![image](https://user-images.githubusercontent.com/6463867/47464187-53c42180-d79d-11e8-8cfd-cb7559f5a321.png)

![image](https://user-images.githubusercontent.com/6463867/47464212-64749780-d79d-11e8-9bc3-9f49d1dcbe0f.png)

I'm running the input workbook pasted below on v1.10 pre-release (beta) and am getting the errors shown above.  I don't understand what is going on because line 2, which would be CIN5, doesn't have the problem, and if there is a single replicate, I though we were allowing it to run, just not computing sigmas for it.
[17-genes_32-edges_db3_Sigmoid_estimation_all-timepoints_no-dHAP4-data.xlsx](https://github.com/kdahlquist/GRNmap/files/2512502/17-genes_32-edges_db3_Sigmoid_estimation_all-timepoints_no-dHAP4-data.xlsx)

**Comment by jtorre39** [comment]
I'll be taking a look at this!

**Comment by jtorre39** [comment]
Okay, so I've corrected all three sheets! They seem to working so far, as GRNmap gets to the point where it starts generating graphs. I am unable to test the an entire run for each (my poor laptop takes quite a bit of time to complete a run). To get 100% confidence I'll have to take GRNmap and run these sheets on a different computer, perhaps the ones in LSB when I get a chance. In the end, it did seem to only be a result of the input sheet getting text inputted into the number cells. 

But will try to run the sheets later in the week completely so we can consider this issue resolved!
 
[(corrected) 16-genes_27-edges_db6_Sigmoid_estimation_all-timepoints.xlsx](https://github.com/kdahlquist/GRNmap/files/2523444/corrected.16-genes_27-edges_db6_Sigmoid_estimation_all-timepoints.xlsx)
[(corrected) -17-genes_32-edges_db3_Sigmoid_estimation_all-timepoints_no-dHAP4-data.xlsx](https://github.com/kdahlquist/GRNmap/files/2523445/corrected.-17-genes_32-edges_db3_Sigmoid_estimation_all-timepoints_no-dHAP4-data.xlsx)
[(corrected)-15-genes_34-edges_db7_Sigmoid_estimation_all-timepoints_no-dHAP4-data.xlsx](https://github.com/kdahlquist/GRNmap/files/2523446/corrected.-15-genes_34-edges_db7_Sigmoid_estimation_all-timepoints_no-dHAP4-data.xlsx)

**Comment by kdahlquist** [comment]
Aaahhhh.  I should have known.  I will run the corrected workbooks today and post the results (probably tomorrow).

**Comment by kdahlquist** [comment]
Two of the three files have completed the runs; the third one is still running.  I'm going to close this one.
