### ISSUE TITLE
Create and organize test files folder

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#42]
@trixr4kdz, create a "test_files" folder on the test_suite branch to hold the files that @bengfitzpatrick sent you for testing.  Look at the GRNsight test-files folder here: https://github.com/dondi/GRNsight/tree/master/test-files to see how the different types of test files are organized into folders based on what they are.  We will want something similar (but not necessarily exact) for our testing purposes.

**Comment by trixr4kdz** [comment]
Created "test_files" folder
