### ISSUE TITLE
file navigation issue: location of input spreadsheet can be in any folder

### ISSUE THREAD

**Issue by bengfitzpatrick** [kdahlquist/GRNmap#44]
>> GRNmodel
input sheet has to be in the folder containing the source code.  When i navigate to a different folder, I get the following error message:

Error using validpath>getFullName (line 66)
File
'Y:\zdrive\LMU\Projects\GeneExpression\GRNmap\currentBeta\GRNmapBeta\matlab\Input_4_gene_inverse.xlsx'
not found.

Error in validpath (line 23)
        filenameOut = getFullName(filename);

Error in xlsfinfo (line 44)
    filename = validpath(filename);

Error in readInputSheet (line 11)
[type, sheets]  = xlsfinfo(input_file);

Error in GRNmodel (line 17)
GRNstruct = readInputSheet(GRNstruct); % We've called Parameters

**Comment by juansc** [comment]
The current implementation requires the Excel sheet to be in the same directory as GRNmap.exe or GRNmodel.m

**Comment by kdahlquist** [comment]
The behavior that we want is that the input spreadsheet can be in any folder and that the output sheet should go to the same folder as the input spreadsheet.

**Comment by juansc** [comment]
This issue is fixed in the beta branch code.

**Comment by kdahlquist** [comment]
This has been tested with the file "Input_21_Gene_Network_Sigmoid_Model.xls" and the beta code as of 2015-04-15 and was found to work.
