### ISSUE TITLE
not all graphs being saved

### ISSUE THREAD

**Issue by bengfitzpatrick** [kdahlquist/GRNmap#45]
The current beta version does not save the last gene's graph. The figure appears: the jpg does not?

**Comment by kdahlquist** [comment]
Moved this up to a priority zero since the the other priority zeroes are finished for this week.

**Comment by juansc** [comment]
Please review.

**Comment by kdahlquist** [comment]
This has been tested with the file "Input_21_Gene_Network_Sigmoid_Model.xls" and the beta code as of 2015-04-15 and was found to work.
