### ISSUE TITLE
GRNmap website is reporting analytics under GRNsight's ID

### ISSUE THREAD

**Issue by dondi** [kdahlquist/GRNmap#46]
GRNmap's web statistics are currently appearing under GRNsight's Google Analytics account, probably because the analytics JavaScript is using GRNsight's identifier, and not GRNmap's. Please fix the JavaScript to use the proper identifier for GRNmap. Do a web-search to find documentation on how to determine the right fragment for your account.

**Comment by trixr4kdz** [comment]
Fixed. ID was correct, but I moved the whole script to before </head> tag.
