### ISSUE TITLE
Add Grace and Trixie to People page

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#47]
We need to add Grace and Trixie to the People page on the web site.  Under Current Students, it should read:

Juan Carrillo (LMU Computer Science, Applied Mathematics '16) Spring 2014 - Present
Katherine (Grace) Johnson (LMU Biochemistry '17) Spring 2015 - Present
Trixie Roque (LMU Computer Science '17) Spring 2015 - Present
Natalie Williams (LMU Biology '17) Fall 2014 - Present

**Comment by trixr4kdz** [comment]
Done
