### ISSUE TITLE
News Item about version 1.0.2 and 1.0.4 available for download

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#48]
We will need to be in the habit of creating news items when we make releases.  See how this is done at GRNsight here: http://dondi.github.io/GRNsight/news.html

In our case we need to say "GRNmap v1.0 Is Released and Available for Download"
* Date the item to the actual release date
* Create a release notes section on the About page like GRNsight has for us to announce the release notes

**Comment by trixr4kdz** [comment]
Updated News page and created Release Notes section. Still need to fix About page.

**Comment by kdahlquist** [comment]
We need retroactive news items for releases v1.0.2 and  v1.0.4.  Get the dates off of the releases page and put the News items in the list accordingly.

**Comment by trixr4kdz** [comment]
Added news items for v1.0.2 (March 11, 2015) and v1.0.4 (March 24, 2015)

**Comment by kdahlquist** [comment]
Confirmed.  Closing this one because my note to change the last modified date was recorded on a different issue.
