### ISSUE TITLE
News item about SoCal SysBio conference

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#49]
We need to add the news item about my presentation at the SoCal SysBio conference, modeled after what is on the GRNsight page (leaving out the part about @NAnguiano since that was about GRNsight).  We can add the abstract and slide links to the Publications page.

**Comment by trixr4kdz** [comment]
Updated News page and added SoCal SysBio Conference presentation slides and abstract to Publications page
