### ISSUE TITLE
pick up and set up posters friday 3/20

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#54]
The posters have all been printed.  If someone is free Friday morning, can he or she pick them up all from me and put them up in UH?

If not we can do it later.

**Comment by anuvarsh** [comment]
I can pick them up at 11am if no one is available before then.

**Comment by juansc** [comment]
I can pick up Trixie's and I's poster at 9am

**Comment by Nwilli31** [comment]
Grace and I can pick ours up at 9 tomorrow.

Thanks,
Natalie

**Comment by kdahlquist** [comment]
@anuvarsh, please come pick up your poster at 11:00.  The others 
already picked up theirs.
