### ISSUE TITLE
Upload symposium posters to GitHub

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#56]
I sent an e-mail to @juansc and @trixr4kdz with the final printed versions of the symposium posters for upload to the GitHub repository.

Please remove (delete) the older version of the poster and replace with these ones.  Please observe the naming conventions for these files for now and any future posters.

**Comment by juansc** [comment]
Done.

**Comment by juansc** [comment]
Please review.

**Comment by kdahlquist** [comment]
Verified and closing.
