### ISSUE TITLE
Generate list of transcription factors that have significant changes in expression in Dahlquist microarray data

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#6]
* @kdahlquist will complete a final version of the microarray dataset for use with future GRNmap development
* @Nwilli31 will generate a list of transcription factors that have expression patterns significantly different than zero from the within-strain ANOVA test.  B & H corrected p value of < 0.05
* @Nwilli31 will generate a list of transcription factors that have expression patterns that are significantly different between strains using the between-strain ANOVA test.  B&H corrected p value < 0.05.
* @Nwilli31 will take the list of significant genes (B&H corrected p value < 0.05) from each of the within-strain and between-strain ANOVA tests and do an enrichment analysis to find out which transcription factors have targets enriched in those lists.
* We will then use this information to create new GRNs to test.

**Comment by bengfitzpatrick** [comment]
this one closed up awhile back when we were looking elsewhere.
