### ISSUE TITLE
Implement test file structure and naming convention as documented in wiki

### ISSUE THREAD

**Issue by dondi** [kdahlquist/GRNmap#61]
GRNmap has converged on a file structure and naming convention for test and demo files. It is [documented here](https://github.com/kdahlquist/GRNmap/wiki/Naming-Convention-and-Test-Files-Organization). This issue represents the initial task of making the current set of files fit these conventions.

**Comment by trixr4kdz** [comment]
For spreadsheets that have the same number of genes, edges, etc., we will have an optional # to append at the end to differentiate.

**Comment by kdahlquist** [comment]
Given Issue #74 where we will systematically test all 16 possibilities for running the code, we may need to think further about our organization and naming convention here.

Right now at the top level we have split off the forward and estimation tests into separate folders, which makes sense.

I am wondering if underneath both of these we should make sub-folders for MM and Sigmoid to further organize the tests.

Also, should we add to the filename information about fix vs. est for P and b?  What about for making graphs?  Or these could be organized in folders?

Let's talk about this at our next meeting.

**Comment by kdahlquist** [comment]
We looked at what was on the wiki for http://www.openwetware.org/wiki/GRNmap_Test_Inputs Issue #74 and we are going to make a slight change to the way it is shown there.

Say fixP-1 or fixP-0, fixb-1 or fixb-0 for the conditions of fixing or estimating P or b.  It's shorter and doesn't re-use the word estimate.  Will use "graph" or "no-graph" for the graphing condition.

Once either @tessaam or @trixr4kdz fixes the filenames on the wiki, they can close this issue.

Also, on the wiki, please make the filenames visible in the hyperlink labels.

All of these 16 test files can also be uploaded to the test-files folder on GitHub (beta branch).

**Comment by kdahlquist** [comment]
We will not do any further subdivision of folders in test-files at this time.

**Comment by tessaam** [comment]
The file names are corrected on the wiki. 

http://openwetware.org/wiki/GRNmap_Test_Inputs#Observations_from_test
