### ISSUE TITLE
@juansc walk @trixr4kdz through entire codebase

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#62]
Because @juansc will not be around in the summer, he and @trixr4kdz need to get together for @juansc to walk her through the entire codebase sometime during the next two weeks.

**Comment by juansc** [comment]
In addition to walking through the code, I will walk @trixr4kdz through the process of creating a release as well as walking her through the process of how to packaging a release.

**Comment by kdahlquist** [comment]
This is in progress.  As they go through it, they are figuring out what can be preallocated to zeros and also changing the variable names to be more informative.

**Comment by kdahlquist** [comment]
As we have started SURP already, I assume that this has been accomplished and am closing.
