### ISSUE TITLE
num_genes vs num_active_genes question

### ISSUE THREAD

**Issue by juansc** [kdahlquist/GRNmap#64]
num_genes vs num_active_genes

**Comment by bengfitzpatrick** [comment]
should be the same.  replace the second with the first.

**Comment by kdahlquist** [comment]
Will close when Juan has fixed this.  This is something that was needed in an older version of the model that is no longer needed.

**Comment by kdahlquist** [comment]
@trixr4kdz is going to look in the code to see if this has been done.

**Comment by kdahlquist** [comment]
@trixr4kdz has verified that this has been done in beta and in master, so closing.
