### ISSUE TITLE
Possible redundant vars in lse.m

### ISSUE THREAD

**Issue by trixr4kdz** [kdahlquist/GRNmap#65]
``` matlab
    GRNstruct.GRNOutput.t          = t;     % Are these redundant?
    GRNstruct.GRNOutput.model      = model; % Are these redundant?
    log2FC(qq).model               = (log2(model))';
    log2FC(qq).simtime             = simtime';
    GRNstruct.GRNModel(qq).model   = log2FC(qq).model;
    GRNstruct.GRNModel(qq).simtime = log2FC(qq).simtime;
```

**Comment by bengfitzpatrick** [comment]
Yes, Trixie, the top two should go away.  Not only are they redundant, but they are also incomplete. Note that the GRNstruct.GRNModel( : ).model structure has a model array for each simulated strain.  The array "model" is number of times by number of genes, and the qq index in your query delineates the strains.  The GRNstruct.GRNOutput.model field contains only one model array, and we don't know which strain it represents (probably the last one in the list).  The GRNstruct.GRNModel( : ).simtime arrays are a small amount of wasted space, as each strain's model should have been computed on the same time grid (which is in the input sheet's simtime array), but it's better for simplicity of future use to keep those things together, even if we keep a few copies of the same data. let me know if you have questions about this response.

**Comment by kdahlquist** [comment]
We're going to set this aside for now, in case changing it breaks something else.

**Comment by trixr4kdz** [comment]
After scanning the lse.m file, it looks like these redundant variables have been removed when @juansc and I were working on a previous issue. We will perform a more thorough investigation of this issue at our Monday meeting.

**Comment by kdahlquist** [comment]
On Tuesday 9/13 the coding team will investigate this and confirm whether this is closable.

**Comment by trixr4kdz** [comment]
I've verified that the redundant variable in the lse.m file was indeed removed when we were working on a previous issue.

**Comment by kdahlquist** [comment]
OK, closing now.
