### ISSUE TITLE
Text for About page for releases

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#66]
v1.0
This is the first release of the GRNmap code and executable.

v1.0.2
GRNmap v1.0.2 includes the following new features and bug fixes:
* Some known bugs in v1.0 have been fixed.
* The code has been updated to be compatible with MATLAB 2014b. Version 1.0 would fail when generating graphs because of the way that MATLAB treated figure handles had changed.
* GRNmap now outputs an individual worksheet containing the optimized expression values for each strain.

v1.0.4
GRNmap v1.0.4 includes the following new features and bug fixes:
* The requirements for the input spreadsheet have been modified as follows:
    *The name of the parameter iestimate has been replaced with estimateParams.
    * The name of the parameter igraph has been replaced with makeGraphs.
    * These changes were made to make the parameter names more descriptive.
* The output spreadsheet now contains all the worksheets from the spreadsheet.
* The output spreadsheet now includes worksheets for all the parameters that were estimated by GRNmap. These output sheets have names that begin with "out_".

v1.0.6
I will work on this one next.

**Comment by kdahlquist** [comment]
GRNmap v1.0.6 includes the following new features and bug fixes:
* The input Microsoft Excel workbook is now not required to be in the same directory as the GRNmodel code and can now be located in any folder.
* A bug was fixed where the last graph generated was not being automatically saved; now all graphs are saved in the same folder as the input workbook.
* The input test files were updated to comply with changes made to the optimization parameter variable names made in release v1.0.4.
* Ensured that all temporary information is cleared between consecutive estimation or simulation runs.
* GRNmap now outputs log2expression sheets for each strain.
* The test file structure and naming convention has been implemented as documented in the wiki (https://github.com/kdahlquist/GRNmap/wiki/Naming-Convention-and-Test-Files-Organization).

For the last bullet point, please just hyperlink the word "wiki" to the wiki page instead of showing the URL.

**Comment by trixr4kdz** [comment]
Finished during last meeting of Spring semester

**Comment by kdahlquist** [comment]
I have some edits that I would like you to make to clean up the grammar and phrasing:  For simplicity, I've copied the release notes again here so you can just copy and paste the entire block of text instead of trying to make the changes piecemeal. (There is a mystery as to why the outputting of the optimized log2 expression values show up in notes for v1.0.2 and v1.0.6, but I'm going to not worry about that for now.  There were actually duplicate issues for that, but let's just leave it alone and move on.)

v1.0 (no changes)
This is the first release of the GRNmap code and executable.

v1.0.2
GRNmap v1.0.2 includes the following new features and bug fixes:

-  Some known bugs in v1.0 have been fixed.
- The code has been updated to be compatible with MATLAB 2014b. Version 1.0 would fail when generating graphs because the way that MATLAB treats figure handles had changed.
- GRNmap now outputs individual worksheets containing the optimized expression values for each strain.

v1.0.4
GRNmap v1.0.4 includes the following new features and bug fixes:

* The requirements for the "optimization_parameters" worksheet in the input Microsoft Excel workbook have been modified as follows: 
 * The name of the parameter iestimate has been replaced with estimateParams.
 * The name of the parameter igraph has been replaced with makeGraphs.
 * These changes were made to make the parameter names more descriptive.
 * The output workbook now contains all of the worksheets from the input workbook.
* The output workbook now includes worksheets for all of the parameters that were estimated by GRNmap. These output sheets have names that begin with "out_".

v1.0.6
GRNmap v1.0.6 includes the following new features and bug fixes:

* The input Microsoft Excel workbook is now not required to be in the same directory as the GRNmodel code and can now be located in any folder.
*  A bug was fixed where the last graph generated was not being automatically saved; now all graphs are saved in the same folder as the input workbook.
*  The input test files were updated to comply with changes made to the optimization parameter variable names made in release v1.0.4.
*   Ensured that all temporary information is cleared between consecutive estimation or simulation runs.
*  GRNmap now outputs the log<sub>2</sub> expression values generated from the forward simulation of the model as individual worksheets for each strain.  The worksheets are named with the convention "<strain designation>_log2_optimized_expression".
*  The test file structure and naming convention has been implemented as documented in the wiki (https://github.com/kdahlquist/GRNmap/wiki/Naming-Convention-and-Test-Files-Organization).

For the last bullet point, please make the link open in a _blank page and add a period to the end of that sentence.

**Comment by kdahlquist** [comment]
I made a tiny correction to the level of bullets in v1.0.4 above that I messed up when I copied it over.

**Comment by kdahlquist** [comment]
I have also gone back and changed the release notes on the releases page to reflect the changes I made above.

**Comment by trixr4kdz** [comment]
I've updated this page

**Comment by kdahlquist** [comment]
I'm going to close this one and open new issues for release notes/about pages for newer versions than 1.0.6
