### ISSUE TITLE
Removing residual kk_max

### ISSUE THREAD

**Issue by juansc** [kdahlquist/GRNmap#67]
kk_max is a residual variable that shouldn't be there anymore. We need to change the following code and change it so that it's not a for loop (just remove the for line and its corresponding end.)

``` matlab
if estimateParams
    % This performs the optimization
    for kk = 1:kk_max 
         % ...code....
    end
    % ...code...
end
```

Additionally, kk_max has to be removed from all input sheets.

**Comment by bengfitzpatrick** [comment]
Where did this issue come from? Unless someone convinces me otherwise, kk_max should remain.  There may be cases as we grow the code and data where restarting the optimization is necessary.

**Comment by juansc** [comment]
We saw that kk_max is always 1 for all the input sheets that were created and so it seemed that maybe that loop was something left over from previous development. If you think we should keep it then we can leave kk_max in the code.

**Comment by bengfitzpatrick** [comment]
Please do.
