### ISSUE TITLE
Search literature to find mRNA production and degradation rates for yeast

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#7]
Suggested reference:
* “A Complete Set of Nascent Transcription Rates for Yeast Genes” PLoS One Nov. 2010 Vicent Pelechano, Sebastian Chavez, Jose E. Perez-Ortın

**Comment by kdahlquist** [comment]
Shalem et al. 2008 Transient transcriptional responses to stress are
generated by opposing effects of mRNA production
and degradation Molecular Systems Biology 4; Article number 223; doi:10.1038/msb.2008.59

**Comment by kdahlquist** [comment]
@Nwilli31 and @GraceJohnson will compile what they have so far on their OpenWetWare wiki, including:
* full bibliographic citation to paper
* hyperlink to full text on publisher web site
* links to supplementary data files

We will begin to look at the data to see what we can use.

**Comment by GraceJohnson** [comment]
Bibliography document can be found to download on my Electronic lab notebook on Open Wet Ware: http://openwetware.org/wiki/Katherine_Grace_Johnson_Electronic_Lab_Notebook#September_9.2C_2015

**Comment by Nwilli31** [comment]
Look at the supplementary data of the Wang (2002 http://www-genome.stanford.edu/turnover/data.shtml) and the Shalem (2008 http://msb.embopress.org/content/4/1/4) paper for the degradation & the production rates.

Will we get values for all the transcription factors, because there is always the potential of missing data?

Attempt to sort out the data. Hopefully, the values with agree with each other.

Wang: click on the text file --> 1.0 Mb (convert half-life information in decay rates)

**Comment by GraceJohnson** [comment]
Half lives from the Wang paper extracted using Microsoft Access and compiled into an Excel sheet named "Wang_halflife_TF.xlsx" available on this page: http://openwetware.org/wiki/Katherine_Grace_Johnson_Electronic_Lab_Notebook#November_4.2C_2015.  
Reference list of the 203 transcription factors was from the Harbison list given in the Belle Excel sheet by @kdahlquist. For the Wang paper, two replicates for half lives were reported. Half-life data was available (at least one replicate) for 193 out of the 203 transcription factors. Average and standard deviations for the two replicates were calculated in the Excel sheet.

**Comment by kdahlquist** [comment]
This is a task for @kdahlquist for the summer.

**Comment by kdahlquist** [comment]
@Nwilli31, I'm going to have you get back into this.  I want you to check out this reference:
* Neymotin et al. (2014) http://rnajournal.cshlp.org/content/20/10/1645.short

Today, I did a pubmed search on the title/abstract words "mRNA degradation" AND "saccharomyces" and reviewed the 132 hits.  I found the Neymotin article in the reference list of another article I found.  I'd like you to to a title/abstract search on "mRNA decay" AND "saccharomyces" and a second title/abstract search on "mRNA turnover" AND "saccharomyces" and review the hits.  At the meeting on Monday, I can share with you the articles I already found.  We might also need to re-do the searches using "RNA degradation", "RNA decay", and "RNA turnover" instead of "mRNA".

I would also like you to do a cited reference search in the Web of Science for the Neymotin et al. (2014) article.

Neymotin et al. (2014) has half lives/degradation rates as a supplementary material file.  Please see if you can make any sense of it.  This might be the data we need for our input sheets.

**Comment by kdahlquist** [comment]
@Nwilli31 has downloaded data and started looking at it.

Supplemental table 5.

**Comment by kdahlquist** [comment]
@Nwilli31, did you see that there was a ReadMe file in the supplementary materials here:

http://rnajournal.cshlp.org/content/suppl/2014/08/08/rna.045104.114.DC1/REVreadme_Table.txt

That explains what each of the columns in each of the tables is.

It seems the the column labeled "thalf", column J of Supplemental table S5 is the value we want to use.  

We convert the half-life to the degradation rate by the formula

(LN(0.5))/[half-life]

We want to do this instead of directly using their alpha value because it is corrected for dilution by cell division.

When we next meet, we'll make our own spreadsheet to use as a reference for the input workbooks.  We'll need to figure out if there is missing data for TFs that we have in our networks.

Although they have computed synthesis rates, let's not use them to begin with.  They didn't measure it directly in their experiments, so they are using other people's data.  We might want to compare our estimated *P* with theirs, but let's keep it simple to start.

**Comment by Nwilli31** [comment]
I made preliminary degradation rates using their half life in a column next to the last column of their data. We can go over that in the meeting

**Comment by kdahlquist** [comment]
OK, we'll start keeping track of the data files on the DahlquistLab repository.

**Comment by kdahlquist** [comment]
There is a directory for degradation_rates on the Dahlquist Lab repository here:  https://github.com/kdahlquist/DahlquistLab/tree/master/data/degradation_rates.

@Nwilli31 should deposit an Excel file with her modifications to the Neymotin data, which should include new worksheets for each computation and a "raw" worksheet that is the Neymotin S5 table unchanged.

* Order the list by standard name.
* We need to pull out the "Harbison 203" transcription factors, take the median and use this for any missing values we may have.

**Comment by Nwilli31** [comment]
I uploaded the file to the DahlquistLab repository with a quick description of how I computed the degradation rates and paired the two data sets (Harbison & Neymotin).

**Comment by kdahlquist** [comment]
I started looking at the degradation rates file and skimming it, it looks fine.  I will just want to double-check the steps and calculations.  I found in your OpenWetWare wiki where you documented what you had done, and I copied it over to a README on the DahlquistLab repository.  It will need a little more detail if someone was going to re-trace your steps.

One thing that will need to be changed is that we want to round the final degradation rates to four decimal points using `=ROUND()` in Excel.

I'm going to try to come back to this before I leave for Tennessee.

**Comment by kdahlquist** [comment]
I'm not going to be able to review this before I leave, I think.  Proceed with the workbooks, #245 and go ahead and include the mRNA deg rate data if you get there; I'll follow up with reviewing when I get back and before we run any of the input workbooks.

**Comment by kdahlquist** [comment]
Today, I discovered that @Nwilli31 had used the median of *all* the genes for missing values instead of just the *Harbison203* set.  She fixed her dataset and uploaded it with a new name on the DahlquistLab repository.  It is called: NEW_Matched_Neymotin_Harbison_correctedDegRates.xlsx

I compared the corrected values with ones I did independently and found they all agreed.

@bklein7 just needs to double-check his workbooks to see if any of them were using the median for missing degradation rates and substitute the new median.  He should also highlight any values that were substituted like this for future reference.

I'm going to still go through the new version and make any cosmetic changes that I think need to be done and I will also review the documentation.  We are close to closing this!

**Comment by kdahlquist** [comment]
So, I can say with great pleasure that this task is now finished (a year later, almost to the day that it was opened).  I updated the files and the readme at the DahlquistLab repository here:  https://github.com/kdahlquist/DahlquistLab/tree/master/data/degradation_rates.

Please use the median value from the worksheet "degradation_rate_Harbison202" for any missing values.

@Nwilli31, would you please put a link to the list of additional papers you found in your lit search.  Record the papers in your OWW notebook and link to it in a comment on this issue.  I'm going to close the issue, but you can still comment on it by clicking on the "closed" header at the top of the issue list to find it.
