### ISSUE TITLE
why michaelis_menten.m but no sigmoid.m

### ISSUE THREAD

**Issue by trixr4kdz** [kdahlquist/GRNmap#70]

**Comment by bengfitzpatrick** [comment]
That was a programming choice somewhere in the past.  The general_network_dynamics_sigmoid.m function includes all the computation necessary to produce the differential equation. Nick and Katrina must have chosen to farm out part of the computation of general_network_dynamics_mm.m to an intermediary function michaelis_menten.m to make the calling code look cleaner.  In retrospect I'm not sure it worked like that.

**Comment by kdahlquist** [comment]
No action needs to be taken, so closing.
