### ISSUE TITLE
Rig it so that we record downloads of the executable from the GRNmap downloads page

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#72]
Learn the Google Analytics API so that you can manually report a "page hit" outside of the standard JavaScript fragment that they supply.

Then, establish a URL, e.g., /grnmap/download, that represents the count of downloads from the github.io.

Finally, the download link on that website can be hooked up to JavaScript that manually reports a "hit" on that URL whenever a download is triggered.

Sample code for how GRNsight does it with an upload can be seen here:

    https://github.com/dondi/GRNsight/blob/master/web-client/public/js/upload.js#L88

**Comment by trixr4kdz** [comment]
@dondi how did you create the URL using Google Analytics? I've been exploring the GA interface but I can't seem to find a way to create /grnmap/download

**Comment by kdahlquist** [comment]
@trixr4kdz needs to fix capitalization and the session control.

**Comment by trixr4kdz** [comment]
I've changed the virtual page name to "GRNmap/download" instead of "grnmap/download" and added sessionControl

**Comment by kdahlquist** [comment]
@trixr4kdz what is the status of this?  Is it implemented?  I referenced this in Issue #71.

**Comment by kdahlquist** [comment]
@trixr4kdz needs to grab the data from Google Analytics, GRNsight uses the server to do it, but we don't have one for GRNmap.  @dondi will use GRNsight server to do this.

**Comment by dondi** [comment]
I've tweaked the GRNsight server code to respond to /grnmap with a `path` parameter. Once this is deployed, we can install the browser code to retrieve and display this information.

**Comment by kdahlquist** [comment]
The next time that GRNsight beta is merged with master, then take "beta" out of the URL of code called "ga-report.js"

**Comment by dondi** [comment]
Client-side code to model is included in documentation.html now. It is a combination of some HTML at the end of the page plus adding a `script` element. With some exceptions (mainly the specialized download count), this code can generally be added to all of the other .html files.

**Comment by dondi** [comment]
OK, I’ve updated the specialized JavaScript for the downloads page so that you get per-version counts, plus totals in the end. Remind me to walk you through what I did sometime; consider it a free preview of CMSI 370 :)

**Comment by trixr4kdz** [comment]
Ok, thanks @dondi. I'll assign it to @kdahlquist so she can check

**Comment by kdahlquist** [comment]
I think this is done.  Some of the counters on the Downloads page were not registering anything, so I made sure to click on all of them.  I'm going to wait to see that it registers before closing this.

**Comment by kdahlquist** [comment]
The downloads have registered, so I am closing this.  Reminder to everyone to download the executable and code from our Downloads page instead of the GitHub page so that we can increase the counters :)
