### ISSUE TITLE
Add system requirements section to About page, Documentation page, and readme on main GitHub site

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#76]
We need to describe the system requirements for running GRNmap from code and for running the executable.

This information needs to appear in three places:
* A distinct section called *Compatibility*, on the About page (below "Availability)
* At the top of the Documentation page
* In the readme blurb on the main GRNmap developer page

We probably need to subdivide this into "Running GRNmap from Code" and "Installing and Running the GRNmap stand-alone executable"

The information we need to provide is:
* operating system and version (Windows-only, only tested on Windows 7).
* minimum RAM, what is least amount of RAM we've used to run it successfully?
* minimum processor speed, what is minimum processor speed we've run it on.
* MATLAB version 2014b
* I believe the executable needs administrator privileges, right?
* need Microsoft Excel (version?)
* anything else?

**Comment by kdahlquist** [comment]
See #79 for text to use.

**Comment by trixr4kdz** [comment]
I've updated the Compatibility and Documentation pages and the README file with the System Requirements for Running the GRNmap source code as written in Issue #79

**Comment by trixr4kdz** [comment]
I made the subdivided Compatibility only on the About page, but the last 2 bullet points are the same for both "Running from code" and "Running Stand-Alone".

**Comment by bengfitzpatrick** [comment]
when you created the executable, @trixr4kdz , you created a windows executable.  Is there a way to create a mac executable as a separate entity?  Since the mac version of matlab has problems with xlsread and xlswrite, the compilation may fail... but can we try it?

**Comment by kdahlquist** [comment]
@trixr4kdz, I like how you organized the compatibility section on the about page.  Can you add the executable requirements that you wrote to the executable section of the downloads page as well?

Also, I didn't notice before, but please remove the "s" from "Executable" in the section header on the download page.  Thanks.

**Comment by trixr4kdz** [comment]
@bengfitzpatrick I believe it is possible to create a mac application. I've been looking into it a bit and found out that Xcode can be used to compile into a mac executable so I think it's worth a shot.

@kdahlquist I've updated the Downloads page to also have the System Requirements section for the Executable and removed the extra "s"

**Comment by kdahlquist** [comment]
A few more tweaks to this one:
* On the About page, for the phrase "Installing and Running the GRNmap stand-alone executable: " please make the r in "running" lower case.
* Change the section to be "System Requirements and Compatibility" instead of just "Compatibility"

Once you have done that, copy this entire section to the Documentation page.  Right now the Documentation page refers only to the code, but should have the whole thing about the executable and code.

**Comment by trixr4kdz** [comment]
Done

**Comment by kdahlquist** [comment]
Confirmed and closing.
