### ISSUE TITLE
Make collapsible sections on News page, by year

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#77]
See how this was done on the GRNsight News page http://dondi.github.io/GRNsight/news.html.

**Comment by trixr4kdz** [comment]
Separated news items by year

**Comment by kdahlquist** [comment]
Please default the 2015 section to "open" instead of closed.

**Comment by trixr4kdz** [comment]
Finished

**Comment by kdahlquist** [comment]
confirmed and closing
