### ISSUE TITLE
Update news items for LMU symposium and SoCal Systems Biology conference

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#78]
Update the news items for the LMU symposium and SoCal Systems Biology conference so that they read identically to what is shown on the GRNsight news page.  http://dondi.github.io/GRNsight/news.html

**Comment by trixr4kdz** [comment]
Updated News page to reflect what is on GRNsight

**Comment by kdahlquist** [comment]
Don't forget to change the last modified date on the web pages, it must be done manually.

**Comment by trixr4kdz** [comment]
Date has been changed

**Comment by kdahlquist** [comment]
verfied and closing
