### ISSUE TITLE
Organize and provide additional download links on Downloads page

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#79]
Right now the Download page is still linked to the v1.0 executable.

Upon thinking about it, we should organize this page so that there are download links to all releases of GRNmap.  There should be two main sections, one for the source code and one for the executable.  Each of them should include the system requirements information from issue #76.  Then each of those sections should have subsections for the various versions.

Would we then be able to track downloads of source code from this page (I know we can't track from the GitHub page, but could we do it from this page like described in issue #72).

**Comment by kdahlquist** [comment]
Let's fix the current download button to correctly download executable v1.0.6 as priority 0, but the rest organization can stay 0.5.

**Comment by trixr4kdz** [comment]
Fixed the download button to say v1.0.6 and linked it to the zip file on GitHub

**Comment by dondi** [comment]
Look at this for comparison:

https://github.com/dondi/GRNsight/blob/beta/web-client/public/js/upload.js#L89-L94

I tried the Download link just now and I spotted the reported hit being sent to Google Analytics (you can see this in the Network part of the browser dev tools as a `collect` URL).

What shows up in the Google Analytics page itself? Some hits but incorrect? No hits at all? That will help us isolate the problem.

**Comment by dondi** [comment]
I performed a quick test just now and the count appears to hit OK. I suggest you add the `sessionControl` parameter (linked above) plus capitalize the `/GRNmap/` part of the path (right now it reports as `/grnmap/` in Google Analytics).

**Comment by kdahlquist** [comment]
The last two comments by @dondi should be on issue #72.

**Comment by trixr4kdz** [comment]
I've added sections in the Downloads page so that all released versions of the executable and source code are available. Still need to add the system requirements though.

**Comment by trixr4kdz** [comment]
Do we want to track downloads of source code and executable separately or just as one?

**Comment by kdahlquist** [comment]
I guess my answer is that if we can track each item separately, then we should do so.  That would mean tracking each version of the executable and each version of the code separately.

**Comment by trixr4kdz** [comment]
I've updated the Downloads page to count downloads of different versions separately.

**Comment by kdahlquist** [comment]
Here is some more information to provide on the Downloads page:

Underneath the header "Download GRNmap Executables" but before the section for v1.0.8, please add the following text.

"We recommend using the latest version of the GRNmap executable.  Links to download prior versions are provided for archival purposes."

For each of the executable sections, on a line after the sentence: "Clicking the button will begin the download of a file that is approximately 688 MB."  add the following sentence: "You may need to disable your antivirus software for the download to complete properly."

**Comment by kdahlquist** [comment]
* Please take the "s" off of the word Codes in the header "Download GRNmap Source Codes"
* Please add the line immediately below the "Download GRNmap Source Code Header: "We recommend using the latest version of the GRNmap source code. Links to download prior versions are provided for archival purposes."
* Then immediately below that line, please add a collapsible section called "System Requirements and Compatibility"  In this section put the following:
 * The GRNmap code was developed and tested with MATLAB R2014b; it may not function properly with other versions of MATLAB.
 * GRNmap is only compatible with the Windows operating system because of the function it uses to read and write Microsoft Excel spreadsheets.  It has only been tested on Windows 7.
 * We recommend running GRNmap with a minimum of 8.00 GB of RAM and a 2.40 GHz processor.  GRNmap may be compatible with slower systems; the amount of RAM and processor speed will affect the speed with which GRNmap completes the estimation.

This section can then be added to the About page, the documentation page, and the ReadMe page on GitHub, as requested in issue #76 .

**Comment by tessaam** [comment]
The Biology department laptop I ran the executable on had 4.00 GB of  RAM and a 2.60 GHz processor.

**Comment by trixr4kdz** [comment]
When you said immediately below the line "Download GRNmap Source Code", did you mean below it when it is closed or below when it is open (i.e add "We recommend..." below the header but above the section to download v1.0.8)?

**Comment by trixr4kdz** [comment]
My bad. I didn't see the comment for the executable. I'm assuming the additional lines go inside the collapsible sections

**Comment by trixr4kdz** [comment]
Updated the Downloads page

**Comment by kdahlquist** [comment]
I like the organization and content.  The last sentence at the bottom of the page needs to be changed slightly:
* It now reads "Source archives have been download 7 times."
* Change to "Source code archives have been downloaded 7 times." adding the word "code" and putting download in the past tense.

Some of the counters did not have values, but I'm assuming that is because they were never downloaded yet.  I went through and clicked on all them them so when Google Analytics catches up, they should all have been downloaded at least once.

**Comment by trixr4kdz** [comment]
Done

**Comment by kdahlquist** [comment]
Confirmed and closing.
