### ISSUE TITLE
Publications page needs to be updated with LMU Symposium abstracts/posters

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#80]
Update the publications page with the LMU Symposium abstracts and posters.  See http://dondi.github.io/GRNsight/publications.html for a model.

Rename our header called "Abstracts" to "Posters".

I think we can link to Juan's SACNAS poster in the code repository, as well.

**Comment by trixr4kdz** [comment]
I've changed "Abstracts" to "Posters" and added the 2015 LMU Symposium abstract with a link that allows visitors to download the poster.

It would seem that @juansc removed his SACNAS poster from the master branch, but the pdf version is still in the test_suite branch. Right now, the poster is linked to the abstract in the Publications page.

**Comment by kdahlquist** [comment]
To answer your questions:
1. Yes, we should open a GRNmap account on SlideShare--I just haven't gotten around to it.  I'll open an issue for it and assign it to me.
2. I would like the SACNAS poster to end up on the master branch again.  I want us to actually store the posters here on GitHub for posterity, even if we also have them on SlideShare.  Can you add it back to the beta branch so that the next time we merge to master it will show up there again?  We'll leave this issue open until the next merge so that we remember to do this.

Also, we are going to need to add a section for the West Coast Biological Sciences Undergraduate Research Conference that Grace and Natalie presented at.  I'll post the issue on GRNsight and when they fix it there you can copy it over.

**Comment by kdahlquist** [comment]
It's all finally done:
* All posters and talks have been pushed to the repository under "documents"
* All files were renamed according to the convention authorlastname_location_date_poster/talk
* beta merged into master branch
* All posters and presentations added to Publications page with abstracts and links to download the corresponding files.
* I'm going to delete abstracts from the wiki that are duplicated on the publications page, but I'm still going to close this issue!
