### ISSUE TITLE
Add Tessa Morris to People page

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#81]
We need to add Tessa  to the People page.

Under Research Assistants > Current Students, put her in alphabetical order as follows:
*Tessa Morris (LMU Biomathematics '16) Summer 2015 - Present

**Comment by trixr4kdz** [comment]
Added Tessa Morris to Current Students

**Comment by kdahlquist** [comment]
Don't forget to change the last modified date on the web pages, it must be done manually.

**Comment by trixr4kdz** [comment]
Changed date

**Comment by kdahlquist** [comment]
confirmed and closing
