### ISSUE TITLE
Update funding information on About page

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#82]
We need to update the funding information on the About page.  Replace what is there with this (preserving hyperlinks):

This work is partially supported by NSF award 0921038 (Kam D. Dahlquist and Ben G. Fitzpatrick), the Loyola Marymount University Summer Undergraduate Research Program 2014 (Juan Carrillo) and 2015 (Trixie Roque), the LMU Honors Summer Research Fellowship 2015 (K. Grace Johnson and Natalie Williams), and the LMU Rains Research Assistant Program 2015 (Tessa Morris).

**Comment by trixr4kdz** [comment]
Updated Funding section

**Comment by kdahlquist** [comment]
Don't forget to change the "last modified" date on all web pages you alter.  It has to be done manually, unfortunately.

**Comment by trixr4kdz** [comment]
Changed date

**Comment by kdahlquist** [comment]
confirmed and closing
