### ISSUE TITLE
Put "Under construction" flag on Documentation page

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#83]
I see that some of the documentation for the input file has been moved over from the wiki to the Documentation page.  Some of this information is out of date and some of it will possibly be changed for the summer work.

Can you comment this out in the code for now until we've settled on the changes we are going to make?

Please put the note "This page is under construction.  For current documentation, please see the GRNmap wiki." with a hyperlink from the word "wiki" to the wiki.

**Comment by trixr4kdz** [comment]
Replaced content in Documentation with "This page is under construction...see the GRNmap wiki."

**Comment by kdahlquist** [comment]
confirmed and closing

**Comment by kdahlquist** [comment]
Don't forget to change the last modified date on the web pages, it must be done manually.

**Comment by trixr4kdz** [comment]
Changed date

**Comment by kdahlquist** [comment]
confirmed and closing
