### ISSUE TITLE
Test GRNmap executable

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#84]
In addition to testing the GRNmap code (as in #74), we also need to put the executable through its paces.  Ideally, we would try this on a "virgin" computer that hasn't seen the installation and also on one that does not have MATLAB installed on it to see how it works.  @kdahlquist will look into getting a department laptop for us to use for testing for the summer.

**Comment by tessaam** [comment]
The executable works as long as the computer has administrator privileges and none of the directory names (folder name or administrator name) have any spaces. Anti-virus software also prevented the download of GRNmap from the GRNmap website (http://kdahlquist.github.io/GRNmap/index.html) so it must be disabled for the download to work. However, the anti-virus software did allow downloads from github (https://github.com/kdahlquist/GRNmap).

http://openwetware.org/wiki/GRNmap_Testing_Report_Executable_2015-06-08_TM#Discussion

**Comment by kdahlquist** [comment]
Did you guys try running the GRNmap executable from the Student (non-administrator) login after you had installed it as an Administrator?  If not, please do so.

**Comment by kdahlquist** [comment]
Also, @trixr4kdz, you mentioned that you were able to download the executable on your Mac.  Did you try running it?  I assumed that it wouldn't work because running it from code doesn't work on a Mac, but we should test to make sure.

**Comment by tessaam** [comment]
GRNmap worked on the Student account after it was installed on the administrator login GRNmap. 
http://openwetware.org/wiki/GRNmap_Testing_Report_Executable_2015-06-08_TM

@kdahlquist I have my Mac with me. Would you like me to try running the executable on it?

**Comment by kdahlquist** [comment]
Yes, that would be great!  Thanks.

At 03:59 PM 6/9/2015, you wrote:

**Comment by tessaam** [comment]
I timed how long it took to run different input sheets:
Took 29:07.18 for 22-genes_47-edges_Dahlquist-data_Sigmoidal_estimation_fixb-0_fixP-0_graph.xlsx
Took 3:34.52 for 4-genes_6-edges_Dahlquist-data_Sigmoidal_estimation_fixb-0_fixP-0_graph.xlsx
Took 3:43.75 for 22-genes_47-edges_Dahlquist-data_Sigmoidal_estimation_fixb-1_fixP-1_graph.xlsx

I also ran two input sheets at the same time. GRNmap will produce the output sheets (.mat and .xlsx) as well as the plots, however the figures will overwrite if they are in the same folder. I only ran 4-genes_6-edges_Dahlquist-data_Sigmoidal_estimation_fixb-0_fixP-0_graph.xlsx and 22-genes_47-edges_Dahlquist-data_Sigmoidal_estimation_fixb-1_fixP-1_graph.xlsx at the same time, but it did not increase the run time by more than a minute.

**Comment by kdahlquist** [comment]
this is fully documented so closing
