### ISSUE TITLE
LSE viewable in counter window

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#86]
I thought that in previous versions of GRNmap, the LSE value was shown in the counter window.  Am I remembering this wrong?

**Comment by kdahlquist** [comment]
It actually used to be there, but now it's gone.  It would be nice to have it back.

**Comment by bengfitzpatrick** [comment]
fixed this. ready for testing once the code is uploaded. L-curve branch transmitted to @kdahlquist

**Comment by bengfitzpatrick** [comment]
merge of beta and L-curve closes this.
