### ISSUE TITLE
Finalize names and contents of each worksheet in input and output files

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#88]
Besides talking about the overall priorities and tasks for the summer, we need to discuss this at our next meeting.  This is related to issue #4, but I want to use this issue to describe what we actually want our input and output workbooks to look like.

Input workbook:
As near as I can tell, the input workbook needs the following sheets:
* production_rates
* degradation_rates
* one sheet per strain of log2 expression data
 * right now they are simply named by the strain designation, they should be called "strain designation_log2_expression" for symmetry with the output worksheets; we will create another issue to make a task to add this functionality.
* network
* network_weights
* optimization_parameters
* network_b: 
 * For the "network_b", let's call it "threshold_b"; a separate issue will be opened to set this task.  It will need to be changed in the code and in the input and output sheets.

All of these input sheets should be copied over "as is" to the output workbook.

Output workbook:
* The output workbook should contain the following sheets copied exactly from the input workbook:
 * production_rates
 * degradation_rates
 * one sheet per strain of log2 expression data called "strain designation_log2_expression"
 * network
 * network_weights
 * optimization_parameters
 * threshold_b.
* The following worksheets are new to the output workbook:
 * "strain designation_log2_optimized_expression" for each strain
 * optimized_production_rates (produced when an estimation is run with fix_P =0)
 * network_optimized_weights (currently this is called "out_network_optimized_weights" the "out_" needs to be removed
 * network_optimized_b (or if we change it, optimized_threshold or optimized_threshold_b; produced when fix_b =0)
 * "strain designation_sigmas" (this would be new functionality; I think they are being computed, but are not currently outputted)
 * "optimization_diagnostics" this would be a new worksheet that has stuff like the LSE value in it and possibly other stuff we want to also output that doesn't fit into any of the other sheets.  We will create a new issue for this task.

**Comment by trixr4kdz** [comment]
I've implemented the naming scheme detailed in this issue except for the output sheets "strain designation_sigmas" and "optimization_diagnostics"

**Comment by trixr4kdz** [comment]
I've fixed the code so that the "strain designation_sigmas" (aka standard deviations) worksheet is now outputted

**Comment by kdahlquist** [comment]
the optimization_diagnostics has been opened as a separate issue #106 

changing the order of the "strain designation_sigmas" sheets is now issue #107

Everything else is verified to be done in the beta branch by @tessaam, so closing this issue.
