### ISSUE TITLE
Bug: fix_b is doing the opposite, =1 no estimate, =0 estimate in v1.0.6

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#90]
I downloaded the zipped code from the v1.0.6 release page.  I used it to run the file "21-genes_50-edges_Dahlquist-data_Sigmoid_estimation.xls" in the test-files > data-samples folder.

In the optimization_parameters worksheet:
* fix_P = 0
* fix_b = 1

Which should mean to estimate the production rates, but do not estimate the thresholds.

Yet, in the resulting output file, there were no new production rates, only the original production_rate sheet with the original values.  And there was a new sheet "out_network_b" that had non-zero values for three genes:
* YPR104C	FHL1	0.041275461
* YNL167C	SKO1	0.125534455
* YLR182W	SWI6	0.075032991

As @trixr4kdz runs through the 16 permutations of input sheets (#74), be on the lookout for stuff like this and also make sure that you can reproduce this bug.

**Comment by tessaam** [comment]
I verified the bug. It occurred with a different input file.

**Comment by kdahlquist** [comment]
Actually, it might be the case that instead of being "switched" like I said above, it's the case that either the production rates are not being estimated at all or, if they are, they are not being written to the output workbook.

@tessaam and @trixr4kdz have produced all 16 test input and output files referred to in #74.  They are stored on the OpenWetWare wiki here: http://www.openwetware.org/wiki/GRNmap_Test_Inputs

We could compare two runs where the only difference was to estimate P and not estimate P and see if there were changes to the weight terms.  Changes to the weight terms would be expected if one run estimated P and the other didn't.

**Comment by kdahlquist** [comment]
@Nwilli31 has confirmed that part of what is going on is that when fix_b =0, it is estimating b and when fix_b =1, it is not estimating b, so those are switched.

I'm going to separate out the production rates as a separate issue.

**Comment by trixr4kdz** [comment]
I fixed the code fragment that causes the network_optimized_b worksheet to not be outputted

**Comment by trixr4kdz** [comment]
When testing, be sure to change the input worksheet "network_b" into "threshold_b". Also, the new output sheet containing b is now named "optimized_threshold_b" instead of "network_optimized_b"

**Comment by bengfitzpatrick** [comment]
@trixr4kdz @kdahlquist I am assuming this code is in the beta branch.  I will test it this evening.

**Comment by trixr4kdz** [comment]
@bengfitzpatrick Yes the bug fix is in the beta branch

**Comment by kdahlquist** [comment]
@tessaam has verified that this is fixed in the beta branch.
