### ISSUE TITLE
MATLAB article on using Excel with MATLAB

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#91]
I don't know if this is useful, but here it is:
http://blogs.mathworks.com/pick/2010/04/16/from-excel-column-labels-to-numbers/?s_v1=6275&elq_cid=934546

**Comment by trixr4kdz** [comment]
I think this will be especially useful for reading off Excel sheets for unit testing

**Comment by kdahlquist** [comment]
@juansc will put this on the wiki and then will close this.

**Comment by juansc** [comment]
Done. The page is called [Resource for Working with Excel Files When Using MATLAB](https://github.com/kdahlquist/GRNmap/wiki/Resource-for-Working-with-Excel-Files-When-Using-MATLAB).
