### ISSUE TITLE
input file cannot be located on Desktop

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#92]
We've uncovered a bug where the input file cannot be located on the Desktop.  It can be in a folder that is on the Desktop, but not on the Desktop directly.  The error message reads:

Error using copyfile
Cannot write to destination:
C:\Users\kdahlqui\Desktop\13-genes_20-edges_McGee-data_Sigmoid_estimation_output.xlsx.
Use the 'f' option to override.

Error in output (line 20)
copyfile(GRNstruct.inputFile, output_file);

Error in GRNmodel (line 34)
GRNstruct = output(GRNstruct);

This has been verified on two different computers.  The input file does work if it is in a different folder.

The graphs save on the Desktop, but the _output.xlsx is not created.

**Comment by trixr4kdz** [comment]
This has been fixed.

**Comment by kdahlquist** [comment]
Confirmed fixed with the test file 21-genes_50-edges_Dahlquist-data_MM_estimation.xlsx (took the .xls version from test_files > data_samples and Saved As .xlsx)
