### ISSUE TITLE
input file cannot be in folder with space characters in name

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#93]
We have discovered a bug where if the input file is located in a folder with space characters in the name, such as 

Desktop\Microarray Data Analysis

it won't save the output file or graphs.

The error message is:
Error using inputcheck (line 40)
Multiple inputs that look like file names: 'C:\Users\kdahlqui\Desktop\Microarray' and 'Data'.

Error in print (line 156)
    [pj, devices, options ] = inputcheck( pj, inputargs{:} );

Error in graphs (line 43)
    eval(['print -djpeg ' directory 'figure_' num2str(kk)]);

**Comment by kdahlquist** [comment]
I have confirmed that it is the space characters at fault.  I removed them from the folder name "MicroarrayDataAnalysis" and the files saved just fine.

**Comment by juansc** [comment]
Fixed please review.

**Comment by kdahlquist** [comment]
Confirmed fixed with the test file 21-genes_50-edges_Dahlquist-data_MM_estimation.xlsx (took the .xls version from test_files > data_samples and Saved As .xlsx), which I put in a folder called "check space in name" (which was on the Desktop, incidentally.)
