### ISSUE TITLE
Production rates not being either estimated or output to workbook

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#94]
I have separated this out from Issue #90.  It appears that either the production rates are not being estimated or they are not being output to the workbook.

@tessaam and @trixr4kdz have produced all 16 test input and output files referred to in #74. They are stored on the OpenWetWare wiki here: http://www.openwetware.org/wiki/GRNmap_Test_Inputs

We could compare two runs where the only difference was to estimate P and not estimate P and see if there were changes to the weight terms. Changes to the weight terms would be expected if one run estimated P and the other didn't.

**Comment by trixr4kdz** [comment]
I fixed the code fragment that causes the production rates worksheet to not be outputted

**Comment by trixr4kdz** [comment]
When testing, be sure to change the input worksheet "network_b" into "threshold_b"

**Comment by kdahlquist** [comment]
@tessaam has verified that this is fixed on the beta branch
