### ISSUE TITLE
test what happens when initial guesses for weights are not 1

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#95]
Take one of the input workbooks that has already been run and choose initial guesses for weights that are not 1. Look at:
* LSE
* number of iterations
* values of weights, b's, and Production rates of results
in comparison to a previous run that was exactly the same except for this change.

**Comment by GraceJohnson** [comment]
We have run most tests with all w=0. We are obtaining estimated weights, b's and p's that are the same as w=1 out to about the third decimal place.

**Comment by kdahlquist** [comment]
@bengfitzpatrick says "Is there a gene that is always repressed and what the b's are in those cases."

**Comment by kdahlquist** [comment]
should be part of testing plan, need more test spreadsheets.  @GraceJohnson and @Nwilli31 should share with @tessaam so they can be codified and added to set of test files.

**Comment by kdahlquist** [comment]
@tessaam needs to create some test cases for the unit tests for this.

**Comment by GraceJohnson** [comment]
@tessaam Notes for our testing can be found here: http://openwetware.org/wiki/GRNmap_Testing_Report:_Non-1_Initial_Weight_Guesses_2015-05-28

The most useful runs were done with all strains:
initial weights: 0, -1, -3, 3, 10, randomly distributed between -1 and 1, and randomly distributed between -3 and 3

**Comment by bengfitzpatrick** [comment]
natalie doesn't understand why this is open, so we closed it.
