### ISSUE TITLE
compute the "ideal" LSE to compare to the actual LSE output by GRNmap

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#96]
The minimum of the LSE would be attained when Log<sub>2</sub> xi (t, theta) - 1/# flasks average of datapoints  (not sure if this is transcribed right)

**Comment by kdahlquist** [comment]
@GraceJohnson, it occurred to me that you should add up the LSEs from all of the single strain runs and then compare it to the all strain run, otherwise it isnt a fair comparison.

**Comment by bengfitzpatrick** [comment]
alternatively, we should compare single strain estimations to ideal single strain sums of squares.

**Comment by GraceJohnson** [comment]
@bengfitzpatrick I have compared single strain estimation (for wt) to its ideal sum of squares. I also computed the ideal using all five strains (wt plus the four deletion strains), by following the same procedure and adding up all the sums and dividing by the grand total of data points. Is this how the code computes the LSE when data from multiple strains must be estimated? Or does is add up the individual LSE values for each strain, resulting in a higher total LSE?

**Comment by bengfitzpatrick** [comment]
@GraceJohnson can you provide some numbers related to your comparisons?

**Comment by GraceJohnson** [comment]
@bengfitzpatrick This page contains MATLAB output LSE values for several strains, alone and combined: http://openwetware.org/wiki/GRNmap_Testing_Report:_Strain_Run_Comparisons_2015-05-27. As each strain is added to the analysis, the LSE ouput by the code seems to increase linearly (i.e. the LSE for one strain is around 7, for two strains around 15, etc.). For the ideal sum of squares calculations, I got an LSE 0.4875 for wt alone and 0.5520 for all strains. I will email you the spreadsheet I used to get these values.

**Comment by kdahlquist** [comment]
@bengfitzpatrick doesn't think that the LSE computed for the multiple strains is being computed correctly.  It might be dividing by the number of datapoints for a single strain, but it should be dividing by the total number of datapoints. He needs to check the MATLAB code.

What should be put out in diagnostic worksheet #106  is
* LSE
* penalty
* minimum (ideal) LSE

**Comment by trixr4kdz** [comment]
@bengfitzpatrick I've merged beta with master, but I didn't fix the order of the worksheets yet. You can check the code now though since I've just finished the release

**Comment by bengfitzpatrick** [comment]
@trixr4kdz  I downloaded the master last night. When did you do the merge?

**Comment by trixr4kdz** [comment]
I merged them yesterday, before 7 I think

**Comment by bengfitzpatrick** [comment]
@trixr4kdz sehr gut.  I aim to post a new beta by Monday with the diagnostics spread sheet added.

**Comment by kdahlquist** [comment]
@GraceJohnson should test this (beta branch)

**Comment by GraceJohnson** [comment]
Beta tested. New version correctly computes min LSE. Notes and files can be found here: http://openwetware.org/wiki/Katherine_Grace_Johnson_Electronic_Lab_Notebook#June_15.2C_2015

In addition, for the strain I ran (wt alone), the LSE was only slightly more than the min LSE, 0.508 compared to 0.487. Correspondingly, the model outputs are more dynamic and seem to fit the data's average. However, it should be noted that, with an alpha of 0.001 and estimating P and b, this run took over 400,000 iterations and 2.5 hours.

**Comment by kdahlquist** [comment]
verified and closing
