### ISSUE TITLE
Test .xls vs. .xlsx for the same exact input file

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#97]
We need to test whether using the exact same input file as a .xls vs. an .xlsx gives the same output.
Use Save As in Excel to change the filetype and run the same input file twice and compare results.

**Comment by tessaam** [comment]
For both the Sigmoidal and Michaelis Menten an .xls and an .xlsx file gave the same output.
http://openwetware.org/wiki/GRNmap_Testing_Report_.xlsx_vs._.xls_2015-05-27#Observations

**Comment by tessaam** [comment]
This was tested again using the most updated version of GRNmap-beta (updated as of 9:42 am 2015-06-03). The w, P, b (Sigmoidal only), LSE, Penalty term, and the counter are the same between the .xlsx and .xls versions for one MM (4-genes_6-edges_artificial-data_MM_estimation_fixP-0_graph) and one Sigmoidal (4-genes_6-edges_artificial-data_Sigmoidal_estimation_fixb-0_fixP-0_graph). 
http://openwetware.org/wiki/GRNmap_Testing_Report_.xlsx_vs._.xls_2015-06-03_TM

These values were also compared to the test to see if  Identical Runs with Same Code Version and Same Input Workbook (Issue #99)  resulted in the same  w, P, b (Sigmoidal only), LSE, Penalty term, and the counter values, which they did.

**Comment by kdahlquist** [comment]
confirmed that there is no difference, so closing
