### ISSUE TITLE
compare two successive identical runs with same version code and same input workbook

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#99]
I don't know if we've actually done this.  Have we actually run the same input workbook twice with the same code and version of MATLAB and compared results?

We would want to compare the values of the estimated w, b, P parameters, as well as the number of iterations and the LSE.

Be sure to use "clear all" between runs.

**Comment by tessaam** [comment]
I compared identical copies of both a Sigmoidal and MM workbook from the sixteen_tests subfolder. I found no difference between the values of the estimated w, b, P parameters, or the number of iterations, LSE, and penalty term.

http://openwetware.org/wiki/GRNmap_Testing_Report_Identical_Runs_with_Same_Code_Version_and_Same_Input_Workbook_2015-06-01#Discussion
